### ISSUE TITLE
ActiveRecord::Relation .size regression with distinct select

### ISSUE THREAD

**Issue by aripollak** [rails/rails#16182]
This test case works as written in Rails 3.2, but fails on Rails 4.1.4 and master:

``` ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'rack', github: 'rack/rack'
    gem 'sqlite3'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts do |t|
    t.integer :foo
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_size_bug
    Post.create! foo: 1
    Post.create! foo: 2
    Post.create! foo: 2

    assert_equal [1, 2], Post.select(:foo).uniq.map(&:foo)
    assert_equal 2, Post.select(:foo).uniq.length
    assert_equal 2, Post.select(:foo).uniq.count
    # Rails 4.1+ selects COUNT(DISTINCT id) instead of COUNT(DISTINCT foo) as above:
    assert_equal 2, Post.select(:foo).uniq.size
  end
end
```

**Comment by magikid** [comment]
This is still failing in Rails 5 even after updating uniq -> distinct.

**Comment by skanev** [comment]
Ping @rafaelfranca

**Comment by avit** [comment]
This is related to my #7121 and https://groups.google.com/forum/?fromgroups=#!topic/rubyonrails-core/mwBehQcEduU

I still contend that count options belong on the `count` method, and should not be picked up from whatever gets chained onto the relation.

**Comment by kamipo** [comment]
Fixed by c6cd9a59f200863ccfe8ad1d9c5a8876c39b9c5c.

**Comment by tommyalvarez** [comment]
@kamipo Did this fix made it into Rails 5.1.5 ? I'm still seeing this bug in a pretty standard query of mine.

**Comment by kamipo** [comment]
@tommyalvarez Can you provide a reproducible script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb?

This fix 6df9b69b2363734175d8869393e83e6ce8b4d7b6 has already been in 5.1.5.

**Comment by tommyalvarez** [comment]
@kamipo here it goes:

```
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.2.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments.create!
    post.comments.create!
    post.comments.create!

    post2 = Post.create!
    post2.comments.create!
    post2.comments.create!
    
    assert_equal 3, post.comments.count
    assert_equal 5, Comment.count
    assert_equal post.id, Comment.first.post.id
    post_count =  Post.joins(:comments).select("distinct posts.id").size

    assert_equal post_count, 2
    Post.destroy_all
    Comments.destroy_all
  end
end
```

Maybe it has to do with the fact i'm using `.select("distinct table_alias.id")` instead of `.distinct("table_alias.id")` ? I don't know if both cases should be equivalent, the former doesn't work as you can see from the minitest, the latter works fine in my project.

_Gemfile.lock_ just in case: 

```
GIT
  remote: git@github.com:tommyalvarez/fourthbase.git
  revision: b30d762fd75d86b7befeda278a7131dce3e6d997
  specs:
    fourthbase (2.1.5)
      rails (>= 4.0)

GIT
  remote: git@gitlab.com:igaltex/stacktex.git
  revision: 0d08ae8cde06fe3e22eb77190a4799851fc796de
  specs:
    stackmint (0.0.2)
      stackmint_capistrano (= 0.0.2)
    stackmint_capistrano (0.0.2)
      recap

GIT
  remote: https://github.com/EdmundMai/batched_query.git
  revision: 44cea80d2dc857c1f650d1401684118385a7869c
  specs:
    batched_query (0.0.1)

GIT
  remote: https://github.com/randym/axlsx.git
  revision: 776037c0fc799bb09da8c9ea47980bd3bf296874
  ref: 776037c0fc799bb09da8c9ea47980bd3bf296874
  specs:
    axlsx (2.1.0.pre)
      htmlentities (~> 4.3.4)
      mimemagic (~> 0.3)
      nokogiri (>= 1.6.6)
      rubyzip (>= 1.2.1)

GEM
  remote: https://rubygems.org/
  specs:
    aasm (4.12.3)
      concurrent-ruby (~> 1.0)
    actioncable (5.1.5)
      actionpack (= 5.1.5)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.5)
      actionpack (= 5.1.5)
      actionview (= 5.1.5)
      activejob (= 5.1.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.5)
      actionview (= 5.1.5)
      activesupport (= 5.1.5)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.5)
      activesupport (= 5.1.5)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_job_status (1.2.1)
      activejob (> 4.2)
      activesupport (> 4.2)
    active_record_query_trace (1.5.4)
    activejob (5.1.5)
      activesupport (= 5.1.5)
      globalid (>= 0.3.6)
    activemodel (5.1.5)
      activesupport (= 5.1.5)
    activerecord (5.1.5)
      activemodel (= 5.1.5)
      activesupport (= 5.1.5)
      arel (~> 8.0)
    activerecord-sqlserver-adapter (5.1.6)
      activerecord (~> 5.1.0)
      tiny_tds
    activesupport (5.1.5)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    annotate (2.7.3)
      activerecord (>= 3.2, < 6.0)
      rake (>= 10.4, < 13.0)
    arel (8.0.0)
    axlsx_rails (0.5.2)
      actionpack (>= 3.1)
      axlsx (>= 2.0.1)
    bcrypt (3.1.12)
    builder (3.2.3)
    byebug (10.0.2)
    capistrano (2.15.9)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    carrierwave (1.2.2)
      activemodel (>= 4.0.0)
      activesupport (>= 4.0.0)
      mime-types (>= 1.16)
    choice (0.2.0)
    combine_pdf (1.0.14)
      ruby-rc4 (>= 0.1.5)
    composite_primary_keys (10.0.3)
      activerecord (~> 5.1.0, >= 5.1.5)
    concurrent-ruby (1.0.5)
    connection_pool (2.2.1)
    crass (1.0.4)
    currency-in-words (0.1.3)
      actionpack (>= 3.1)
      activesupport (>= 3.1)
    database_cleaner (1.7.0)
    devise (4.4.3)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.3)
    docile (1.3.0)
    dotenv (2.2.2)
    dotenv-rails (2.2.2)
      dotenv (= 2.2.2)
      railties (>= 3.2, < 6.0)
    erd (0.4.0)
      nokogiri
      rails-erd (>= 0.4.5)
    erubi (1.7.1)
    erubis (2.7.0)
    et-orbi (1.1.1)
      tzinfo
    factory_bot (4.8.2)
      activesupport (>= 3.0.0)
    factory_bot_rails (4.8.2)
      factory_bot (~> 4.8.2)
      railties (>= 3.0.0)
    faker (1.8.7)
      i18n (>= 0.7)
    fast_jsonapi (1.2)
      activesupport (>= 4.2)
    ffi (1.9.23)
    foreman (0.63.0)
      dotenv (>= 0.7)
      thor (>= 0.13.6)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    haml (4.0.7)
      tilt
    haml-rails (0.9.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 5.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
    highline (1.7.10)
    html2haml (2.2.0)
      erubis (~> 2.7.0)
      haml (>= 4.0, < 6)
      nokogiri (>= 1.6.0)
      ruby_parser (~> 3.5)
    htmlentities (4.3.4)
    i18n (0.9.5)
      concurrent-ruby (~> 1.0)
    json (2.1.0)
    jwt (2.1.0)
    kaminari (1.1.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.1.1)
      kaminari-activerecord (= 1.1.1)
      kaminari-core (= 1.1.1)
    kaminari-actionview (1.1.1)
      actionview
      kaminari-core (= 1.1.1)
    kaminari-activerecord (1.1.1)
      activerecord
      kaminari-core (= 1.1.1)
    kaminari-core (1.1.1)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.6.0)
      launchy (~> 2.2)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.2)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    method_source (0.9.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.2)
    mini_magick (4.8.0)
    mini_mime (1.0.0)
    mini_portile2 (2.3.0)
    minitest (5.11.3)
    monetize (1.7.0)
      money (~> 6.9)
    money (6.11.3)
      i18n (>= 0.6.4, < 1.1)
    money-rails (1.11.0)
      activesupport (>= 3.0)
      monetize (~> 1.7.0)
      money (~> 6.11.0)
      railties (>= 3.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (4.2.0)
    net-ssh-gateway (2.0.0)
      net-ssh (>= 4.0.0)
    newrelic_rpm (5.2.0.345)
    nio4r (2.3.1)
    nokogiri (1.8.2)
      mini_portile2 (~> 2.3.0)
    open4 (1.3.4)
    orm_adapter (0.5.0)
    pg (1.0.0)
    pg_search (2.1.2)
      activerecord (>= 4.2)
      activesupport (>= 4.2)
      arel (>= 6)
    public_suffix (3.0.2)
    puma (3.11.4)
    pundit (1.1.0)
      activesupport (>= 3.0.0)
    rack (2.0.5)
    rack-cors (1.0.2)
    rack-protection (2.0.1)
      rack
    rack-test (1.0.0)
      rack (>= 1.0, < 3)
    rails (5.1.5)
      actioncable (= 5.1.5)
      actionmailer (= 5.1.5)
      actionpack (= 5.1.5)
      actionview (= 5.1.5)
      activejob (= 5.1.5)
      activemodel (= 5.1.5)
      activerecord (= 5.1.5)
      activesupport (= 5.1.5)
      bundler (>= 1.3.0)
      railties (= 5.1.5)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-erd (1.5.2)
      activerecord (>= 3.2)
      activesupport (>= 3.2)
      choice (~> 0.2.0)
      ruby-graphviz (~> 1.2)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.1.5)
      actionpack (= 5.1.5)
      activesupport (= 5.1.5)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.1)
    rb-fsevent (0.10.3)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    recap (1.2.2)
      capistrano (~> 2.9)
      open4
      thor
    redis (4.0.1)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    rolify (5.2.0)
    rspec-core (3.7.1)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-rails (3.7.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.1)
    ruby-graphviz (1.2.3)
    ruby-rc4 (0.1.5)
    ruby_dep (1.5.0)
    ruby_parser (3.11.0)
      sexp_processor (~> 4.9)
    rubyzip (1.2.1)
    rufus-scheduler (3.4.2)
      et-orbi (~> 1.0)
    sass (3.5.6)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    searchlight (4.1.0)
    secondbase (2.1.5)
      rails (>= 4.0)
    seed_migration (1.2.3)
    sexp_processor (4.11.0)
    shoulda-matchers (3.1.2)
      activesupport (>= 4.0.0)
    sidekiq (5.1.3)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (>= 3.3.5, < 5)
    sidekiq-cron (0.6.3)
      rufus-scheduler (>= 3.3.0)
      sidekiq (>= 4.2.1)
    simple_command (0.0.9)
    simplecov (0.16.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    tiny_tds (1.3.0)
      mini_portile2 (~> 2.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    warden (1.2.7)
      rack (>= 1.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    wicked_pdf (1.1.0)
    wkhtmltopdf-binary (0.12.4)
    yard (0.9.12)

PLATFORMS
  ruby

DEPENDENCIES
  aasm
  active_job_status
  active_record_query_trace
  activerecord-sqlserver-adapter
  annotate
  axlsx!
  axlsx_rails
  batched_query!
  bcrypt (~> 3.1.7)
  byebug
  carrierwave
  combine_pdf
  composite_primary_keys
  currency-in-words
  database_cleaner (~> 1.5)
  devise
  dotenv-rails (~> 2.2.0)
  erd
  factory_bot_rails
  faker
  fast_jsonapi
  foreman (= 0.63.0)
  fourthbase!
  haml
  haml-rails (~> 0.9)
  jwt
  kaminari
  letter_opener
  listen (>= 3.0.5, < 3.2)
  mini_magick
  money-rails (~> 1.11.0)
  newrelic_rpm
  pg
  pg_search
  puma (~> 3.7)
  pundit
  rack-cors
  rails (= 5.1.5)
  rolify
  rspec-rails
  rufus-scheduler (= 3.4.2)
  sass-rails
  searchlight
  secondbase
  seed_migration
  shoulda-matchers (~> 3.0)
  sidekiq
  sidekiq-cron (~> 0.6.3)
  simple_command
  simplecov
  spring
  spring-watcher-listen (~> 2.0.0)
  stackmint!
  tiny_tds (~> 1.3.0)
  tzinfo-data
  wicked_pdf
  wkhtmltopdf-binary
  yard

BUNDLED WITH
   1.16.2

```

**Comment by tommyalvarez** [comment]
@kamipo great thanks, i'll subscribe to that issue then.
