### ISSUE TITLE
Update_attributes always calls a save, even if the object is not modified

### ISSUE THREAD

**Issue by bastien-tilkee** [rails/rails#18400]
When doing an update_attributes that does not actually update the model (=attributes are the same as current ones), a save is called anyways.

Unless I'm missing something, I think it should not, because :

- It does a Commit in the Database that is not necessary (which of course is quick, but could be a performance gain if removed)
- As a consequence, when using touch: true, on an association the other element is touched

There is a workaround, which consists in doing an assign_attributes and then a save if changed? (which a few people seem to use by overriding the default update_attributes method) but I would find it more intuitive and logical to have this behavior by default in rails. What do you guys think ?

The code right now looks like this :
```
def update(attributes)
      with_transaction_returning_status do
        assign_attributes(attributes)
        save
      end
end
```

The idea would be to do save if changed? instead of save

**Comment by brainopia** [comment]
I'd try to see if any of the tests are failing after the change if it were up to me :smile:

**Comment by bastien-tilkee** [comment]
Yeah I didn't try to implement or test it yet, I wanted to see if this was made on purpose before :)

**Comment by rafaelfranca** [comment]
I thought `save` already do this, but I think I was wrong.

**Comment by senny** [comment]
@bastien-tilkee this was fixed a while ago. I added in some regression tests to keep it working. Thank you for reporting.

**Comment by ioquatix** [comment]
I'm still seeing this behaviour.. a lot of empty transactions, isolated it to what in practice works out to be equivalent to `model.update_attribute(:foo, model.foo))`. Writing model.foo = model.foo; model.save if model.changed? avoids the empty transaction.

**Comment by jmzbond** [comment]
The commits referenced are for `update_attribute` method not `update_attributes`. I was also curious about this so I just tested it in my console. Looks like the default behavior is `save_if_changed?` as OP suggested... I'm not seeing any SQL queries in the console & `updated_at` times do not change if I pass the exact same attributes as the model already has for `update_attribute`, `update_attributes`, and `save`. At least these are the three methods that I use most. 

I do note that an update will happen if the type is not explicitly the same. I.e., if I have an attribute that is a string type like zipcode:

    object.zipcode 
    # => "21113"
    object.zipcode = 21113
    object.save
    # => calls SQL to make the update

Object is still valid since the integer is converted to a string.
