### ISSUE TITLE
Counter cache is automatic in Rails 4.2.x when using a column name like #{table_name}_count

### ISSUE THREAD

**Issue by yan-hoose** [rails/rails#19042]
I ran into an issue where Rails 4.1 and 4.2 behave differently when a column is named like a counter cache (e.g `comments_count`) but is not configured (e.g no `counter_cache: true` on the `belongs_to` association). Here is a script to demonstrate the issue:
```ruby
# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.1.9'
#gem 'activerecord', '4.2.0'
#gem 'activerecord', '4.2.1.rc1'
require 'active_record'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :comments_count, default: 0
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    assert_equal 0, post.comments_count

    post.comments << Comment.create!
    assert_equal 1, post.comments.count
    assert_equal 0, post.comments_count
  end
end
```
This test passes with Rails 4.1.9 since it does not consider the column to be a counter cache column, however the test fails with Rails 4.2.0 and 4.2.1.rc1 on the last assertion since they consider the column as a counter cache and increment it automatically.

Setting `counter_cache: false` with `belongs_to` has no effect.

**Comment by raouldevil** [comment]
I have replicated this issue, see the console output at: https://gist.github.com/raouldevil/da036e1118b2cfaa7a40

**Comment by gmanley** [comment]
I'm digging into this issue. I'll update shortly.

**Comment by gmanley** [comment]
So I have found the culprit. https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_many_association.rb#L83 Here the check to see if it has a cached counter will return true if the default counter cache name exists on the table. There are quite a few tests that rely on this, where the model fixtures don't specify counter_cache explicitly. That worries me a bit... as this changes the current behavior. I'll have a PR up shortly, we can discuss then.

**Comment by Spone** [comment]
Hi @gmanley, this problem prevents me from updating an app to 4.2. Is there a workaround for now?

**Comment by Christian-Hansen** [comment]
Hehe, I just bumped in to this issue in production app testing on 4.2.1.rc4

**Comment by bodyfarmer** [comment]
Is there a way I can install this gem on Rails 4.2.1 while waiting for the update?

**Comment by tristang** [comment]
I've issued pull request #19683 which fixes the issue I'd encountered. 

Notably, calling `.any?` on an association that had an appropriately named `*_count` column would result in the count being taken from that column, and if it was `.zero?`, the collection would be assumed to be loaded and and return an empty array.

This patch makes the test given in this issue pass: https://gist.github.com/tristang/814e7fdedafa429297d5

As @gmanley mentions, I had to update a number of tests to explicitly use the counter_cache, so this patch could break real world apps that relied on the implicit behaviour from the presence of the column.

**Comment by tristang** [comment]
@Spone A workaround for now is to break the counter_cache by giving a column name that doesn't exist on the `has_many` association. The `belongs_to` association should be working fine already.

    class Post < ActiveRecord::Base
      has_many :tags, counter_cache: :this_is_not_a_column_that_exists
    end

**Comment by kaleb4eg** [comment]
hey @tristang  Rails 4.2.2 is already released. Was fix to this issue in release scope?

**Comment by tristang** [comment]
@kaleb4eg Looks like this issue has been retained and pushed forward to the 4.2.4 milestone. 

So I think pull request (#19683) is still required.

**Comment by kaleb4eg** [comment]
@tristang yeah, I can see, ths for response!

**Comment by pcerioli-gpsw** [comment]
Is this issue is going to fix in future releases of Rails? The suggested workaround:
```
has_many :tags, counter_cache: :this_is_not_a_column_that_exists
```
didn't work for me (I am on Rails 4.1.8).
From my understanding this is still open.

**Comment by yan-hoose** [comment]
The fix was released in Rails 4.2.4. I recommend you to upgrade.

**Comment by sb8244** [comment]
I am still getting the deprecation notice in Rails 4.2.7. I do not use `counter_cache: true` anywhere in my codebase, but I do have `model_count` columns on my models for counter caches that are controlled outside of Rails.
