### ISSUE TITLE
ActiveRecord 4.2.3 regression: unscope mutates source relation's where_values

### ISSUE THREAD

**Issue by felixbuenemann** [rails/rails#20722]
There is a regression in ActiveRecord 4.2.3 compared to 4.2.2 related to `unscope`.

Calling `unscope` on a relation modifies the `where_values` in the input relation instead of only in the returned relation:

```ruby
active = Project.active
active.where_values.size
=> 1
active.bind_values.size
=> 1
active.to_sql
=> "SELECT \"projects\".* FROM \"projects\" WHERE \"projects\".\"deleted\" = 'f'"
all = active.unscope(where: :deleted)
active.where_values.size
=> 0 # WRONG should not be modified!
active.bind_values.size
=> 1
active.to_sql
=> "SELECT \"projects\".* FROM \"projects\""
active.to_a
  Project Load (1.7ms)  SELECT "projects".* FROM "projects"  [["deleted", "f"]]
PG::ProtocolViolation: ERROR:  bind message supplies 1 parameters, but prepared statement "a1" requires 0
: SELECT "projects".* FROM "projects"
```

**Comment by felixbuenemann** [comment]
I'm currently working on a tescase using the ar template, will post a gist asap.

**Comment by felixbuenemann** [comment]
While writing a testcase I noticed that `unscope` was already mutating the source relation before 4.2.3, which I think is caused by incomplete dereferencing in spawn. The difference is that 4.2.3 only modifies the `where_values` on the source relation, while 4.2.2 also modifies the `bind_values`.

There is no indication in the docs that `unscope` is supposed to modify the source relation, so I think thats also a bug.

**Comment by felixbuenemann** [comment]
Here's the testcase: https://gist.github.com/21dc7e7496839ae06e07

On rails 4.2.3 it fails with the following exception:
```
BugTest#test_unscope_should_not_modify_source_relation:
ActiveRecord::StatementInvalid: SQLite3::RangeException: bind or column index out of range: SELECT COUNT(*) FROM "posts"
```

Interestingly it also fails on older versions, eg. 4.2.2, 4.1.0, 4.0.0:
```
Finished in 0.041740s, 23.9579 runs/s, 71.8736 assertions/s.

  1) Failure:
BugTest#test_unscope_should_not_modify_source_relation [ar-gh-30722-testcase.rb:46]:
Expected: 1
  Actual: 2
```
So it seems `unscope` has always modified the source relation in addition to the target/spawned relation.

**Comment by felixbuenemann** [comment]
This *might* be related to #20721.

**Comment by fenec** [comment]
related to #20718. because of changes from here:  https://github.com/rails/rails/commit/c99bea1df015eeff4764e2d886de90620ab9fb67
maybe @sgrif can help with this issue

**Comment by senny** [comment]
@felixbuenemann the title mentions regression but since it also fails on older versions that's not really the case. Is it possible to create a gist that started failing on `4.2.3`?

**Comment by felixbuenemann** [comment]
@senny well it fails with an exception on 4.2.3 which it didn't before. I only noticed in the process that unscope was already mutating the source previously. I could change the gist to assert on the size of where_values and bind_values as written in the initial post.

**Comment by sgrif** [comment]
The current gist is fine, I spent the morning on this and the related issues. I have a fix pretty much done, just had to run into meetings. Should have it finished tonight or tomorrow.

**Comment by felixbuenemann** [comment]
@sgrif Thanks for the update!

**Comment by sgrif** [comment]
This was fixed by https://github.com/rails/rails/commit/449241cc30545783419bd8f3cbc7b81137316001

**Comment by felixbuenemann** [comment]
@sgrif Please reopen. I am still getting the same exception with the testcase gist posted above on 4-2-stable at 449241c.

**Comment by sgrif** [comment]
I'll confirm when I can, but that test was passing for me.

**Comment by sgrif** [comment]
Fixed in #https://github.com/rails/rails/commit/21e05a041f467e0c356ece400a1edbd23f3e23cd

**Comment by felixbuenemann** [comment]
Thanks, works fine on 4-2-stable!
