### ISSUE TITLE
Illegal Instruction in active_support to_json call

### ISSUE THREAD

**Issue by sgringwe** [rails/rails#21090]
Rails 4.2.3. I am getting consistent but not replicatable yet crashes when calling to_json. This is crashing ruby itself, but the code causing the crash is in Active support and active record so I figured I'd post it here first. The error seems to end on string.rb in all cases. The most common case is this below, and happens dozens of times a day (1 per 2500 requests or so).

```
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:87: [BUG] Illegal instruction at 0x007f02bd7c8166 
Aug 01 14:20:37 handshake-production app/web.2:  ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux] 
Aug 01 14:20:37 handshake-production app/web.2:  -- Control frame information ----------------------------------------------- 
Aug 01 14:20:37 handshake-production app/web.2:  c:0161 p:---- s:0882 e:000881 CFUNC  :initialize 
Aug 01 14:20:37 handshake-production app/web.2:  c:0160 p:---- s:0880 e:000879 CFUNC  :new 
Aug 01 14:20:37 handshake-production app/web.2:  c:0159 p:0116 s:0876 e:000875 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:87 
Aug 01 14:20:37 handshake-production app/web.2:  c:0158 p:0009 s:0872 e:000871 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:91 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0157 p:---- s:0868 e:000867 IFUNC  
Aug 01 14:20:37 handshake-production app/web.2:  c:0156 p:---- s:0866 e:000865 CFUNC  :each 
Aug 01 14:20:37 handshake-production app/web.2:  c:0155 p:---- s:0864 e:000863 CFUNC  :map 
Aug 01 14:20:37 handshake-production app/web.2:  c:0154 p:0139 s:0861 e:000859 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:91 
Aug 01 14:20:37 handshake-production app/web.2:  c:0153 p:0014 s:0856 e:000854 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:91 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0152 p:---- s:0851 e:000850 IFUNC  
Aug 01 14:20:37 handshake-production app/web.2:  c:0151 p:---- s:0849 e:000848 CFUNC  :each 
Aug 01 14:20:37 handshake-production app/web.2:  c:0150 p:---- s:0847 e:000846 CFUNC  :map 
Aug 01 14:20:37 handshake-production app/web.2:  c:0149 p:0139 s:0844 e:000842 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:91 
Aug 01 14:20:37 handshake-production app/web.2:  c:0148 p:0009 s:0839 e:000838 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:93 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0147 p:---- s:0836 e:000835 CFUNC  :map 
Aug 01 14:20:37 handshake-production app/web.2:  c:0146 p:0150 s:0833 e:000832 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:93 
Aug 01 14:20:37 handshake-production app/web.2:  c:0145 p:0014 s:0829 e:000827 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:91 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0144 p:---- s:0824 e:000823 IFUNC  
Aug 01 14:20:37 handshake-production app/web.2:  c:0143 p:---- s:0822 e:000821 CFUNC  :each 
Aug 01 14:20:37 handshake-production app/web.2:  c:0142 p:---- s:0820 e:000819 CFUNC  :map 
Aug 01 14:20:37 handshake-production app/web.2:  c:0141 p:0139 s:0817 e:000815 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:91 
Aug 01 14:20:37 handshake-production app/web.2:  c:0140 p:0017 s:0812 e:000810 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:35 
Aug 01 14:20:37 handshake-production app/web.2:  c:0139 p:0024 s:0807 e:000806 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb:22 
Aug 01 14:20:37 handshake-production app/web.2:  c:0138 p:0050 s:0802 e:000801 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/json.rb:37 
Aug 01 14:20:37 handshake-production app/web.2:  c:0137 p:0038 s:0798 e:000795 METHOD /app/lib/json_whitelister.rb:7 
Aug 01 14:20:37 handshake-production app/web.2:  c:0136 p:0012 s:0792 e:000791 LAMBDA /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0135 p:---- s:0787 e:000786 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0134 p:0050 s:0782 e:000781 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:226 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0133 p:---- s:0776 e:000775 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0132 p:0012 s:0772 e:000771 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0131 p:---- s:0769 e:000768 CFUNC  :each 
Aug 01 14:20:37 handshake-production app/web.2:  c:0130 p:0030 s:0766 e:000765 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:504 
Aug 01 14:20:37 handshake-production app/web.2:  c:0129 p:0011 s:0761 e:000760 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:496 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0128 p:---- s:0759 e:000758 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0127 p:0065 s:0755 e:000754 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:296 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0126 p:---- s:0748 e:000747 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0125 p:0012 s:0744 E:001ed8 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:495 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0124 p:---- s:0741 e:000740 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0123 p:0021 s:0737 e:000736 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503 
Aug 01 14:20:37 handshake-production app/web.2:  c:0122 p:0011 s:0732 e:000731 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:496 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0121 p:---- s:0730 e:000729 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0120 p:0010 s:0726 e:000725 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:290 
Aug 01 14:20:37 handshake-production app/web.2:  c:0119 p:0026 s:0724 e:000723 METHOD /app/app/controllers/application_controller.rb:522 
Aug 01 14:20:37 handshake-production app/web.2:  c:0118 p:0012 s:0721 e:000720 LAMBDA /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0117 p:---- s:0716 e:000715 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0116 p:0050 s:0711 E:000708 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:289 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0115 p:---- s:0704 e:000703 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0114 p:0012 s:0700 E:001df8 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:495 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0113 p:---- s:0697 e:000696 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0112 p:0021 s:0693 e:000692 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503 
Aug 01 14:20:37 handshake-production app/web.2:  c:0111 p:0011 s:0688 e:000687 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:496 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0110 p:---- s:0686 e:000685 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0109 p:0010 s:0682 e:000681 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:290 
Aug 01 14:20:37 handshake-production app/web.2:  c:0108 p:0056 s:0680 e:000679 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/time/zones.rb:48 
Aug 01 14:20:37 handshake-production app/web.2:  c:0107 p:0020 s:0674 e:000673 METHOD /app/app/controllers/application_controller.rb:517 
Aug 01 14:20:37 handshake-production app/web.2:  c:0106 p:0012 s:0670 e:000669 LAMBDA /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0105 p:---- s:0665 e:000664 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0104 p:0050 s:0660 E:000778 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:289 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0103 p:---- s:0653 e:000652 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0102 p:0012 s:0649 E:000088 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:495 [FINISH] 
Aug 01 14:20:37 handshake-production app/web.2:  c:0101 p:---- s:0646 e:000645 CFUNC  :call 
Aug 01 14:20:37 handshake-production app/web.2:  c:0100 p:0021 s:0642 e:000641 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503 
Aug 01 14:20:37 handshake-production app/web.2:  c:0099 p:0077 s:0637 e:000636 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88 
Aug 01 14:20:37 handshake-production app/web.2:  c:0098 p:0009 s:0629 E:001cc8 METHOD /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19 
Aug 01 14:20:37 handshake-production app/web.2:  c:0097 p:0010 s:0625 e:000624 METHOD /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29 
```
which all happen in a to_json call of some sort.

A different stacktrace to get to the same error much less often is:
```
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/type/string.rb:35: [BUG] Illegal instruction at 0x007f18aa344166 
Aug 01 12:59:27 handshake-production app/web.2:  ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux] 
Aug 01 12:59:27 handshake-production app/web.2:  -- Control frame information ----------------------------------------------- 
Aug 01 12:59:27 handshake-production app/web.2:  c:0171 p:---- s:0931 e:000930 CFUNC  :initialize 
Aug 01 12:59:27 handshake-production app/web.2:  c:0170 p:---- s:0929 e:000928 CFUNC  :new 
Aug 01 12:59:27 handshake-production app/web.2:  c:0169 p:0039 s:0925 e:000924 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/type/string.rb:35 
Aug 01 12:59:27 handshake-production app/web.2:  c:0168 p:0018 s:0921 e:000920 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/type/value.rb:93 
Aug 01 12:59:27 handshake-production app/web.2:  c:0167 p:0009 s:0917 e:000916 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/type/value.rb:23 
Aug 01 12:59:27 handshake-production app/web.2:  c:0166 p:0011 s:0913 e:000912 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute.rb:104 
Aug 01 12:59:27 handshake-production app/web.2:  c:0165 p:0010 s:0909 e:000908 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute.rb:42 
Aug 01 12:59:27 handshake-production app/web.2:  c:0164 p:0017 s:0906 e:000905 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute.rb:37 
Aug 01 12:59:27 handshake-production app/web.2:  c:0163 p:0011 s:0903 e:000902 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_set.rb:31 
Aug 01 12:59:27 handshake-production app/web.2:  c:0162 p:0013 s:0899 e:000898 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_methods/read.rb:93 
Aug 01 12:59:27 handshake-production app/web.2:  c:0161 p:0011 s:0895 e:000894 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_methods.rb:379 
Aug 01 12:59:27 handshake-production app/web.2:  c:0160 p:0031 s:0889 e:000888 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:123 
Aug 01 12:59:27 handshake-production app/web.2:  c:0159 p:0017 s:0885 e:000884 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:94 
Aug 01 12:59:27 handshake-production app/web.2:  c:0158 p:0011 s:0878 e:000877 METHOD /app/app/models/education.rb:84 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0157 p:---- s:0874 e:000873 CFUNC  :public_send 
Aug 01 12:59:27 handshake-production app/web.2:  c:0156 p:0016 s:0869 e:000868 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:54 
Aug 01 12:59:27 handshake-production app/web.2:  c:0155 p:0062 s:0864 e:000863 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:41 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0154 p:---- s:0860 e:000859 CFUNC  :each_pair 
Aug 01 12:59:27 handshake-production app/web.2:  c:0153 p:0015 s:0857 e:000856 METHOD /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/strong_parameters.rb:185 
Aug 01 12:59:27 handshake-production app/web.2:  c:0152 p:0078 s:0853 E:000820 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_assignment.rb:35 
Aug 01 12:59:27 handshake-production app/web.2:  c:0151 p:0009 s:0846 e:000845 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/persistence.rb:251 
Aug 01 12:59:27 handshake-production app/web.2:  c:0150 p:0014 s:0844 e:000843 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351 
Aug 01 12:59:27 handshake-production app/web.2:  c:0149 p:0006 s:0842 e:000841 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213 
Aug 01 12:59:27 handshake-production app/web.2:  c:0148 p:0019 s:0840 e:000839 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184 
Aug 01 12:59:27 handshake-production app/web.2:  c:0147 p:0080 s:0834 e:000833 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213 
Aug 01 12:59:27 handshake-production app/web.2:  c:0146 p:0017 s:0830 e:000829 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220 
Aug 01 12:59:27 handshake-production app/web.2:  c:0145 p:0014 s:0825 E:000f38 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348 
Aug 01 12:59:27 handshake-production app/web.2:  c:0144 p:0007 s:0821 E:000fd8 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/persistence.rb:250 
Aug 01 12:59:27 handshake-production app/web.2:  c:0143 p:0012 s:0817 e:000816 METHOD /app/app/controllers/educations_controller.rb:26 
Aug 01 12:59:27 handshake-production app/web.2:  c:0142 p:0012 s:0814 e:000813 METHOD /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4 
Aug 01 12:59:27 handshake-production app/web.2:  c:0141 p:0013 s:0808 e:000807 METHOD /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198 
Aug 01 12:59:27 handshake-production app/web.2:  c:0140 p:0027 s:0803 e:000802 METHOD /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10 
Aug 01 12:59:27 handshake-production app/web.2:  c:0139 p:0010 s:0799 e:000798 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0138 p:---- s:0797 e:000796 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  c:0137 p:0036 s:0794 e:000792 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115 
Aug 01 12:59:27 handshake-production app/web.2:  c:0136 p:0017 s:0788 e:000787 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0135 p:---- s:0785 e:000784 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  c:0134 p:0021 s:0781 e:000780 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503 
Aug 01 12:59:27 handshake-production app/web.2:  c:0133 p:0011 s:0776 e:000775 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:496 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0132 p:---- s:0774 e:000773 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  c:0131 p:0010 s:0770 e:000769 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:290 
Aug 01 12:59:27 handshake-production app/web.2:  c:0130 p:0006 s:0768 e:000767 METHOD /app/lib/what_happened.rb:42 
Aug 01 12:59:27 handshake-production app/web.2:  c:0129 p:0012 s:0765 e:000764 LAMBDA /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0128 p:---- s:0760 e:000759 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  c:0127 p:0050 s:0755 E:000878 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:289 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0126 p:---- s:0748 e:000747 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  c:0125 p:0012 s:0744 E:000e78 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:495 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0124 p:---- s:0741 e:000740 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(rb_yield+0x495) [0x7f18bc83d395] vm.c:821 
Aug 01 12:59:27 handshake-production app/web.2:  c:0123 p:0021 s:0737 e:000736 METHOD /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503 
Aug 01 12:59:27 handshake-production app/web.2:  c:0122 p:0011 s:0732 e:000731 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:496 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  c:0121 p:---- s:0730 e:000729 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(rb_ary_each+0x52) [0x7f18bc85baa2] array.c:1803 
Aug 01 12:59:27 handshake-production app/web.2:  c:0120 p:0010 s:0726 e:000725 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:290 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_call_cfunc+0x11e) [0x7f18bc82883e] vm_insnhelper.c:1360 
Aug 01 12:59:27 handshake-production app/web.2:  c:0119 p:0026 s:0724 e:000723 METHOD /app/app/controllers/application_controller.rb:522 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_exec_core+0x2067) [0x7f18bc82dd77] insns.def:1024 
Aug 01 12:59:27 handshake-production app/web.2:  c:0118 p:0012 s:0721 e:000720 LAMBDA /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_exec+0x84) [0x7f18bc831564] vm.c:1407 
Aug 01 12:59:27 handshake-production app/web.2:  c:0117 p:---- s:0716 e:000715 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_call0_body.constprop.73+0x1a5) [0x7f18bc832cd5] vm_eval.c:180 
Aug 01 12:59:27 handshake-production app/web.2:  c:0116 p:0050 s:0711 E:002068 BLOCK  /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:289 [FINISH] 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(rb_call0+0x1aa) [0x7f18bc8339ba] vm_eval.c:59 
Aug 01 12:59:27 handshake-production app/web.2:  c:0115 p:---- s:0704 e:000703 CFUNC  :call 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(send_internal+0xae) [0x7f18bc83735e] vm_eval.c:899 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_call_cfunc+0x11e) [0x7f18bc82883e] vm_insnhelper.c:1360 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_exec_core+0x2067) [0x7f18bc82dd77] insns.def:1024 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_exec+0x84) [0x7f18bc831564] vm.c:1407 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(rb_iseq_eval+0x1a6) [0x7f18bc83dee6] vm.c:1664 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(rb_load_internal0+0x127) [0x7f18bc6ed0e7] load.c:614 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(rb_f_load+0x82) [0x7f18bc6ed3e2] load.c:643 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_call_cfunc+0x11e) [0x7f18bc82883e] vm_insnhelper.c:1360 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_call_method+0x11e) [0x7f18bc836afe] vm_insnhelper.c:1656 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_exec_core+0x1fea) [0x7f18bc82dcfa] insns.def:1054 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(vm_exec+0x84) [0x7f18bc831564] vm.c:1407 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(rb_iseq_eval_main+0x1f3) [0x7f18bc83e153] vm.c:1677 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(ruby_exec_internal+0xc4) [0x7f18bc6e7424] eval.c:252 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(ruby_run_node+0x2d) [0x7f18bc6eafbd] eval.c:317 
Aug 01 12:59:27 handshake-production app/web.2:  /app/vendor/ruby-2.2.0/bin/ruby(main+0x4b) [0x7f18bc6e6fbb] parse.y:8763 
Aug 01 12:59:27 handshake-production app/web.2:  -- Other runtime information ----------------------------------------------- 
```

**Comment by pixeltrix** [comment]
@sgringwe I suspect this may be a bug in ruby that has been fixed in the 2.2.1 or 2.2.2 patch releases - any chance you can upgrade so that we can rule that out. If it's not that then it must be related to the data being encoded - any chance of seeing what that is when you get the crash?

**Comment by sgringwe** [comment]
Hi @pixeltrix - unfortunately after upgrading to 2.2.2 the issue is still present. i'll do my best to try and print out the json being encoded.

**Comment by sgringwe** [comment]
@pixeltrix I have some example JSON from some errors but it contains some private data that might take  a while to strip out. Is there any information you could add about what type of characters could cause this, or what type of encoding that is expected?

**Comment by chancancode** [comment]
Do you happen to know the type of object being encoded?

**Comment by sgringwe** [comment]
@chancancode it is an active record object, if that's what you are referring to. unfortunately I don't know the specific value or object being encoded. Going to continue trying to get those details

**Comment by sgringwe** [comment]
@chancancode This ended up being caused by https://github.com/sparklemotion/nokogiri/issues/1332 (libxml conflciting with nokogiri and causing memory consuption). no issue with rails

**Comment by pixeltrix** [comment]
@sgringwe thanks for coming back and closing the issue - it's always helpful to know the resolution for ourselves and anyone else with similar problems.
