### ISSUE TITLE
PostgreSQL tsrange type does not go through time zone conversion on load

### ISSUE THREAD

**Issue by davidbalbert** [rails/rails#21116]
The PostgreSQL `tsrange` type is a range of `timestamp without time zone` types (the backing type for Active Record `datetime` columns). When a `tsrange` is loaded from the database, the begin and end attributes of the `Range` are instances of `Time` and in UTC, rather than `ActiveSupport::TimeWithZone` in `Time.zone`.

Assume a table called `sessions` with a `duration` column of type `tsrange` and the following code.

```ruby
Time.zone = 'Eastern Time (US & Canada)'
class Session < ActiveRecord::Base; end

s = Session.create!(duration: Time.zone.now..10.minutes.from_now)

s.duration #=> Mon, 03 Aug 2015 22:04:58 EDT -04:00..Mon, 03 Aug 2015 22:14:58 EDT -04:00

s.reload
```

## Expected results 

After reloading the `Session` instance, I expect the duration to remain in EDT.

```ruby
s.duration #=> Mon, 03 Aug 2015 22:04:58 EDT -04:00..Mon, 03 Aug 2015 22:14:58 EDT -04:00
```

## Actual results

After reloading the `Session` instance, the duration is now in UTC.

```ruby
s.duration #=> 2015-08-04 02:04:58 UTC..2015-08-04 02:14:58 UTC
```

## How to reproduce

I have uploaded an [automatic test case](https://gist.github.com/davidbalbert/90e8da8668de8dfe10ea) as a gist. It requires a running PostgreSQL server on localhost and the `createdb` and `dropdb` binaries on your path.

## How to fix

I am not positive, but I believe you would need some sort of `value.is_a?(Range)` check in [`TimeZoneConverter#convert_time_to_time_zone`](https://github.com/rails/rails/blob/17eb64213a86d14ebe44a1215f2408065fa2634a/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb#L25-L33)

Please let me know if there's any way I can be helpful.

**Comment by palkan** [comment]
I've proposed a patch [here](https://github.com/rails/rails/pull/21142).

And here is a slightly updated [test case](https://gist.github.com/palkan/707f4f7c8827fa75c4db) (run with `PATCH=1` env var to use patched Rails).

**Comment by davidbalbert** [comment]
I can still reproduce this bug on both `master` and `4-2-stable` by using the automatic test case linked in the original issue. As far as I can tell, nobody has looked at this issue nor @palkan's proposed fix, so I don't think there's any information for me to add.

That said, if there is something I could do to be helpful, please let me know.

**Comment by magikid** [comment]
It looks like this may have been fixed in 302e923.

**Comment by maclover7** [comment]
Using the reproduction script above, am able to still reproduce error on master.

**Comment by palkan** [comment]
@magikid The problem with the test case: we should explicitly tell ActiveRecord which types are TZ-aware:

```ruby
...
# First, turn on TZ awareness manually (in Rails it is activated within Railtie)
ActiveRecord::Base.time_zone_aware_attributes = true

# And add tsrange to TZ-aware types
class Session < ActiveRecord::Base
  self.time_zone_aware_types += [:tsrange]
end
...
```

And then everything works just fine (on master).
