### ISSUE TITLE
Default scopes defined on abstract classes are missing table names when called from subclasses

### ISSUE THREAD

**Issue by swrobel** [rails/rails#23413]
Similar to https://github.com/rails/rails/issues/10658 except this only seems to affect uses of `default_scope` on master. I created [an executable test case](https://gist.github.com/swrobel/7247955f409f4b24f253) to show the failure. This happens with all supported database adapters, as far as I can tell, although the way that each fails when the `table_name` is missing is different. This does not happen if `default_scope` is defined as a class method, - only when using the `default_scope -> { }` syntax.

**Comment by sgrif** [comment]
Does this issue occur on 4.2 or only on master?

**Comment by swrobel** [comment]
I've only tested on master

**Comment by sgrif** [comment]
Could you check 4.2? We need to know whether this is a new regression that should block the 5.0 release.

**Comment by swrobel** [comment]
Checked 4.2 and the behavior is worse, owing to the above-referenced #10658. Even the first assertion fails on 4.2, since abstract_class scope table_names are missing as well.

I also forgot to mention that if you define a `default_scope` class method this issue doesn't occur - only when using the `default_scope -> { }` syntax.

**Comment by sgrif** [comment]
Thanks for confirming that this issue is also present on 4.2.

**Comment by swrobel** [comment]
@sgrif I'm a bit confused why you put Milestone 4.2.6 on this since #10658 wasn't fixed on 4.2.x, only master. I would expect this fix to be targeted for 5.0.0.

**Comment by sgrif** [comment]
Because this is not a regression in 5.0.0, this is a bug which can be fixed in the next 4.2 release.

**Comment by swrobel** [comment]
Ok, good point. In that case, #10658 should be fixed on 4.2.x as well.

**Comment by Baril27** [comment]
Is there a branch that contains #23666 that isn't master. Or is waiting for a 4.2.7 release the best option?

**Comment by ischuster** [comment]
This is still happening in 4.2.7.rc1. 

Will it be fixed for 4.2.7 ?

**Comment by ischuster** [comment]
Am I doing any wrong or this bug still persist in 4.2.7?

**Comment by rafaelfranca** [comment]
It is still present in 4.2.7 and will not be fixed on it. It is only fixed in Rails 5
