### ISSUE TITLE
New app: "key must be 32 bits".

### ISSUE THREAD

**Issue by elieteyssedou** [rails/rails#25185]
### Steps to reproduce
Run ```rails s```. No more... (new app)

### Expected behavior
It should display my index. 

### Actual behavior
It fails.

Here is what is going wrong:
<img width="1426" alt="capture d ecran 2016-05-28 a 21 18 13" src="https://cloud.githubusercontent.com/assets/8143621/15629483/1f4d4a0e-251a-11e6-8423-754a356aa348.png">

Can you help me? Don't understand at all.

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.4.0dev

**Comment by maclover7** [comment]
Hmm, after some digging in some C code (💀), looks like there is a [new breaking change](https://github.com/ruby/ruby/commit/ce635262f53b760284d56bb1027baebaaec175d1) in OpenSSL, which rejects certain values for `key=`, which is the bug you are running into. :(

Looking into fixes.

**Comment by Fudoshiki** [comment]
Same issue

**Comment by bisonh** [comment]
I was having this issue yesterday. Very frustrating. Today I tried using bundle install without the exclusion of the production environment, and the error message is no longer coming up when I view localhost:3000/users.

**Comment by jeremy** [comment]
Fixed by #25192

**Comment by elieteyssedou** [comment]
Thank you ! 👍

**Comment by slhck** [comment]
I'm still seeing this issue – freshly installed Ruby 2.4.0-dev and Rails 5.0.0.

Any idea what the problem could be?

**Comment by schneems** [comment]
Temporary solution is to use Ruby 2.3.1. We'll need that patch to be backported to Rails 5 though before Christmas cc/ @vipulnsward

**Comment by vipulnsward** [comment]
It has been fixed by https://github.com/rails/rails/pull/25758 and backported in https://github.com/rails/rails/commit/15a972e080d7712aa2eb04f21472398457d1439c

**Comment by schneems** [comment]
:heart: :heart: :heart:

**Comment by jonlumb** [comment]
Still experiencing this issue running Ruby 2.4.0preview2 and Rails 5.0.0.1

The "Welcome to Rails" index screen works, but problems occur as soon as I attempt to access a scaffold that I've generated.

**Comment by Marthyn** [comment]
Fixed it with using the master branch. But `Ruby 2.4.0preview2 and Rails 5.0.0.1` definitely does not work.

**Comment by guilleiguaran** [comment]
@Marthyn what about branch 5-0-stable?

**Comment by jbae995** [comment]
Hey guys, 2017, and I'm getting the exact same error as the very top post with the screenshot. Can anyone please give me some advice on how to get past this? (REAL new to rails). 

Thanks in advance
<img width="1130" alt="screen shot 2017-01-18 at 11 29 33 am" src="https://cloud.githubusercontent.com/assets/18182025/22042780/7f7d5706-dd71-11e6-8372-9be7a29b9b1f.png">

**Comment by rafaelfranca** [comment]
Upgrade your Rails version to 5.0.1

**Comment by jbae995** [comment]
My rails version is already at 5.0.1 :( .....
<img width="127" alt="screen shot 2017-01-18 at 11 36 27 am" src="https://cloud.githubusercontent.com/assets/18182025/22042973/6115245a-dd72-11e6-859c-a881252697df.png">

any other suggestions pleaaaase?

**Comment by rafaelfranca** [comment]
By your stacktrace it is 5.0.0.1

**Comment by jbae995** [comment]
Hey Rafael, 
in the screenshots attached, at my desktop it says i am running 5.0.1, then on my unisports directory (which is the app im trying to run on the rails server) it shows 5.0.0.1. I have also tried upgrading to 5.0.1 in the unisports directory (but as shown in the screenshot, it says "success", but then when i check rails -v again, it says i have 5.0.0.1 running.... 

Sorry about the constant questions and Thanks for the help! 

<img width="712" alt="screen shot 2017-01-18 at 1 18 39 pm" src="https://cloud.githubusercontent.com/assets/18182025/22045752/0be69dce-dd81-11e6-8fc4-0859cc9be65a.png">
<img width="713" alt="screen shot 2017-01-18 at 1 16 36 pm" src="https://cloud.githubusercontent.com/assets/18182025/22045753/0be956a4-dd81-11e6-9468-60172f72c28e.png">

**Comment by cpapidas** [comment]
The problem is about the ruby 2.4.0, just for now if you want a quick solution **use ruby 2.3.1**

**Comment by kshyam** [comment]
I have got the same issue, while updating my ruby version and rails version.
@cpapidas : Thanks for your suggestion, I thought the same and changed my ruby version form 2.4.0 to 2.3.1 and it worked fine.

**Comment by matheussilvasantos** [comment]
I was using ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux] with rails 5.0.0.1. I update rails to 5.0.1 and it is fine now.

**Comment by benoittgt** [comment]
```sh
 🚴  » rails -v
Rails 4.2.8
 🚴  » ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin14]
```

Lot's of fails during tests : 
```
      ArgumentError:
        key must be 32 bytes
      # /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:79:in `key='
      # /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:79:in `_encrypt'
      # /Users/bti/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.8/lib/active_support/message_encryptor.rb:60:in `encrypt_and_sign'
```

**Comment by benoittgt** [comment]
Error is correct. We have a key size at 128. Sorry

**Comment by AlexCppns** [comment]
The whole thread assumes a ruby version of 2.4.0 but we are having the problem with ruby 2.3.3 and rails 4.2.3. We truncated the key...

**Comment by benoittgt** [comment]
@AlexCppns Maybe you should check https://github.com/rails/rails/issues/28401

**Comment by AlexCppns** [comment]
@benoittgt I couldn't relate to your link, however we upgraded to ruby 2.4.0/rails 4.2.8 and with the truncation trick, our app seems to be running again... *touching wood*.

**Comment by alucinare** [comment]
I'm not sure if this will help anyone. I was having the same error and I ran `$ bundle update` to update my gem files and it also updated to the latest version of rails. This fixed the problem.

**Comment by wisetara** [comment]
I haven't gotten any of these things to work. Am on Ruby 2.3.4 and have tried Rails 5.0.0.1, Rails 5.0.4, and 5-0-stable branch. Still get the horrible key error. I welcome any suggestions.

**Comment by wisetara** [comment]
One of my gems was using the encryptor gem as a dependency, and if it went above 1.3.0, this happened. Added encryptor to my Gemfile, locked it at 1.3.0, and all is good again.

Ruby 2.3.4/Rails 5.0.1 (and Rails 4.2)

**Comment by ahcarpenter** [comment]
Still getting this error with ActiveSupport 5.1.4 and Ruby 2.4.0

**Comment by rikbw** [comment]
I still have the same issue when upgrading from ruby version `2.2.8` to `2.5.1`. My rails version is `5.1.5`. I have a key that has a size of 40 bytes. Is this considered an issue with rails and will this be patched in future versions or not?

**Comment by iarobinson** [comment]
I was experiencing this issue earlier my solution is described beneath the heading element at the bottom of this comment.

<img width="629" alt="screen shot 2018-09-20 at 7 53 50 am" src="https://user-images.githubusercontent.com/7991933/45826978-5ddc9700-bcaa-11e8-9382-34a986028960.png">

Rails and Ruby version:
```
$ ruby -v 
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
$ rails -v
Rails 5.0.7
```

Stack trace:
```
activesupport (5.0.0) lib/active_support/message_encryptor.rb:72:in `key='
activesupport (5.0.0) lib/active_support/message_encryptor.rb:72:in `_encrypt'
activesupport (5.0.0) lib/active_support/message_encryptor.rb:58:in `encrypt_and_sign'
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:592:in `commit'
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:465:in `[]='
actionpack (5.0.0) lib/action_dispatch/middleware/session/cookie_store.rb:117:in `set_cookie'
rack (2.0.1) lib/rack/session/abstract/id.rb:353:in `commit_session'
rack (2.0.1) lib/rack/session/abstract/id.rb:224:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0) lib/active_record/migration.rb:552:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0) lib/rails/engine.rb:522:in `call'
puma (3.6.0) lib/puma/configuration.rb:225:in `call'
puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
puma (3.6.0) lib/puma/server.rb:415:in `process_client'
puma (3.6.0) lib/puma/server.rb:275:in `block in run'
puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

Running `bundle update` was the key. I upgraded Ruby from 2.0 to 2.5.1 yesterday so that may have played a role. Here's the terminal readout of the successful update which solved the problem:

<img width="715" alt="screen shot 2018-09-20 at 8 04 50 am" src="https://user-images.githubusercontent.com/7991933/45827812-1d7e1880-bcac-11e8-8747-a2e2d8cb8baa.png">

## How I Got it Running Locally

I ran `bundle install` then I followed up with `bundle update`.

Then I reset the server (`CMD+C` then `rails s`)

After updating bundle, I forgot to restart the server and spent a few minutes researching the error needlessly. So.... restarting the server is important. 🥇

My motivation for putting this solution here is that I found this thread while seeking a solution to the error. The above conversation is helpful for understanding how problems in Rails are diagnosed. There was no specific solution for a young Rails developer like myself.

**Comment by mvondoyannick** [comment]
Hi, have the same issue on rails 7.0.4 and ruby 3.1.2

```
$ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
$ rails -v
Rails 7.0.4
```

![image](https://user-images.githubusercontent.com/2368758/205606510-9a4d0dc9-6a2b-4fb4-8381-8fc8d225a5a1.png)
