### ISSUE TITLE
Getting "ArgumentError: key must be 32 bytes" after upgrading to Ruby 2.4.0-preview1 with edge Rails

### ISSUE THREAD

**Issue by jasnow** [rails/rails#25448]
### Steps to reproduce

 * Given you have a repo: https://github.com/jasnow/tasks5_edge
 * And you run "rake" (using Ruby 2.3.1), it runs without error
 * But when you upgrade the repo to use Ruby 2.4.0-preview1
 * And you run "rake", you get this error message 3 times:
```
ArgumentError:
  key must be 32 bytes
```
  * The total stacktrace is here: https://gist.github.com/jasnow/4e0d394314eafd105a039c73a395c37f

### Expected behavior
Expect the above test to run without the error message like it does with Ruby 2.3.1.

### Actual behavior
Get error:
```
ArgumentError:
  key must be 32 bytes
```
The total stacktrace is here: https://gist.github.com/jasnow/4e0d394314eafd105a039c73a395c37f

### System configuration

**Rails version**: Rails 5.1.0.alpha (revision: 0c998a14c45430afe85188f8ad13a696b077ffd9)

**Ruby version**: ruby-2.4.0-preview1

**Comment by prathamesh-sonpatki** [comment]
This is being fixed in https://github.com/rails/rails/pull/25192. Closing this issue as there is already PR and discussion around it.

**Comment by jasnow** [comment]
Thanks for the heads-up.

**Comment by schneems** [comment]
Since the PR was (partially?) reverted going to re-open this issue.

**Comment by jasnow** [comment]
Still getting error when I go from 2.3.1 to 2.4.0-preview1 on above repo.

**Comment by jasnow** [comment]
Some interesting analysis related to this issue: https://github.com/koic/rails/commit/f81781092af20dbaa773f1d48b953853b2a13d2d

**Comment by vipulnsward** [comment]
Should be fixed by https://github.com/rails/rails/pull/25758

**Comment by cnemeth** [comment]
I'm still having this issue after upgrading from ruby 2.3.1 to 2.4.0-preview2

ruby 2.4.0preview2 (2016-09-09 trunk 56129) [x86_64-darwin15]
Rails 5.0.0.1

stack trace
https://gist.github.com/cnemeth/42ae67172ebe45417473172a3a6382fc

**Comment by nateberkopec** [comment]
@cnemeth The fix hasn't been released yet (coming in 5.0.1 it looks like). You need to point your Gemfile at the 5-0-stable branch to get it now:

```ruby
gem 'rails', github: 'rails/rails', branch: "5-0-stable"
```

**Comment by alexch** [comment]
I'm getting this error under Ruby 2.4.0p0 and Rails 4.2.7.1. Is Rails 4.2 going to get this fix?

**Comment by stevensonmt** [comment]
Getting this error with Rails 5.0.0.1 and ruby 2.4.0p0.

**Comment by miltzi** [comment]
Getting this error with Rails 5.0.1 and Ruby 2.4.0p0

**Comment by pawdro** [comment]
@miltzi the same issue I had, but upgrade of fails (5.0.0.1 -> 5.0.1) helped.

**Comment by devohh** [comment]
I think you should re-open this issue since, like @miltzi, I still encounter the same problem.
I am using : Rails 5.0.2 and Ruby 2.4.0p0

```
activesupport (5.0.2) lib/active_support/message_encryptor.rb:79:in `key='
activesupport (5.0.2) lib/active_support/message_encryptor.rb:79:in `_encrypt'
activesupport (5.0.2) lib/active_support/message_encryptor.rb:60:in `encrypt_and_sign'
lib/encryptor.rb:8:in `encrypt'
lib/json_web_token.rb:22:in `encrypt'
lib/json_web_token.rb:5:in `encode'
app/mailers/user_mailer.rb:29:in `registration'
actionpack (5.0.2) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.2) lib/abstract_controller/base.rb:126:in `process'
actionmailer (5.0.2) lib/action_mailer/rescuable.rb:23:in `block in process'
actionmailer (5.0.2) lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
actionmailer (5.0.2) lib/action_mailer/rescuable.rb:22:in `process'
actionview (5.0.2) lib/action_view/rendering.rb:30:in `process'
actionmailer (5.0.2) lib/action_mailer/base.rb:595:in `block in process'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
actionmailer (5.0.2) lib/action_mailer/base.rb:594:in `process'
actionmailer (5.0.2) lib/action_mailer/message_delivery.rb:105:in `block in processed_mailer'
actionmailer (5.0.2) lib/action_mailer/message_delivery.rb:104:in `tap'
actionmailer (5.0.2) lib/action_mailer/message_delivery.rb:104:in `processed_mailer'
actionmailer (5.0.2) lib/action_mailer/message_delivery.rb:95:in `deliver_now'
app/models/user.rb:145:in `send_confirmation'
app/models/user.rb:29:in `block in begin_process'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
activerecord (5.0.2) lib/active_record/transactions.rb:211:in `transaction'
app/models/user.rb:26:in `begin_process'
app/controllers/registrations_controller.rb:9:in `create'
actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.2) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.2) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.2) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.2) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.2) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.2) lib/rails/engine.rb:522:in `call'
puma (3.7.1) lib/puma/configuration.rb:232:in `call'
puma (3.7.1) lib/puma/server.rb:578:in `handle_request'
puma (3.7.1) lib/puma/server.rb:415:in `process_client'
puma (3.7.1) lib/puma/server.rb:275:in `block in run'
puma (3.7.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by matthewd** [comment]
> ```lib/encryptor.rb:8:in `encrypt'```

That's not our code.

**Comment by devohh** [comment]
My bad @matthewd. I have deleted my message until further investigations.

**Comment by devohh** [comment]
@matthewd Thanks for pointing me in the right direction. In the lib/encryptor.rb file I had those lines :
```
passphrase = ActiveSupport::KeyGenerator.new(key).generate_key(salt)
@encryptor = ActiveSupport::MessageEncryptor.new(passphrase)
```
And everything was working fine until I updated to the last ruby version (2.4.0p0). To make it work, I added '32' as argument to the 'generate_key' method. As follow :
```
passphrase = ActiveSupport::KeyGenerator.new(key).generate_key(salt,32)
@encryptor = ActiveSupport::MessageEncryptor.new(passphrase)
```
Maybe, it would help others.

**Comment by mooreniemi** [comment]
FWIW I found this error resolved by using `5.0.2`

**Comment by Jimlian** [comment]
this error resolved by using 5.0.2

**Comment by krainboltgreene** [comment]
I'm on Ruby 2.4.0 and Rails 5.0.2 and I'm still getting this error.

Here's my code:

``` ruby
ENCRYPTION_KEY_GENERATOR = ActiveSupport::KeyGenerator.new(ENV['X'])
ENCRYPTION_KEY = ENCRYPTION_KEY_GENERATOR.generate_key(ENV['Y'])
ENCRYPTOR = ActiveSupport::MessageEncryptor.new(ENCRYPTION_KEY)
```

I'm definitely on Rails 5.0.2:

``` ruby
> Rails::VERSION::STRING
=> "5.0.2"
```

Here's me reproducing it:

```
> ENCRYPTOR.encrypt_and_sign('a')
ArgumentError: key must be 32 bytes
from /usr/local/bundle/gems/activesupport-5.0.2/lib/active_support/message_encryptor.rb:79:in `key='
```

**Comment by devohh** [comment]
It was the same for me. Did you try ? Just adding 32 as parameter to the generate_key method. It worked for me.

`ENCRYPTION_KEY = ENCRYPTION_KEY_GENERATOR.generate_key(ENV['Y'], 32)`

**Comment by amarouane** [comment]
Why don't you use :
key = SecureRandom.random_bytes(32) crypt = ActiveSupport::MessageEncryptor.new(key) encrypted_data = crypt.encrypt_and_sign('my secret random data') crypt.decrypt_and_verify(encrypted_data) => "my secret random data"

**Comment by ahcarpenter** [comment]
Still getting this error with ActiveSupport 5.1.4 and Ruby 2.4.0

**Comment by AlexanderUlitin** [comment]
@devohh yes, that works for me too, but for new generated data, but if I have previously encrypted data - I can't decrypt it after this fix.

Anyone have any idea how to decrypt the string, that was created with 64 chars key (when I used ruby 2.3)?

**Comment by gregblass** [comment]
Thank you @ahcarpenter. Not sure why there aren't 20 thumbs up for that comment.

**Comment by ahcarpenter** [comment]
haha thank @gregblass :)

**Comment by victorperez** [comment]
@AlexanderUlitin probably a bit late but leaving this here for reference, to decrypt previously encrypted data you can pass the old key (without truncate) as a second argument to `ActiveSupport::MessageEncryptor`. Example:

```
secret = ENV['SECRET_KEY'] # this represent a 64 chars key used on ruby 2.3

encryptor = ActiveSupport::MessageEncryptor.new(secret[0..31], secret)
encryptor.decrypt_and_verify(data)
```

**Comment by brunoadacosta** [comment]
Same problem here, ruby 2.6.3 and Rails 5.1.6

**Comment by elisoncampos** [comment]
Still having this issue with Ruby 2.6.1 and Rails 5.2.4.1

**Comment by jasnow** [comment]
@elisoncampos - If you would like to share your repos privately, I will see if I can help.

**Comment by elisoncampos** [comment]
> @elisoncampos - If you would like to share your repos privately, I will see if I can help.

Sadly, I cant. However https://github.com/rails/rails/issues/25448#issuecomment-441832416 fixed it for me (still doing some tests)

**Comment by mlauter** [comment]
For what it's worth, the default key length for `ActiveSupport::KeyGenerator.generate_key` still [appears to be 64](https://github.com/rails/rails/blob/v5.2.4.1/activesupport/lib/active_support/key_generator.rb#L22) and not 32 in rails v 5.2.4.1

**Comment by Jordanod1884** [comment]
were do you add this code to?
