### ISSUE TITLE
ActiveRecord sets incorrect default value when using `now()`

### ISSUE THREAD

**Issue by fnando** [rails/rails#25498]
### Steps to reproduce

Using PostgreSQL adapter, create a datetime column that has the default value `now()`

Here's a sample script reproducing the issue: [ar-datetime-default-value-bug.tar.gz](https://github.com/rails/rails/files/330888/ar-datetime-default-value-bug.tar.gz)

### Expected behavior

The schema dump should have a `now()` string as the default value.

### Actual behavior

It outputs the current timestamp.

### System configuration

- **ActiveRecord version**: 4.2.6
- **Ruby version**: 2.3.1

**Comment by rafaelfranca** [comment]
This may be something we already fixed in Rails 5 because I remember something about this. I'll check later.

**Comment by fnando** [comment]
@rafaelfranca just tried with AR 5.0.0.rc2 and the error still happens.

**Comment by kamipo** [comment]
Related #20005.

**Comment by rafaelfranca** [comment]
@fnando I told you that I remember something related 😄. Rails 5 fixes it adding support to procs for lazy evaluation of SQL expressions.

**Comment by rafaelfranca** [comment]
Thanks @kamipo for pointing to the change.

**Comment by fnando** [comment]
@rafaelfranca Thanks, dude. :*
