### ISSUE TITLE
Font issue in Rails Guides on Firefox Ubuntu

### ISSUE THREAD

**Issue by danmolloy** [rails/rails#25744]
Firefox 47.0 running on Ubuntu 16.04

On this Guides page, section 2.1 http://guides.rubyonrails.org/active_record_migrations.html

[Underscore is missing from part_number in first code box.](http://imgur.com/t3PrWj0)
[The underscore is in the html](http://imgur.com/FxLqcUj), it's just not being displayed.
[Double clicking on the code box makes it appear.](http://imgur.com/tpJcb7c)
[Changing the font to Arial makes it appear.](http://imgur.com/SyiNTok)

**Comment by vipulnsward** [comment]
@danmolloy This has been fixed on http://edgeguides.rubyonrails.org/, can you confirm?

**Comment by alexcameron89** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5634381/17817432/1ccd6c5c-6604-11e6-997c-59b872b96d74.png)

I'm still seeing it on mine. I'm using Firefox, and if I change the margin from `0` to `0.5px` in `.syntaxhighlighter a, .syntaxhighlighter div, .syntaxhighlighter code, .syntaxhighlighter table, .syntaxhighlighter table td, .syntaxhighlighter table tr, .syntaxhighlighter table tbody, .syntaxhighlighter table thead, .syntaxhighlighter table caption, .syntaxhighlighter textarea`, then it shows up. I guess the margin is cutting it off.

**Comment by maclover7** [comment]
@alexcameron89 Can you submit a PR with that change? ^^

**Comment by alexcameron89** [comment]
Gladly! Done 👍
