### ISSUE TITLE
Underscores not getting shown sometimes in Guides

### ISSUE THREAD

**Issue by greenbigfrog** [rails/rails#26189]
![image](https://cloud.githubusercontent.com/assets/6208894/17734672/e7031bbc-647d-11e6-8c9a-1dd0ccaab341.png)

I've noticed that sometimes underscores (`_`) Don't get shown/rendered in codeblocks. Marking it sometimes lets the `_` reappear... This can get a bit confusing...

No idea if it's just me (`Chromium	51.0.2704.79 (Developer Build) Ubuntu 16.04 (64-bit)`) or also occuring for others

**Comment by maclover7** [comment]
cc @fxn

**Comment by greenbigfrog** [comment]
https://twitter.com/greenbigfrog/status/766169525217820672

**Comment by rafaelfranca** [comment]
I remember it being something with the font.

**Comment by vipulnsward** [comment]
@greenbigfrog this has been fixed on http://edgeguides.rubyonrails.org/ 
Can you confirm?

**Comment by greenbigfrog** [comment]
I will need to keep testing/trying now and then, since right now I wasn't even able to make one disappear in the normal guides...

**Comment by ignatiusreza** [comment]
also ubuntu user here, it's still not showing

![notshowing](https://cloud.githubusercontent.com/assets/667726/17801959/385c62a6-6628-11e6-9419-a7520945696c.png)

weirdly.. it disappear only if the browser width is wider than a certain limit:

![out](https://cloud.githubusercontent.com/assets/667726/17802106/3407da18-6629-11e6-9d11-7072f4341761.gif)

**Comment by maclover7** [comment]
Whoops! Looks like this has already been reported over at #25744 -- closing this issue as a duplicate.

**Comment by greenbigfrog** [comment]
Didn't find it right away. Sorry.
