### ISSUE TITLE
Can't deserialize. undefined method `[]=' for nil:NilClass

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#26215]
_From @Frexuz on August 18, 2016 17:15_

(I hope this is the right repo for this issue)
Can't seem to read a serialized column after upgrading to Rails 5.0 stable.

I haven't used a specific serialization class, I assume YAML is the default? (Thought, before the upgrade, the values were saved as `!ruby/hash:ActionController::Parameters`)
```
class PaymentNotification < ActiveRecord::Base
  serialize :raw_IPN
  ...
end
```

Value in the serialized database column:
```
--- !ruby/hash:ActionController::Parameters
address_status: confirmed
subscr_date: 12:42:39 Dec 20, 2015 PST
payer_id: 123
address_street: 1 Main St
mc_amount1: '6.00'
mc_amount3: '12.00'
charset: windows-1252
address_zip: '123'
first_name: Test
reattempt: '1'
address_country_code: US
address_name: Test Buyer
notify_version: '3.8'
subscr_id: I-123123123
custom: '2'
payer_status: verified
business: payments-facilitator@test.com
address_country: United States
address_city: San Jose
verify_sign: 123-12312312321312.2JohI99Xp56cvu9zc
payer_email: payments-buyer@test.com
btn_id: '123'
last_name: Buyer
address_state: CA
receiver_email: test@email.com
recurring: '1'
txn_type: subscr_signup
item_name: asd
mc_currency: EUR
item_number: asd
residence_country: US
test_ipn: '1'
period1: 12 M
period3: 12 M
ipn_track_id: 111
controller: payment_notifications
action: create
```

Getting this error when it tries to deserialize it (Just by doing `PaymentNotification.first` for example)
```
NoMethodError - undefined method `[]=' for nil:NilClass:
  actionpack (5.0.0) lib/action_controller/metal/strong_parameters.rb:414:in `[]='
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:362:in `block in revive_hash'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:281:in `visit_Psych_Nodes_Mapping'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych/nodes/node.rb:38:in `to_ruby'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/psych.rb:253:in `load'
  activerecord (5.0.0) lib/active_record/coders/yaml_column.rb:24:in `load'
  activerecord (5.0.0) lib/active_record/type/serialized.rb:18:in `deserialize'
  activerecord (5.0.0) lib/active_record/attribute.rb:140:in `type_cast'
  activerecord (5.0.0) lib/active_record/attribute.rb:38:in `value'
  activerecord (5.0.0) lib/active_record/attribute_set.rb:42:in `fetch_value'
  activerecord (5.0.0) lib/active_record/attribute_methods/read.rb:66:in `_read_attribute'
  activerecord (5.0.0) lib/active_record/attribute_methods/read.rb:36:in `__temp__271677f59405e4'
  app/admin/payment_notifications.rb:17:in `block (3 levels) in <top (required)>'
```

_Copied from original issue: rails/strong_parameters#241_

**Comment by rafaelfranca** [comment]
Could you try the 5-0-stable branch?

**Comment by Frexuz** [comment]
```
# gem 'rails', '5.0.0'
gem 'rails', github: "rails/rails", branch: '5-0-stable'
```
Is this correct?
After running `bundle` it still fails. 

I looked up the commit; https://github.com/rails/rails/commit/bd1e437ef90f87af3de7841e80316f9f0aa616ca
and tried to see if I had it, running `bundle open rails` and opening **strong_parameters.rb**. I don't see the commit's changes in this file. What am I doing wrong? :)

Gemfile.lock:
```
GIT
  remote: git://github.com/rails/rails.git
  revision: 1a7618a22d1728caed7e52f46daaac3e25a6a667
  branch: 5-0-stable
  specs:
    rails (5.0.0.1)
      actioncable (= 5.0.0.1)
      actionmailer (= 5.0.0.1)
      actionpack (= 5.0.0.1)
      actionview (= 5.0.0.1)
      activejob (= 5.0.0.1)
      activemodel (= 5.0.0.1)
      activerecord (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.0.1)
      sprockets-rails (>= 2.0.0)
```

**Comment by rafaelfranca** [comment]
Yes, this is correct. I believe this may be a bundler bug. It is using `rails` gem from git source but activerecord from the actual gem when it should be using from git. Try to run `bundle update rails`.

**Comment by Frexuz** [comment]
That did something.. Seems I have the changes now, but I get another error:

`output error: #<ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Hash, but was a ActionController::Parameters.`

**Comment by rafaelfranca** [comment]
Could you post the full backtrace?

**Comment by Frexuz** [comment]
```
ActiveRecord::SerializationTypeMismatch - Attribute was supposed to be a Hash, but was a ActionController::Parameters. -- <ActionController::Parameters {"address_status"=>"confirmed", "subscr_date"=>"12:42:39 Dec 20, 2015 PST", "payer_id"=>"ACHUSN2DG3YGY", "address_street"=>"1 Main St", "mc_amount1"=>"6.00", "mc_amount3"=>"12.00", "charset"=>"windows-1252", "address_zip"=>"95131", "first_name"=>"Test", "reattempt"=>"1", "address_country_code"=>"US", "address_name"=>"Test Buyer", "notify_version"=>"3.8", "subscr_id"=>"I-4P3CR262F6YJ", "custom"=>"2", "payer_status"=>"verified", "business"=>"payments-facilitator@episodecalendar.com", "address_country"=>"United States", "address_city"=>"San Jose", "verify_sign"=>"AcJvWJJJljP-n4Ko13sGCx2EhgPtASzxEqnLcO.2JohI99Xp56cvu9zc", "payer_email"=>"payments-buyer@episodecalendar.com", "btn_id"=>"3252770", "last_name"=>"Buyer", "address_state"=>"CA", "receiver_email"=>"payments-facilitator@episodecalendar.com", "recurring"=>"1", "txn_type"=>"subscr_signup", "item_name"=>"Premium - Xmas offer - 12 months", "mc_currency"=>"EUR", "item_number"=>"premium-xmas-test", "residence_country"=>"US", "test_ipn"=>"1", "period1"=>"12 M", "period3"=>"12 M", "ipn_track_id"=>"608bbf168c43f", "controller"=>"payment_notifications", "action"=>"create"} permitted: false>:
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/coders/yaml_column.rb:34:in `assert_valid_value'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/coders/yaml_column.rb:26:in `load'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/type/serialized.rb:18:in `deserialize'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/attribute.rb:140:in `type_cast'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/attribute.rb:38:in `value'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/attribute_set.rb:44:in `fetch_value'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/attribute_methods/read.rb:66:in `_read_attribute'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/attribute_methods/read.rb:36:in `__temp__271677f59405e4'
  app/admin/payment_notifications.rb:17:in `block (3 levels) in <top (required)>'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/view_helpers/display_helper.rb:57:in `find_value'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/view_helpers/display_helper.rb:44:in `format_attribute'
  arbre (1.1.1) lib/arbre/element.rb:180:in `method_missing'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/components/table_for.rb:101:in `block in build_table_cell'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `td'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/components/table_for.rb:100:in `build_table_cell'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/components/table_for.rb:44:in `block (2 levels) in column'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/components/table_for.rb:43:in `block in column'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/relation/delegation.rb:38:in `each'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/components/table_for.rb:42:in `column'
  arbre (1.1.1) lib/arbre/element.rb:176:in `method_missing'
  app/admin/payment_notifications.rb:15:in `block (2 levels) in <top (required)>'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/index_as_table.rb:224:in `block in build'
  arbre (1.1.1) lib/arbre/element.rb:32:in `build'
  arbre (1.1.1) lib/arbre/html/tag.rb:19:in `build'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/components/table_for.rb:20:in `build'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/index_as_table.rb:229:in `table_for'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/index_as_table.rb:222:in `build'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/index.rb:139:in `block (2 levels) in render_index'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/index.rb:138:in `block in render_index'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `paginated_collection'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/index.rb:132:in `render_index'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/index.rb:50:in `build_collection'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/index.rb:28:in `block in main_content'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/index.rb:38:in `wrap_with_batch_action_form'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/index.rb:26:in `main_content'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:91:in `block (2 levels) in build_main_content_wrapper'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:90:in `block in build_main_content_wrapper'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:89:in `build_main_content_wrapper'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:75:in `block in build_page_content'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:74:in `build_page_content'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:52:in `block (2 levels) in build_page'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:48:in `block in build_page'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:47:in `build_page'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/views/pages/base.rb:10:in `build'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/app/views/active_admin/resource/index.html.arb:2:in `block in __home_frexuz__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin_cc___ad_ebe__app_views_active_admin_resource_index_html_arb___3141590133720464771_70153825833180'
  arbre (1.1.1) lib/arbre/context.rb:45:in `initialize'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/app/views/active_admin/resource/index.html.arb:1:in `__home_frexuz__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin_cc___ad_ebe__app_views_active_admin_resource_index_html_arb___3141590133720464771_70153825833180'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/template.rb:158:in `block in render'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/notifications.rb:166:in `instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/template.rb:348:in `instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/template.rb:156:in `render'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/notifications.rb:164:in `instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/template_renderer.rb:14:in `render'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/renderer.rb:42:in `render_template'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/renderer/renderer.rb:23:in `render'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/rendering.rb:103:in `_render_template'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/streaming.rb:217:in `_render_template'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/rendering.rb:83:in `render_to_body'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/renderers.rb:144:in `render_to_body'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/abstract_controller/rendering.rb:26:in `render'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/rendering.rb:36:in `render'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/frexuz/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/core_ext/benchmark.rb:12:in `ms'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/instrumentation.rb:43:in `render'
  responders (2.3.0) lib/action_controller/responder.rb:238:in `default_render'
  responders (2.3.0) lib/action_controller/responder.rb:170:in `to_html'
  responders (2.3.0) lib/responders/flash_responder.rb:107:in `to_html'
  responders (2.3.0) lib/action_controller/responder.rb:163:in `respond'
  responders (2.3.0) lib/action_controller/responder.rb:156:in `call'
  responders (2.3.0) lib/action_controller/respond_with.rb:205:in `respond_with'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/inherited_resources-ba9467db4817/lib/inherited_resources/actions.rb:7:in `index'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-cc178ad0ebe1/lib/active_admin/resource_controller/streaming.rb:12:in `index'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/abstract_controller/base.rb:188:in `process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/rendering.rb:30:in `process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:126:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:455:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  route_translator (5.0.2) lib/route_translator/extensions/action_controller.rb:27:in `set_locale_from_url'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:382:in `block in make_lambda'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:285:in `block in halting'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:447:in `block in around'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:455:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/rescue.rb:20:in `process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/notifications.rb:164:in `instrument'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/abstract_controller/base.rb:126:in `process'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionview/lib/action_view/rendering.rb:30:in `process'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal.rb:190:in `dispatch'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_controller/metal.rb:262:in `dispatch'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/routing/route_set.rb:32:in `serve'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/journey/router.rb:39:in `block in serve'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/journey/router.rb:26:in `serve'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/routing/route_set.rb:725:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  bullet (5.3.0) lib/bullet/rack.rb:12:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/cookies.rb:613:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activerecord/lib/active_record/migration.rb:552:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/callbacks.rb:90:in `run_callbacks'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/executor.rb:12:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/railties/lib/rails/rack/logger.rb:36:in `call_app'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/railties/lib/rails/rack/logger.rb:24:in `block in call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/tagged_logging.rb:70:in `block in tagged'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/tagged_logging.rb:26:in `tagged'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/tagged_logging.rb:70:in `tagged'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/railties/lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.1.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/executor.rb:12:in `call'
  rack-livereload (0.3.16) lib/rack/livereload.rb:23:in `_call'
  rack-livereload (0.3.16) lib/rack/livereload.rb:14:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/actionpack/lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
   () home/frexuz/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-09d313acd57d/railties/lib/rails/engine.rb:522:in `call'
  puma (3.6.0) lib/puma/configuration.rb:225:in `call'
  puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
  puma (3.6.0) lib/puma/server.rb:415:in `process_client'
  puma (3.6.0) lib/puma/server.rb:275:in `block in run'
  puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

And full Gemfile.lock if needed:
```
GIT
  remote: git://github.com/activeadmin/activeadmin.git
  revision: cc178ad0ebe1b74729eeaa59d5c7ad9b82ed7837
  specs:
    activeadmin (1.0.0.pre4)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails
      kaminari (~> 0.15)
      railties (>= 3.2, < 5.1)
      ransack (~> 1.3)
      sass-rails
      sprockets (< 4.1)

GIT
  remote: git://github.com/activeadmin/inherited_resources.git
  revision: ba9467db4817944591df35dfe340f4c05a948033
  specs:
    inherited_resources (1.6.0)
      actionpack (>= 3.2, < 5.1)
      has_scope (~> 0.6)
      railties (>= 3.2, < 5.1)
      responders

GIT
  remote: git://github.com/amatsuda/kaminari.git
  revision: abbf93d557208ee1d0b612c612cd079f86ed54f4
  branch: 0-17-stable
  specs:
    kaminari (0.17.0)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)

GIT
  remote: git://github.com/contentful/contentful_model.git
  revision: 64952845250c6378517b79ddc8c6357734cc64e7
  branch: master
  specs:
    contentful_model (0.1.7.1)
      activesupport
      contentful (~> 0.9)
      contentful-management (~> 1.0)
      redcarpet
      require_all

GIT
  remote: git://github.com/ctran/annotate_models.git
  revision: c952306966c9bae4438e4d40351561af3d8005c0
  specs:
    annotate (2.7.0)
      activerecord (>= 3.2, < 6.0)
      rake (>= 10.4, < 12.0)

GIT
  remote: git://github.com/rails/rails.git
  revision: 09d313acd57dfb72057e0656881487e7333bb393
  branch: 5-0-stable
  specs:
    actioncable (5.0.0.1)
      actionpack (= 5.0.0.1)
      nio4r (~> 1.2)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.0.1)
      actionpack (= 5.0.0.1)
      actionview (= 5.0.0.1)
      activejob (= 5.0.0.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.0.1)
      actionview (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.0.1)
      activesupport (= 5.0.0.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (5.0.0.1)
      activesupport (= 5.0.0.1)
      globalid (>= 0.3.6)
    activemodel (5.0.0.1)
      activesupport (= 5.0.0.1)
    activerecord (5.0.0.1)
      activemodel (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      arel (~> 7.0)
    activesupport (5.0.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    rails (5.0.0.1)
      actioncable (= 5.0.0.1)
      actionmailer (= 5.0.0.1)
      actionpack (= 5.0.0.1)
      actionview (= 5.0.0.1)
      activejob (= 5.0.0.1)
      activemodel (= 5.0.0.1)
      activerecord (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.0.1)
      sprockets-rails (>= 2.0.0)
    railties (5.0.0.1)
      actionpack (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)

GIT
  remote: git://github.com/sinatra/rack-protection.git
  revision: 7e723a74763bb83989d1249cdceb9cceb2ee6f01
  specs:
    rack-protection (2.0.0)
      rack

GIT
  remote: git://github.com/sinatra/sinatra.git
  revision: 6b5a0ef3a4598366138fefe3f2b696ddeb371f3c
  specs:
    sinatra (2.0.0.pre.alpha)
      mustermann (~> 0.4)
      rack (~> 2.0)
      rack-protection (~> 2.0)
      tilt (~> 2.0)

GIT
  remote: https://github.com/rails/rails-observers.git
  revision: 3fe157d6cbb5b5e767ded248009fc59443d63fa1
  specs:
    rails-observers (0.1.3.alpha)
      activemodel (>= 4.0, < 5.1)

GEM
  remote: http://rubygems.org/
  specs:
    addressable (2.4.0)
    amistad (0.10.2)
    arbre (1.1.1)
      activesupport (>= 3.0.0)
    arel (7.1.1)
    ast (2.3.0)
    awesome_print (1.7.0)
    bcrypt (3.1.11)
    best_in_place (3.1.0)
      actionpack (>= 3.2)
      railties (>= 3.2)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bourbon (4.2.7)
      sass (~> 3.4)
      thor (~> 0.19)
    brakeman (3.3.5)
    builder (3.2.2)
    bullet (5.3.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.10.0)
    byebug (9.0.5)
    callsite (0.0.11)
    cancancan (1.15.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.1)
    coffee-rails (4.2.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.2.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    concurrent-ruby (1.0.2)
    connection_pool (2.2.0)
    contentful (0.12.0)
      http (~> 1.0)
      json (~> 1.8)
      multi_json (~> 1)
    contentful-management (1.2.0)
      http (~> 1.0)
      json (~> 1.8)
      multi_json (~> 1)
    curb (0.9.3)
    dalli (2.7.6)
    database_cleaner (1.5.3)
    debug_inspector (0.0.2)
    devise (4.2.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.1)
      responders
      warden (~> 1.2.3)
    devise-encryptable (0.2.0)
      devise (>= 2.1.0)
    diff-lcs (1.2.5)
    docile (1.1.5)
    domain_name (0.5.20160615)
      unf (>= 0.0.5, < 1.0.0)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.0.1)
    execjs (2.7.0)
    factory_girl (4.7.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.7.0)
      factory_girl (~> 4.7.0)
      railties (>= 3.0.0)
    faker (1.6.6)
      i18n (~> 0.5)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.14)
    formatador (0.2.5)
    formtastic (3.1.4)
      actionpack (>= 3.2.13)
    formtastic_i18n (0.6.0)
    gem-shut-the-fuck-up (1.0.0)
    global (0.1.2)
      activesupport (>= 2.0)
    globalid (0.3.7)
      activesupport (>= 4.1.0)
    guard (2.14.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-annotate (2.3)
      annotate (~> 2.4, >= 2.4.0)
      guard-compat (~> 1.2, >= 1.2.1)
    guard-brakeman (0.8.3)
      brakeman (>= 2.1.1)
      guard (>= 2.0.0)
    guard-bundler (2.1.0)
      bundler (~> 1.0)
      guard (~> 2.2)
      guard-compat (~> 1.1)
    guard-compat (1.2.1)
    guard-jshintrb (1.1.1)
      guard (~> 2.0)
      jshintrb
    guard-livereload (2.5.2)
      em-websocket (~> 0.5)
      guard (~> 2.8)
      guard-compat (~> 1.0)
      multi_json (~> 1.8)
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    guard-rubocop (1.2.0)
      guard (~> 2.0)
      rubocop (~> 0.20)
    guard-scss-lint (0.0.1alpha)
      guard (~> 2.0)
      scss-lint (~> 0.30.0)
    has_permalink (0.1.7)
    has_scope (0.7.0)
      actionpack (>= 4.1, < 5.1)
      activesupport (>= 4.1, < 5.1)
    hashie (3.4.4)
    hiredis (0.6.1)
    htmlentities (4.3.4)
    http (1.0.4)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 1.0.1)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    http-form_data (1.0.1)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    icalendar (2.4.0)
    jquery-rails (4.1.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    jshint-rb (1.1.1)
      execjs (>= 1.3.2)
      multi_json (>= 1.3.5)
    jshintrb (0.3.0)
      execjs
      multi_json (>= 1.3)
      rake
    json (1.8.3)
    jwt (1.5.4)
    kgio (2.10.0)
    libv8 (5.0.71.48.3)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.10)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    meta_request (0.4.0)
      callsite (~> 0.0, >= 0.0.11)
      rack-contrib (~> 1.1)
      railties (>= 3.0.0, < 5.1.0)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.2)
    mini_portile2 (2.1.0)
    mini_racer (0.1.4)
      libv8 (~> 5.0, < 5.1.11)
    minitest (5.9.0)
    multi_json (1.12.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    mustermann (0.4.0)
      tool (~> 0.2)
    mysql2 (0.4.4)
    nenv (0.3.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (3.2.0)
    nio4r (1.2.1)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oauth (0.5.1)
    oauth2 (1.2.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.3.1)
      hashie (>= 1.2, < 4)
      rack (>= 1.0, < 3)
    omniauth-facebook (4.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-oauth (1.1.0)
      oauth
      omniauth (~> 1.0)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    omniauth-twitter (1.2.1)
      json (~> 1.3)
      omniauth-oauth (~> 1.1)
    orm_adapter (0.5.0)
    paper_trail (5.2.0)
      activerecord (>= 3.0, < 6.0)
      activesupport (>= 3.0, < 6.0)
      request_store (~> 1.1)
    paperclip (5.0.0)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (~> 0.3.0)
    parser (2.3.1.2)
      ast (~> 2.2)
    pkg-config (1.1.7)
    polyamorous (1.3.1)
      activerecord (>= 3.0)
    powerpack (0.1.1)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    puma (3.6.0)
    rack (2.0.1)
    rack-contrib (1.2.0)
      rack (>= 0.9.1)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails-controller-testing (1.0.1)
      actionpack (~> 5.x)
      actionview (~> 5.x)
      activesupport (~> 5.x)
    rails-dom-testing (2.0.1)
      activesupport (>= 4.2.0, < 6.0)
      nokogiri (~> 1.6.0)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rainbow (2.1.0)
    raindrops (0.17.0)
    rake (11.2.2)
    ransack (1.8.2)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.3)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    redcarpet (3.3.4)
    redis (3.3.1)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    request_store (1.3.1)
    require_all (1.3.3)
    responders (2.3.0)
      railties (>= 4.2.0, < 5.1)
    rmagick (2.16.0)
    route_translator (5.0.2)
      actionpack (>= 5.0.0, < 5.1)
      activesupport (>= 5.0.0, < 5.1)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.2)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-rails (3.5.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    rubocop (0.42.0)
      parser (>= 2.3.1.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.8.1)
    ruby_dep (1.4.0)
    rufus-scheduler (3.2.2)
    rusage (0.2.0)
    sass (3.4.22)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sassc (1.10.0)
      bundler
      ffi (~> 1.9.6)
      sass (>= 3.3.0)
    sassc-rails (1.3.0)
      railties (>= 4.0.0)
      sass
      sassc (~> 1.9)
      sprockets (> 2.11)
      sprockets-rails
      tilt
    scout_apm (2.1.0)
      rusage (~> 0.2.0)
    scss-lint (0.30.0)
      rainbow (~> 2.0)
      sass (~> 3.4.0)
    scss_lint (0.49.0)
      rake (>= 0.9, < 12)
      sass (~> 3.4.20)
    sentry-raven (1.2.2)
      faraday (>= 0.7.6, < 0.10.x)
    shellany (0.0.1)
    shoulda-matchers (3.1.1)
      activesupport (>= 4.0.0)
    sidekiq (4.1.4)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      redis (~> 3.2, >= 3.2.1)
      sinatra (>= 1.4.7)
    sidekiq-cron (0.4.2)
      redis-namespace (>= 1.5.2)
      rufus-scheduler (>= 2.0.24)
      sidekiq (>= 4.0.0)
    sidekiq-statistic (1.2.0)
      sidekiq (>= 3.3.4, < 5)
    sidekiq-unique-jobs (4.0.18)
      sidekiq (>= 2.6)
      thor
    simple-random (1.0.3)
    simplecov (0.12.0)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.0)
    skylight (0.10.6)
      activesupport (>= 3.0.0)
    slim (3.0.7)
      temple (~> 0.7.6)
      tilt (>= 1.3.3, < 2.1)
    slop (3.6.0)
    split (2.1.0)
      redis (>= 2.1)
      redis-namespace (>= 1.1.0)
      simple-random (>= 0.9.3)
      sinatra (>= 1.2.6)
    spring (1.7.2)
    spring-watcher-listen (2.0.0)
      listen (>= 2.7, < 4.0)
      spring (~> 1.2)
    sprite-factory (1.7.1)
    sprockets (3.7.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.1.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    susy (2.2.12)
      sass (>= 3.3.0, < 3.5)
    synvert (0.9.0)
      synvert-core (>= 0.5.3)
    synvert-core (0.11.1)
      activesupport
      erubis
      parser (= 2.3.1.2)
    temple (0.7.7)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.5)
    time_diff (0.3.0)
      activesupport
      i18n
    tool (0.2.3)
    trumbowyg_rails (2.1.0.3)
      rails (>= 3.1)
      railties (>= 3.1)
      sass (>= 3.2)
    tunemygc (1.0.68)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.1)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.2)
    unicode-display_width (1.1.0)
    unicorn (5.1.0)
      kgio (~> 2.6)
      raindrops (~> 0.7)
    uniform_notifier (1.10.0)
    warden (1.2.6)
      rack (>= 1.0)
    websocket-driver (0.6.4)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)

PLATFORMS
  ruby

DEPENDENCIES
  activeadmin!
  amistad
  annotate!
  awesome_print
  best_in_place
  better_errors
  binding_of_caller
  brakeman
  bullet
  byebug
  cancancan (~> 1.7)
  contentful_model!
  curb
  dalli
  database_cleaner
  devise
  devise-encryptable
  factory_girl_rails
  faker
  gem-shut-the-fuck-up
  global
  guard
  guard-annotate
  guard-brakeman
  guard-bundler
  guard-jshintrb
  guard-livereload (~> 2.4)
  guard-rspec
  guard-rubocop
  guard-scss-lint
  has_permalink
  hiredis
  htmlentities
  icalendar
  inherited_resources!
  jquery-rails
  jshint-rb
  kaminari!
  meta_request
  mini_racer
  mysql2
  net-scp
  net-ssh
  nokogiri
  omniauth-facebook
  omniauth-twitter
  paper_trail
  paperclip
  pry-rails
  puma
  rack-livereload
  rack-protection!
  rails!
  rails-controller-testing
  rails-observers!
  ransack
  redcarpet
  redis
  redis-namespace
  rmagick
  route_translator
  rspec-rails (~> 3.0)
  rubocop
  sassc-rails
  scout_apm
  scss_lint
  sentry-raven (>= 0.12.0)
  shoulda-matchers
  sidekiq (< 5)
  sidekiq-cron (~> 0.4.0)
  sidekiq-statistic
  sidekiq-unique-jobs
  simplecov
  sinatra!
  skylight
  slim (>= 1.1.0)
  split
  spring
  spring-watcher-listen
  sprite-factory
  susy
  synvert
  time_diff
  trumbowyg_rails
  tunemygc
  turbolinks (~> 5.0.0)
  uglifier (>= 1.3.0)
  unicorn
  warden

BUNDLED WITH
   1.12.5
```

Ruby 2.3.1

**Comment by rafaelfranca** [comment]
And how is defined the `serialize` or `store` call?

**Comment by Frexuz** [comment]
I had left Hash in there for testing purposes (`serialize :raw_IPN, Hash`)

Reverting it back to just `serialize :raw_IPN` works!

Sorry about that! :) 

So I'll just keep `gem 'rails', github: "rails/rails", branch: '5-0-stable'` until the next gem release?

**Comment by rafaelfranca** [comment]
> So I'll just keep gem 'rails', github: "rails/rails", branch: '5-0-stable' until the next gem release?

Yes. Glad it is fixed already. Thank you for reporting.

**Comment by zyxan** [comment]
I just came across this error updating my app to rails 5, but running `bundle update rails` didn't change the situation. Using the latest rails gem (5.0.0.1), still can't deserialize, having `ActionView::Template::Error (undefined method `[]=' for nil:NilClass)` when attempting to access the serialized attributes.

I have this in my Gemfile.lock

    rails (5.0.0.1)
      actioncable (= 5.0.0.1)
      actionmailer (= 5.0.0.1)
      actionpack (= 5.0.0.1)
      actionview (= 5.0.0.1)
      activejob (= 5.0.0.1)
      activemodel (= 5.0.0.1)
      activerecord (= 5.0.0.1)
      activesupport (= 5.0.0.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.0.0.1)
      sprockets-rails (>= 2.0.0)

with ruby 2.3.1

**Comment by rafaelfranca** [comment]
@zyxan use 5-0-stable. The fix IS NOT RELEASED YET.
