### ISSUE TITLE
Preload association ignores left_join in association scope.

### ISSUE THREAD

**Issue by Mik-die** [rails/rails#28261]
### Steps to reproduce

I have a test case:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
  end

  create_table :posts, force: true do |t|
    t.integer :author_id
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Author < ActiveRecord::Base
  has_many :posts, -> { left_joins(:comments).where('comments.id > 10') }
end

class Post < ActiveRecord::Base
  belongs_to :author
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_left_joins_in_association_scope
    Author.create
    assert Author.preload(:posts).to_a
  end
end
```

### Expected behavior
I expect it respects `left_joins` in association scope when do `preload` and include `LEFT OUTER JOIN` in preload sql. 

### Actual behavior
It ignores `left_joins` and raises exception:

```
no such column: comments.id: SELECT "posts".* FROM "posts" WHERE (comments.id > 10) AND "posts"."author_id" = 1
```

### System configuration
**Rails version**:
5.0.0

**Ruby version**:
2.3.1p112

**Comment by meinac** [comment]
Hi @Mik-die, can you please verify that the test case passes with following gem configurations;
```ruby
gemfile(true) do
  source "https://rubygems.org"
  gem 'rails', github: 'meinac/rails', branch: 'fix_assoc_scopes_with_left_outer_joins'
  gem 'arel', github: 'rails/arel'
  gem 'sqlite3'
end
```

With this configuration the test case will run against my patch of Rails which is checked out from #27860 therefore to fix this on Rails at first we need to merge it and I'm waiting for a response since 31th of January.

@rafaelfranca I know you are too busy but can you have a look at this please.

**Comment by Mik-die** [comment]
Hey @meinac, it looks like the issue is fixed in your branch, my test have passed. Thank you.

**Comment by kamipo** [comment]
This should be fixed by #29413.

**Comment by Mik-die** [comment]
I just run this test against master, it's fixed, thank you!

**Comment by rohpai** [comment]
I'm using Rails 5.0.6 with a mysql DB and I still see this issue. Can someone confirm if this is working as expected?

**Comment by kamipo** [comment]
I also faced the problem. I've backported in ed6a0ff9cd27863e8e32332998d800907f93a1f6 and 1f87800d6a3f927597bea9a87895f1d2c0012398.
