### ISSUE TITLE
Rails Server Will Not Allow Custom Port Number to Run Defaults to 3000

### ISSUE THREAD

**Issue by shakycode** [rails/rails#28384]
### Steps to reproduce

````
shakycodes-MacBook-Pro:app shakycode$ rails s -p 9002
/Users/shakycode/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/shakycode/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:9002
=> Run `rails server -h` for more startup options
/Users/shakycode/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
Puma starting in single mode...
* Version 3.7.0 (ruby 2.4.0-p0), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
````

### Expected behavior
Expect when passing `-p 9002` that Puma/local app server will listen on specified port

### Actual behavior
Puma does not listen on 9002 instead defaults to 3000.

### System configuration
**Rails 5.0.1**

**Ruby ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]**

**Comment by shakycode** [comment]
In `puma.rb` this will set the default port `port        ENV.fetch("PORT") { 3000 }` so I can change it in there to 9002, but even when passing the `-p 9002` to the `rails s` command I should be able to override.  This apparently started with Puma.  Is this worth a PR or should docs be more explicit as per Puma usage.

It seems to me that running `rails s -p 9002` should spinup Puma on 9002.

**Comment by maclover7** [comment]
I believe bumping your Puma version should fix the issue. Related discussion at #27837 and #28055.

**Comment by shakycode** [comment]
@maclover7 Thanks so much for pointing that out.  I bumped to `3.7.1` and can now pass the `-p 9002` no problem.  I'll leave this open if you think it warrants it, but appreciate the help!

**Comment by maclover7** [comment]
Will close this out since the issue is fixed. Thanks for opening and reporting!

**Comment by bakku** [comment]
After just upgrading to Rails 5.1.0.rc1 I noticed that when specifying the port like this:

`rails s -p3005`

the issue still exists. 

Puma will then ignore the specified port and choose `3000`. 

`rails s -p 3005` 

however works as expected. Certainly not a blocker but it was working in Rails 5.1.0.beta1
