### ISSUE TITLE
includes(:association) is not respecting scope when eager loaded using .references()

### ISSUE THREAD

**Issue by jeffblake** [rails/rails#28415]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
Tell us what should happen

comment.post should be present, even if the post is soft deleted

### Actual behavior
Tell us what happens instead

comment.post is nil

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.4

Reference: https://github.com/rails/rails/pull/21550

bug.rb

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
    t.datetime :deleted_at
  end

  create_table :comments, force: true do |t|
    t.integer :post_id

  end
end

class Post < ActiveRecord::Base
  has_many :comments

  scope :with_deleted, -> { unscope(where: :deleted_at) }

  default_scope { where deleted_at: nil }
end

class Comment < ActiveRecord::Base
  belongs_to :post, -> { with_deleted }
end

class BugTest < Minitest::Test

  def setup!
    post = Post.create!(name: 'test')

    post.comments << Comment.create!

    post.touch :deleted_at

  end

  # this should pass
  def test_association_with_references
    setup!

    comments = Comment.includes(:post).references(:posts)
    refute_nil comments.first.post
  end

  def test_association_without_references
    setup!

    comments = Comment.includes(:post)
    refute_nil comments.first.post
  end

  def test_association_without_preloading
    setup!

    comments = Comment.all
    refute_nil comments.first.post
  end

end
```

**Comment by kamipo** [comment]
https://github.com/rails/rails/pull/29154/commits/e315eaf7eebf8ff303540ebb803647b7187096d4 in #29154 will fix the issue.

**Comment by kamipo** [comment]
This should be fixed by c9cf8b8dd4b968e21768f495d6ed0861a6efe08c.

**Comment by okuramasafumi** [comment]
@kamipo I run `bug.rb` above against Rails 5.1.3 and Ruby 2.4.1 and it still fails.

**Comment by kamipo** [comment]
Backported in ad80256de48366d4de15d5a6d039bda8464ddcda.

**Comment by feliara8** [comment]
im still having this issue in 5.1.4
