### ISSUE TITLE
Number with get method returning String failed to validate numerically

### ISSUE THREAD

**Issue by repinel** [rails/rails#29024]
I wonder if this was ever to suppose to be valid, but used to be in Rails 4. If so, #19851 caused the regression (sorry :cold_sweat:).

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  # uncomment this to run with activerecord-4.2.8
  # gem "activerecord", "4.2.8"

  # comment this to run with activerecord-4.2.8
  gem "rails", github: "rails/rails"
  gem "arel", github: "rails/arel"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :items, force: true do |t|
    t.integer "number"
  end
end

class Item < ActiveRecord::Base
  validates :number, numericality: { greater_than_or_equal_to: 0 }

  def number
    super.to_s.rjust(4, "0")
  end
end

class BugTest < Minitest::Test
  def test_leading_zeros_and_validation
    item = Item.new number: 2
    assert item.save
    assert_equal "0002", item.number
  end
end
```

It returns using `ruby-2.3.0`:
```
BugTest#test_leading_zeros_and_validation:
ArgumentError: comparison of String with 0 failed
    activemodel/lib/active_model/validations/numericality.rb:57:in `>='
    activemodel/lib/active_model/validations/numericality.rb:57:in `block in validate_each'
    active_model/validations/numericality.rb:43:in `each'
    active_model/validations/numericality.rb:43:in `validate_each'
```

**Comment by pixeltrix** [comment]
@repinel isn't this the same as #22744 which you commented on and was fixed in #22760 ? Is it that it wasn't backported to 4-2-stable ?

**Comment by repinel** [comment]
@pixeltrix it seems different because `Item#number` would normally return the integer and it was overridden to return a string. So the attribute and `Item#number` don't match.

I'm still not sure if overridden that method to return a different type should be ok in this case.

**Comment by pixeltrix** [comment]
Yeah, it looks like this condition:

``` ruby
unless raw_value.is_a?(Numeric)
  value = parse_raw_value_as_a_number(raw_value)
end
```

causes a weird edge condition where the typecast value is used for the comparison. If you did:

``` ruby
item = Item.new number: '2'
```

then the test should pass because it will parse and use the value from before the typecast.

I wonder whether changing the conditional to the following helps:

``` ruby
if raw_value.is_a?(Numeric)
  value = raw_value
else
  value = parse_raw_value_as_a_number(raw_value)
end
```

Also I wonder whether creating the schema with a string column and passing a numeric to `initialize` without the overridden accessor would also trigger the error.

**Comment by repinel** [comment]
> I wonder whether changing the conditional to the following helps

Yes, the test case passes.

> Also I wonder whether creating the schema with a string column and passing a numeric to initialize without the overridden accessor would also trigger the error.

Also yes, it cast the attribute properly.

**Comment by matthewd** [comment]
@repinel #29249 has made @pixeltrix's suggested change; does that mean this is now fixed?

**Comment by repinel** [comment]
@matthewd Yes, it has been fixed . Thanks! 😁
