### ISSUE TITLE
Rails UJS docs missing?

### ISSUE THREAD

**Issue by sambostock** [rails/rails#30031]
### Steps to reproduce

1. Visit [remote elements](http://guides.rubyonrails.org/working_with_javascript_in_rails.html#remote-elements) section of the official guides.
2. Click the link to rails-ujs:

> Unless you have disabled the Asset Pipeline, [rails-ujs](https://github.com/rails/rails-ujs/blob/master/src/rails-ujs.coffee) provides the JavaScript half, and the regular Ruby view helpers add appropriate tags to your DOM.

3. > **404** This is not the page you are looking for

### Expected behavior
There should be docs for `rails-ujs`, especially setup.

### Actual behavior
`404` No docs found

### System configuration
Not applicable.

**Comment by guilleiguaran** [comment]
I've updated the docs but we need to wait to get the guides re-generated to see it in http://guides.rubyonrails.org

**Comment by sambostock** [comment]
Just had a look at your [commit](https://github.com/rails/rails/commit/e31a1629d4b6a82e334735ff4a78016db24f32f5), and the URL still doesn't work.

https://github.com/rails/rails-ujs `404`s entirely 😢

**Comment by guilleiguaran** [comment]
Sorry, it should be fixed now!!!

**Comment by sambostock** [comment]
Nice! I take it the guides are regenerated when the version is bumped?

**Comment by guilleiguaran** [comment]
Exactly, let's close this for now and re-open if still happening after of the release of next version.

**Comment by dobrynin** [comment]
Seems to no longer work 😢

**Comment by sambostock** [comment]
@dobrynin I'm unable to reproduce the error. Can you provide a link to the guides which link to the 404? Perhaps it's an old version of the guides?

**Comment by dobrynin** [comment]
Hm. I was getting a 404 before but I can't replicate it now either. Oh well, seems to be working now!

**Comment by shime** [comment]
For reference, the documentation for Rails UJS (unobtrusive JavaScript) is located here: https://guides.rubyonrails.org/working_with_javascript_in_rails.html#unobtrusive-javascript
