### ISSUE TITLE
ActiveStorage (javascript) dispatchEvent not working in Firefox

### ISSUE THREAD

**Issue by DLawla** [rails/rails#31393]
We are running into an issue where the ActiveStorage javascript window events (for example, 'direct-upload:initialize') are not being picked up by event listeners in Firefox, but are being picked up in Chrome and Safari.

For example, we use the following code to initialize some direct upload progress indicators:

```
addEventListener('direct-upload:initialize', event => {
  const { target, detail } = event;
  const { id, file } = detail;
  const filename = limit(file.name);
  target.parentNode.insertAdjacentHTML('afterend', `
    <div id="direct-upload-${id}" class="direct-upload direct-upload--pending">
      <div id="direct-upload-progress-${id}" class="direct-upload__progress" style="width: 0%"></div>
      <span class="direct-upload__filename">${filename}</span>
    </div>
  `);
});
```

This code does not get run on Firefox, but works happily in Chrome/Safari.

I can confirm the following from my debugging:
- The event listeners are being attached to `window` correctly in Firefox:
![image](https://user-images.githubusercontent.com/12427222/33816959-807fc030-dea1-11e7-9f1a-fb522f455a4e.png)

- I can manually, via the browser console, trigger any one of those events in Firefox:
```
var event = document.createEvent("Event")
event.initEvent('direct-upload:start', true, true)
document.getElementById('upload-field-id').dispatchEvent(event)
#-> will trigger the event
```

This recent ActiveStorage & Firefox issue https://github.com/rails/rails/pull/30568 got me thinking -- is there a discrepancy between the native `dispatchEvent` handling in Firefox vs Chrome/Safari which is keeping these events from being picked up by the event listeners?

### System configuration
Rails '5.2.0.beta2'

**Ruby version**:
2.4.2

**Comment by georgeclaghorn** [comment]
cc @javan

**Comment by javan** [comment]
I suspect this was fixed by https://github.com/rails/rails/pull/30568. It looks like the [npm package](https://www.npmjs.com/package/activestorage) isn't being published when Rails updates are released. The latest published version is `0.1.1`, but should be: https://github.com/rails/rails/blob/edcd32edadd0d6d6b505f59436d05c6a890d4d7c/activestorage/package.json#L3

cc @rafaelfranca

**Comment by javan** [comment]
Wups, my bad. `5.2.0-beta2` was released, but it's published under the `pre` npm dist-tag so it doesn't show up on  https://www.npmjs.com/package/activestorage.

```
$ npm view activestorage@pre
 
{ name: 'activestorage',
  description: 'Attach cloud and local files in Rails applications',
  'dist-tags': { latest: '0.1.1', pre: '5.2.0-beta2' },
  versions: [ '0.1.0', '0.1.1', '5.2.0-beta1', '5.2.0-beta2' ],
  …
```

@DLawla, can you please try with `"activestorage": "5.2.0-beta2"` in your `package.json` and let me know if the problem persists?

**Comment by DLawla** [comment]
@javan, thanks for the follow-up.
Our package.json is up-to-date (`"activestorage": "5.2.0-beta2"`), but the problem is still persisting for me after testing in Firefox (version: 57.0.4) 😢

**Comment by javan** [comment]
Oh, Firefox 👴🏻

**Comment by DLawla** [comment]
@javan Why did you close this? I'm still experiencing the issue, unfortunately.

**Comment by javan** [comment]
I fixed the issue with https://github.com/rails/rails/commit/21417e02e906f6b64f013aafefdc0cb8ea8b5e74. It will be included in the next Rails release.

**Comment by DLawla** [comment]
Ahh I see. Thanks for the update, and good work!

**Comment by xijo** [comment]
@javan Is there any way to release / quickfix this problem without waiting for the next rails release cycle. Firefox not working is kind of a show stopper.. 🦊

**Comment by javan** [comment]
@xijo, if you're using webpacker: `yarn add activestorage@5.2.0-rc1`. Or, just copy [the source](https://unpkg.com/activestorage@5.2.0-rc1/app/assets/javascripts/activestorage.js) into your app.
