### ISSUE TITLE
[ActiveStorage] DiskController doesn't support HTTP range

### ISSUE THREAD

**Issue by cpunion** [rails/rails#32193]
I'm building a video server with Rails 5.2.0.rc1, and play video in a React Native app, but the app always throws:

```
Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped"
```

Error description:

> The HTTP server sending the media resource is not configured as expected. This might mean that the server does not support byte range requests.

### Steps to reproduce

`curl -H "Accept-Ranges: bytes" -H "Range: bytes=0-1" ACTIVE_STORAGE_DOWNLOAD_URL -v`

### Expected behavior
Returns `206 Partial Content` with `Content-Range` header.

### Actual behavior
Response with `200 OK` and without `Content-Range` header.

### System configuration
**Rails version**:
5.2.0.rc1

**Ruby version**:
2.4.1

**Comment by michaldarda** [comment]
Accept-Ranges is header sent by server, not client

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests

> If sites omit the Accept-Ranges header, they likely don't support for partial requests. Some sites also explicitly send "none" as a value, indicating no support. In some apps, download managers disable their pause buttons in that case.If sites omit the Accept-Ranges header, they likely don't support for partial requests. Some sites also explicitly send "none" as a value, indicating no support. In some apps, download managers disable their pause buttons in that case.

**Comment by janko-m** [comment]
FWIW, Shrine implements this logic in its [`rack_response`](https://github.com/shrinerb/shrine/blob/master/lib/shrine/plugins/rack_response.rb) plugin (which is then called in the [`download_endpoint`](https://github.com/shrinerb/shrine/blob/master/lib/shrine/plugins/download_endpoint.rb)), so it might be worth taking a look there when implementing this functionality.

**Comment by Bartuz** [comment]
Awesome @janko-m, we are looking forward to implement it with @mdarda

**Comment by rderik** [comment]
@michaldarda , It is returned by the server when the server handles a direct file access, and if the person is using Apache or Nginx it will probably already be handled by default with any extra configuration, but here the one handling the request is actually the application (Rails), I think there should be a way to at least tell the client that it is not supported instead of seeming as if it is supported but then fail and produce unexpected results.

We can do a simple test using a recording resource that has an audio_file with ActiveStorage and then try to listen to it on Safari.

The template would be something like this:
`  <%= audio_tag rails_blob_url(recording.audio_file, disposition: "attachment"), controls: true, preload: "none"%>`

If you check that on Safari you'll see that Safari expects it to handle the Range request but Rails actually doesn't handle it so the audio file is shown as a "live broadcast" because, here is my assumption, it doesn't get answered with the whole size of the file or which ranges are acceptable.

I've seen this method in the disk_service.rb:
https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service/disk_service.rb#L41

That seems to show that `download_chunk` is supported but I haven't come across any documentation on how to use it.

Does that mean that the range download is supported?

**Comment by janko-m** [comment]
> It is returned by the server when the server handles a direct file access, and if the person is using Apache or Nginx it will probably already be handled by default with any extra configuration, but here the one handling the request is actually the application (Rails), I think there should be a way to at least tell the client that it is not supported instead of seeming as if it is supported but then fail and produce unexpected results.

AFAIK the server should return `Accept-Ranges: bytes` response header if it supports Range requests. If the server doesn't return this header, the client should take it that the server *doesn't* support Range requests. What would be wrong is if the ActiveStorage controller would return `Accept-Ranges: bytes` response header, but then didn't support Range requests, which I think is not the case.

Apache/Nginx will take care of Range requests if you delegate serving the file from disk to them (by making the reponse body respond to `#to_path` and using `Rack::Sendfile`), which isn't the case here as the file doesn't have to be from disk.

> If you check that on Safari you'll see that Safari expects it to handle the Range request but Rails actually doesn't handle it so the audio file is shown as a "live broadcast" because, here is my assumption, it doesn't get answered with the whole size of the file or which ranges are acceptable.

If you use an `<audio>` or `<video>` tag, the browser will try to make Range requests regardless of whether the server supports them or not. This is because the browser only knows whether the server supports range requests after looking at the response headers from the first request. And I *think* the browser decides that it pays off more to make Range requests in parallel with the first request, than to make the first request, check the response headers, and then make subsequent Range requests if it sees `Accept-Ranges: bytes`.

**Comment by rderik** [comment]
Thanks for your reply @janko-m.

>AFAIK the server should return Accept-Ranges: bytes response header if it supports Range requests.
Yea I think this is the case too.

But the crux is:
> Apache/Nginx will take care of Range requests if you **delegate serving the file from disk** to them (by making the reponse body respond to #to_path and using Rack::Sendfile), **which isn't the case here as the file doesn't have to be from disk**.

The file is being served by the DiskController( so we can assume the file is being served from disk), so the DiskController should set the headers and use the Rack::Sendfile.

Or how would someone go about it with the current tools provided by ActiveStorage? `rails_blob_path` doesn't seem to trigger the server to catch and handle the request.

**Comment by rderik** [comment]
Oh, I didn't know it was already fixed, it'll be a matter to wait for the next release then. 

https://github.com/rails/rails/commit/847342c25c61acaea988430dc3ab66a82e3ed486#diff-17640e7129bc730594120c1ac91d7928

**Comment by janko-m** [comment]
The streaming response code that's currently on `master` doesn't fix this issue, it was just a better alternative to loading the whole content into memory and using `#send_data`.

One way would be to use `#send_file`, which by itself doesn't do ranged requests, so that approach relies on Nginx/Apache being set up to serve files (otherwise it still works, but you don't have Range requests support).

Another way is to use `Rack::File`, which supports Range requests and works with `Rack::Sendfile` (so it will still delegate file serving to Nginx/Apache if configured). I think something like the following should work in a Rails controller:

```rb
file_status, file_headers, file_body = Rack::File.new(nil).serving(request, path)
response.status = file_status
response.headers.merge!(file_headers)
self.response_body = file_body
```
