### ISSUE TITLE
Capybara tests won't compile Webpacker assets in `rake test:system`

### ISSUE THREAD

**Issue by danielpclark** [rails/rails#32347]
### Steps to reproduce

Clone this repo https://github.com/danielpclark/vue_example/tree/SecondBlogVersion

Set up with:

```
bundle
yarn install
rake db:create
rake db:migrate
```

You can see the VueJS components working in development or production mode when you run `rails s` and browse to `http://localhost:3000/documents/new` and `http://localhost:3000/documents/{id}`.  Both the form and show resource are VueJS components and Rails nicely prepares the resource via webpacker with live-ish reloading :+1: .

### Expected behavior

Since it works with normal use I expect `rails test:system` to allow Capybara to use webpacker resources.

### Actual behavior

When running `rails test:system` none of the webpacker components get compiled or loaded for Capybara to properly test.  The example project has no form loaded for it to run its test through.

### System configuration
**Rails version**: Rails 5.2.0.rc2

**Ruby version**: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

**Comment by danielpclark** [comment]
I just noticed I need to hit refresh on any page where I want it to work the first time.  Closing until I diagnose that.  I'll re-open if that's not the issue.

**Comment by danielpclark** [comment]
Okay, I fixed my Turbolinks issue.  Everything I asserted initially in this issue above still holds true.  I've also updated the tag in my repo so the link above is still accurate for what to clone and test.

**Comment by pixeltrix** [comment]
@danielpclark does setting `config.action_controller.allow_forgery_protection = true` fix your issue? It looks like it's barfing because it can't find the CSRF token in the HTML <head> element.

**Comment by pixeltrix** [comment]
@danielpclark when I changed the config it fixed the CSRF token issue but the tests still failed because Capybara couldn't find the textarea element labelled 'Body' because it didn't have a 'for' attribute - I assume that's an issue with the form binding by Vue.js

**Comment by danielpclark** [comment]
I found the config had an existing setting and changed that and now the form does show up like you say.  Previously I had tried just putting the setting in and it was later overwritten in the same file.

I've swapped the order of the fields Capybara looks for and the same issue occurs with the normal text input field.  So I can take it from here.

Thank you for your help!

**Comment by danielpclark** [comment]
@pixeltrix  If you don't mind, could you tell me how you got verbose enough output to get those details?

**Comment by pixeltrix** [comment]
> If you don't mind, could you tell me how you got verbose enough output to get those details?

@danielpclark I did `RAILS_ENV=test rails server` 😉
