### ISSUE TITLE
Transaction problem of active storage

### ISSUE THREAD

**Issue by 8398a7** [rails/rails#32449]
### Steps to reproduce

added test to activestorage/test/models/attachments_test.rb

```ruby
  test "transaction test" do
    @user.avatar.attach create_blob(filename: "funky.jpg", data: "funky.jpg")

    perform_enqueued_jobs do
      e = assert_raises NoMethodError do
        ActiveRecord::Base.transaction do
          @user.avatar.attach create_blob(filename: "town.jpg", data: "town.jpg")
          foo!
        end
      end
    end

    assert_equal "funky.jpg", @user.reload.avatar.filename.to_s
    assert_equal "funky.jpg", @user.reload.avatar.download
  end
```

### Expected behavior

Processing is rolled back, funky.jpg remains as a record, and funky.jpg can be downloaded.

When updating a record, there may be a validation error in elements other than AS.
If you create a transaction, you also expect the behavior of rolling back files at this time.

Actually, `#purge_later` processing as callback is defined as `after_destroy_commit.`
https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/macros.rb#L47

However, under the influence of the following code it seems that `#purge_later` will be running before commit.
https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/one.rb#L32

How about stopping calling `#purge_later` in `#attach` and adding a condition other than `attached?` to the condition of `#purge_later` in `attched/one.rb` ?
https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/attached/one.rb#L65

### Actual behavior

```bash
 $ > bundle exec rake test TEST=test/models/attachments_test.rb TESTOPTS="--name=test_transaction_test"
Missing service configuration file in test/service/configurations.yml
== 20170806125915 CreateActiveStorageTables: migrating ========================
-- create_table(:active_storage_blobs)
   -> 0.0009s
-- create_table(:active_storage_attachments)
   -> 0.0011s
== 20170806125915 CreateActiveStorageTables: migrated (0.0021s) ===============

==  ActiveStorageCreateUsers: migrating =======================================
-- create_table(:users)
   -> 0.0003s
==  ActiveStorageCreateUsers: migrated (0.0004s) ==============================

Run options: --name=test_transaction_test --seed 2624

# Running:

E

Error:
ActiveStorage::AttachmentsTest#test_transaction_test:
Errno::ENOENT: No such file or directory @ rb_sysopen - /var/folders/k5/20ls9d1173n5_gyvbrbwwlj00000gn/T/active_storage_tests20180404-36880-1xgsfyj/KM/Ph/KMPhTUemVRXARBZKP9aB6Dqn



bin/rails test /Users/username/.ghq/github.com/rails/rails/activestorage/test/models/attachments_test.rb:46



Finished in 0.081944s, 12.2035 runs/s, 24.4069 assertions/s.
1 runs, 2 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**: master branch(a07d0680787ced3c04b362fa7a238c918211ac70)

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

cc: @georgeclaghorn

**Comment by claudiob** [comment]
A similar behavior is described in #31985

**Comment by CodingAnarchy** [comment]
The `after_destroy_commit` is to remove the attachment if you destroy the original record that the macro is included in.  The use of `purge_later` in `attach` is to destroy the old attachment if you upload a new one.

However, if you roll back the transaction when uploading a new file, it deletes the old attachment anyway because that `purge_later` enqueues a job that runs outside of the transaction.

I think this can be solved by not running `purge_later` in `attach`, but then there needs to be another way to delete the old attachment when it is replaced.  Perhaps an `after_update_commit` that searches for the newly orphaned records and removes them?  Maybe an `ActiveStorage::Attachment.where(record: self).where.not(id: "#{name}_attachment".id).map(&:purge_later)` would do the trick?

**Comment by CodingAnarchy** [comment]
Note: I've been getting around this by monkey-patching ActiveStorage to not do a `purge_later` in the `attach`, and to instead call `ActiveStorage::Blob.unattached.map(&:purge_later)` in an after_update_commit hook.  However, I recognize the latter is not going to work as a general solution.

Perhaps the general solution would be to add to`purge_later` an optional parameter that requires the blob to be unattached first and skip the purge if not?

**Comment by georgeclaghorn** [comment]
Would you mind trying latest master to see if this problem still exists?

**Comment by georgeclaghorn** [comment]
Never mind. I confirmed this is fixed in master. Thanks for reporting!

**Comment by CodingAnarchy** [comment]
Any chance of a link to where it was fixed? And will it be in a new release of 5.2 or just Rails 6?

**Comment by georgeclaghorn** [comment]
It was fixed in #33303, 28db8ba6, and bd5eba1. Those are breaking changes, so they’ll only land in 6.0.

**Comment by CodingAnarchy** [comment]
Alright, good to know.  Thanks!

**Comment by michaelschmitz** [comment]
Until 6.0 is there this still causes problem in my app, for example having the orphaned documents still show up in the view after validation fails. To fix this in a simple way use a quick check whether the element is attached and the id is not nil (something is the model, invoice the name of active storage document):

```
<% if @something.invoice.attached? and @something.invoice.id != nil %>
show stuff
<% end %>
```

**Comment by kreintjes** [comment]
Same problem over here. When I have a form with image upload which contained a validation error (on some other field), then the image is partially removed and replaced with some corrupt object, which responds to `attached?` but can't be displayed (and crashes when trying to call variant on it). This causes various pages in my app to crash, when someone has a validation error in some completely other form.

This problem makes ActiveStorage much less usable for Rails 5.2 apps. It would be really nice if it could be backported or some workaround would be available (so images aren't removed until the whole form is valid, or if not possible are completely removed instead of still responding to `attached?`).

**Comment by seanfcarroll** [comment]
+1 for backporting to 5.2 or if not possible a recommended workaround.

**Comment by hraynaud** [comment]
I have to say this is really disappointing. We've all been encouraged to use ActiveStorage (instead of paperclip, carrierwave etc, already losing some well established features like being able provide folder structure for our files) and now this issue which I also got caught with. I can understand if you can't fix it until rails 6 but how about if the core team could provide some guidance on acceptable and scalable work around.
