### ISSUE TITLE
LoadError when multiple threads try to load the same namespaced class

### ISSUE THREAD

**Issue by DimitriosLisenko** [rails/rails#33209]
### Version Information
Ruby: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`
Rails: `Rails 5.2.0`

### Steps to reproduce
- Create brand new rails project using `rails new awesome_application`
- Create a directory called `app/models/deep` and a file called `app/models/deep/beep.rb` with the following beautifully succinct code:
```
module Beep
  Class Deep
  end
end
```
- Open up the rails console and run `Deep::Beep` - all good!
- Close and open up the rails console again and run `2.times { |i| Thread.new { Rails.application.executor.wrap { Deep::Beep } } }` - oh no! Sometimes fails with:
```
.../activesupport-5.2.0/lib/active_support/dependencies.rb:452: warning: already initialized constant Deep
.../activesupport-5.2.0/lib/active_support/dependencies.rb:452: warning: previous definition of Deep was here
#<Thread:0x00007fd4795428b0@(irb):1 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from (irb):1:in `block (2 levels) in irb_binding'
	4: from .../activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
	3: from (irb):1:in `block (3 levels) in irb_binding'
	2: from .../activesupport-5.2.0/lib/active_support/dependencies.rb:193:in `const_missing'
	1: from .../bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
.../activesupport-5.2.0/lib/active_support/dependencies.rb:510:in `load_missing_constant': Unable to autoload constant Deep::Beep, expected .../app/models/deep/beep.rb to define it (LoadError)
```

### Why does this happen?
There is a race condition where two threads will concurrently run the `const_missing` method for the `Deep` module, and both will run the `autoload_module!` method and create two **separate** `Deep` module objects on each thread - I believe it should be a single object for any given module.

Then, one of the threads will load the `Beep` class into its local module object using `require_or_load` (which is mutexed globally with `Dependencies.load_interlock`) and continue happily, while the other will run `require_or_load`, determine that `Beep` is already loaded, and then raise `LoadError` because its local module (`from_mod` in the source code) does **not** have the `Beep` class defined on it.

**Comment by javan** [comment]
I'm unable to reproduce this:

```bash
$ cat app/models/deep/beep.rb 
module Deep
  class Beep
  end
end

$ rails -v
Rails 5.2.0

$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

```irb
>> Deep::Beep
=> Deep::Beep

>> 2.times { |i| Thread.new { Rails.application.executor.wrap { Deep::Beep } } }
=> 2

>> 2000.times { |i| Thread.new { Rails.application.executor.wrap { Deep::Beep } } }
=> 2000
```

I believe a related issue was recently fixed in bootsnap. Try pointing your Gemfile at `Shopify/bootsnap` instead of v1.3.0.

**Comment by javan** [comment]
Oops, I missed your "Close and open up the rails console again and run" step. I was able to repro by doing that, and can confirm that it's fixed in bootsnap master.

**Comment by DimitriosLisenko** [comment]
@javan I don't think this is a bootsnap issue - in my main Rails code base I don't use bootsnap (commented out in `config/boot.rb`) and still experience this issue.

**Comment by javan** [comment]
Confirmed, sorry about that. I saw bootstrap in your backtrace and jumped the gun. Curious that using bootstrap actually fixes the issue.

**Comment by shepmaster** [comment]
I believe we are seeing this in our tests, manifesting as

> .../gems/activesupport-5.0.7/lib/active_support/dependencies.rb:464: warning: already initialized constant ...
> .../gems/activesupport-5.0.7/lib/active_support/dependencies.rb:464: warning: previous definition of ... was here

and

> A copy of ... has been removed from the module tree but is still active

Here's my debug logging that has led me to this conclusion; I've hand-annotated the lines prefixed with `#`:

```
# Rack middleware is printing out the request path and HTTP Referer header
/jobs/6/activity_items from http://127.0.0.1:50343/projects/6
/jobs/6/subscribers from http://127.0.0.1:50343/projects/6
.../gems/activesupport-5.0.7/lib/active_support/dependencies.rb:464: warning: already initialized constant NewUi
.../gems/activesupport-5.0.7/lib/active_support/dependencies.rb:464: warning: previous definition of NewUi was here
# Note that the second starting marker is printed before the first ending marker 
>>>
>>>
# One thread calls autoload_module and we start printing its backtrace
autoload_module!(NewUi, :Jobs, "NewUi::Jobs", "new_ui/jobs")
.../gems/activesupport-5.0.7/lib/active_support/dependencies.rb:522:in `load_missing_constant'
.../gems/activesupport-5.0.7/lib/active_support/dependencies.rb:203:in `const_missing'
.../gems/activesupport-5.0.7/lib/active_support/inflector/methods.rb:270:in `const_get'
# The second thread also calls autoload_module and starts printing its backtrace
autoload_module!(NewUi, :Jobs, "NewUi::Jobs", "new_ui/jobs")
.../gems/activesupport-5.0.7/lib/active_support/inflector/methods.rb:270:in `block in constantize'
.../gems/activesupport-5.0.7/lib/active_support/inflector/methods.rb:266:in `each'
.../gems/activesupport-5.0.7/lib/active_support/dependencies.rb:522:in `load_missing_constant'
.../gems/activesupport-5.0.7/lib/active_support/dependencies.rb:203:in `const_missing'
.../gems/activesupport-5.0.7/lib/active_support/inflector/methods.rb:270:in `const_get'
# snip end of backtrace
`call'
<<<
# snip end of backtrace
<<<
2018-08-01 11:20:04 -0400: Rack app error handling request { GET /jobs/6/activity_items }
#<ArgumentError: A copy of NewUi::Jobs has been removed from the module tree but is still active!>
```

Rack middleware snippet

```ruby
  def call(env)
    STDERR.puts "#{env['PATH_INFO']} from #{env['HTTP_REFERER']}"
# ... snip real implementation
    @app.call(env)
  end
```

Modified `activesupport-5.0.7/lib/active_support/dependencies.rb`:

```ruby
    def autoload_module!(into, const_name, qualified_name, path_suffix)
      return nil unless base_path = autoloadable_module?(path_suffix)
      if qualified_name =~ /NewUi::Jobs/
        STDERR.puts ">>>"
        STDERR.puts "autoload_module!(#{into.inspect}, #{const_name.inspect}, #{qualified_name.inspect}, #{path_suffix.inspect})"
        STDERR.puts caller
        STDERR.puts "<<<"
      end
      mod = Module.new
      into.const_set const_name, mod
      autoloaded_constants << qualified_name unless autoload_once_paths.include?(base_path)
      autoloaded_constants.uniq!
      mod
    end
```

We are using 

- Ruby 2.5.1p57
- Rails 5.0.7
- Puma 3.12.0

**Comment by DimitriosLisenko** [comment]
I looked a little bit further into this - to be completely safe (since `ActiveSupport::Dependencies.clear` can run at any moment, and we don't want it to run while `load_missing_constant` runs assuming everything up the chain has been loaded), I changed the `const_missing` method to this:

```
def const_missing(const_name)
  Dependencies.load_interlock do
    from_mod = anonymous? ? guess_for_anonymous(const_name) : self
    return from_mod.const_get(const_name) if from_mod.const_defined?(const_name, false)
    Dependencies.load_missing_constant(from_mod, const_name)
  end
end
```

Unfortunately, this still results in NameError sometimes. This is because Ruby does not pass `Module.nesting` at the point `const_missing` was called, so there is some workaround code that works with some assumptions about the nesting around this point (blob attached):
https://github.com/rails/rails/blob/29b1984a05db7c556bde2a7a79a9062fbdf1a4da/activesupport/lib/active_support/dependencies.rb#L525
which is unfortunately not thread safe.

For example, consider the following code:
```
# a.rb
class A
end

# b.rb
class B
  # let's assume there is code in this class that calls A
end

# rails console (let's pretend this is a web server with multiple threads)
Object.const_missing(:B) # returns class B

# multiple threads try loading class A from class B before class A has been loaded
B.const_missing(:A) # returns class B
B.const_missing(:A) # throws NameError (uninitialized constant B::A) as a result of the above blob
```

If we had the nesting, we could correctly emulate Ruby's constant lookup, but at the moment we can't do that. There is a Ruby feature request to pass in the nesting here: https://bugs.ruby-lang.org/issues/2740.

**Comment by DimitriosLisenko** [comment]
Ha! Yes, you are correct. That's what I get for trying to be funny - my actual tests were using `A` and `A::B`, which is harder to mess up :)

The issue still stands, so I updated the original post, thanks.

**Comment by akshah123** [comment]
I am running into a similar problem with rails 5.0.7 and puma 3.12.1.

Is this issue resolved in later rails version? If not, is there a workaround?

**Comment by akshah123** [comment]
@shepmaster Were you able to find a solution for your issue?  It seems like my setup is very similar to yours.

**Comment by goelinsights** [comment]
I just had the same issue (I’m using rails as an API with a JavaScript front end) and setting eager_load to true in development environment files seems to have worked for now.

It means resetting the server for every rails change, but I was having to do that anyway due to other issues that seem to be related to name spacing.

**Comment by shepmaster** [comment]
> Were you able to find a solution for your issue

@akshah123 I do not think so. We still periodically trigger this in development mode when switching git branches (refreshing the page once or twice usually works). We've turned on eager loading for the test environment to avoid it there.

**Comment by akshah123** [comment]
This is really interesting.  I am actually seeing this problem not in development but in production where we do have eager_load set to true.  I am trying out bootsnap in prod to see if that addresses the problem.

**Comment by hudon** [comment]
we're running into this when using `concurrent-ruby`'s promises. We're on ruby 2.5.3, rails 5.2.3. Also, we can repro the OP:
```
$ cat app/models/deep/beep.rb 
module Deep
  class Beep
    
  end
end
$ rails c
irb(main):001:0> 2.times { |i| Thread.new { Rails.application.executor.wrap { Deep::Beep } } }
=> 2
~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:456: warning: already initialized constant Deep
~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:456: warning: previous definition of Deep was here
#<Thread:0x00007ff74126b160@(irb):1 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from (irb):1:in `block (2 levels) in irb_binding'
	3: from ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
	2: from (irb):1:in `block (3 levels) in irb_binding'
	1: from ~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:195:in `const_missing'
~/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:511:in `load_missing_constant': Unable to autoload constant Deep::Beep, expected ~/code/projects/canix/entrc-backend/app/models/deep/beep.rb to define it (LoadError)
irb(main):002:0> 

```

**Comment by jose-airspace** [comment]
I am experiencing this issue on ruby 2.6.2 and rails 5.1.6.2

**Comment by stevenleeg** [comment]
I'm also seeing this issue on ruby 2.6.5 and rails 5.2.3

**Comment by ajw725** [comment]
i'm also seeing this with ruby 2.6.5 and rails 5.1.4. it's happening both in the rails server and in sidekiq. it seems to happen mostly/only on the first request after restarting the server (or sidekiq), and enabling eager loading in development fixes it. i've ensured that all of our classes/modules are defined correctly and in directories corresponding to their names/hierarchies.

**Comment by shepmaster** [comment]
I haven’t tested thoroughly, but switching to zeitwerk as part of upgrading to Rails 6 did allow us to switch back to lazy loading.

**Comment by ajw725** [comment]
in addition to the example @DimitriosLisenko gave with the rails console, i was able to reproduce this in a similarly simple rails 5 app by making two very quick HTTP requests to the same endpoint. [repo here](https://github.com/ajw725/autoload_rails_bug). it's just a single model, `Foo::Bar`, defined in app/models/foo/bar.rb. there's a controller with two endpoints; the first endpoint loads a simple view, which contains javascript that makes two GET requests (via `fetch`) to a second controller endpoint, which just initializes `Foo::Bar`.

the bug doesn't happen every time, but i've seen it twice now, both times immediately after i restarted the server. here is the output:

```
=> Booting Puma
=> Rails 5.1.7 application starting in development 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.2 (ruby 2.6.5-p114), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2020-02-14 20:26:14 -0700
Processing by PagesController#home as HTML
  Rendering pages/home.html.erb within layouts/application
  Rendered pages/home.html.erb within layouts/application (1.2ms)
Completed 200 OK in 373ms (Views: 208.9ms)

Started GET "/cause_bug.json" for 127.0.0.1 at 2020-02-14 20:26:15 -0700
Started GET "/cause_bug.json" for 127.0.0.1 at 2020-02-14 20:26:15 -0700
Processing by PagesController#cause_bug as JSON
Processing by PagesController#cause_bug as JSON
Completed 500 Internal Server Error in 13ms
  
NameError (uninitialized constant PagesController::Foo):
  
app/controllers/pages_controller.rb:6:in `cause_bug'
Completed 200 OK in 151ms (Views: 0.2ms)
```

you can see that one of the requests succeeds while the other fails.

info:
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
rails 5.1.7
MacBookPro14,1 (13 inch, 2017)
macOS catalina (10.15.2)

**Comment by ajw725** [comment]
ok, actually - much more reliable (i.e. 100%) repro in sidekiq on [this branch](https://github.com/ajw725/autoload_rails_bug/tree/sidekiq-repro).

steps:

 * start redis
 * boot the application (rails server) but do **not** start sidekiq
 * load the home page
 * start sidekiq

the enqueued workers will run immediately, and the output will look like this:

```
2020-02-15T04:16:07.161Z 45213 TID-oxdsbi0us INFO: Starting processing, hit Ctrl-C to stop
2020-02-15T04:16:07.186Z 45213 TID-oxdsgmct8 TestWorker JID-8fc1a98daa016cf9f4813902 INFO: start
2020-02-15T04:16:07.194Z 45213 TID-oxdsgmb6w TestWorker JID-e692288c0977ed9bac2d2d96 INFO: start
2020-02-15T04:16:07.201Z 45213 TID-oxdsgmb6w TestWorker JID-e692288c0977ed9bac2d2d96 INFO: fail: 0.007 sec
2020-02-15T04:16:07.201Z 45213 TID-oxdsgmb6w WARN: {"context":"Job raised exception","job":{"class":"TestWorker","args":[],"retry":false,"queue":"default","jid":"e692288c0977ed9bac2d2d96","created_at":1581740163.4420302,"enqueued_at":1581740163.442235},"jobstr":"{\"class\":\"TestWorker\",\"args\":[],\"retry\":false,\"queue\":\"default\",\"jid\":\"e692288c0977ed9bac2d2d96\",\"created_at\":1581740163.4420302,\"enqueued_at\":1581740163.442235}"}
2020-02-15T04:16:07.201Z 45213 TID-oxdsgmb6w WARN: LoadError: Unable to autoload constant Foo::Bar, expected /Users/andrewweinstein/repos/autoload_bug/app/models/foo/bar.rb to define it
2020-02-15T04:16:07.201Z 45213 TID-oxdsgmb6w WARN: /Users/andrewweinstein/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:512:in `load_missing_constant'
/Users/andrewweinstein/.rvm/gems/ruby-2.6.5/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:202:in `const_missing'
/Users/andrewweinstein/repos/autoload_bug/app/workers/test_worker.rb:6:in `perform'
[...]
2020-02-15T04:16:07.201Z 45213 TID-oxdsgmct8 TestWorker JID-8fc1a98daa016cf9f4813902 INFO: done: 0.015 sec
```

the worker with JID 8fc... completes successfully, but the worker with JID e69... fails with a LoadError.

**Comment by ajw725** [comment]
the other interesting thing here is that the error message/failure location actually changes from run to run, presumably depending on the exact timing of the threads or something like that. it can fail either with the LoadError described above (i.e. if `require_or_load(expanded, qualified_name)` returns false) OR right at the beginning of `#load_missing_constant` with an ArgumentError (i.e. if `qualified_const_defined?(from_mod.name)` is false). i tested in a docker container (debian 9.11 / stretch), ran the same example twice in a row, and got two different error messages:

```
root@35d525d0a9a1:/home/users/andrewweinstein/autoload_rails_bug# bundle exec rails c
Running via Spring preloader in process 13964
Loading development environment (Rails 5.1.7)
irb(main):001:0> 2.times do
irb(main):002:1* Thread.new do
irb(main):003:2* Rails.application.executor.wrap { Foo::Bar }
irb(main):004:2> end
irb(main):005:1> end
=> 2
irb(main):006:0> /usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:457: warning: already initialized constant Foo
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:457: warning: previous definition of Foo was here
#<Thread:0x0000559e377c5350@(irb):2 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from (irb):3:in `block (2 levels) in irb_binding'
	3: from /usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/execution_wrapper.rb:85:in `wrap'
	2: from (irb):3:in `block (3 levels) in irb_binding'
	1: from /usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:202:in `const_missing'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:496:in `load_missing_constant': A copy of Foo has been removed from the module tree but is still active! (ArgumentError)

irb(main):007:0>
root@35d525d0a9a1:/home/users/andrewweinstein/autoload_rails_bug# bundle exec rails c
Running via Spring preloader in process 13968
Loading development environment (Rails 5.1.7)
irb(main):001:0> 2.times { Thread.new { Rails.application.executor.wrap { Foo::Bar } } }
=> 2
irb(main):002:0> /usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:457: warning: already initialized constant Foo
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:457: warning: previous definition of Foo was here
#<Thread:0x0000559e37920c68@(irb):1 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from (irb):1:in `block (2 levels) in irb_binding'
	3: from /usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/execution_wrapper.rb:85:in `wrap'
	2: from (irb):1:in `block (3 levels) in irb_binding'
	1: from /usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:202:in `const_missing'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:512:in `load_missing_constant': Unable to autoload constant Foo::Bar, expected /home/users/andrewweinstein/autoload_rails_bug/app/models/foo/bar.rb to define it (LoadError)
```

**Comment by supert56** [comment]
I'm also seeing this issue. I have a React app that's calling a Rails Api (Rails v5.1.7). 

When the React app first loads it calls two endpoints asynchronously very rapidly. When the server has just been restarted one of these requests will always fail. 

Switching to `eager_load = true` does work as a workaround for me.

I'm going to try upgrading to rails 6 to see if this solves it.

**Comment by supert56** [comment]
Nope sadly this is still happening even on rails 6.0.3 :(

![image](https://user-images.githubusercontent.com/1561873/81288378-71459d00-905c-11ea-9f9d-9fb9b0d216dd.png)

**Comment by Bhacaz** [comment]
A other workaround that works for us was to only use one thread in development to keep the `eager_load = false`.

```ruby
# config/puma/development.rb
workers 1
threads 1, 1
```

* Rails 5.0.7.2
* Ruby 2.6.6
* Puma 4.3.5

**Comment by DimitriosLisenko** [comment]
@Bhacaz FWIW that's what we're doing as well, and also running the following configuration in `config/environments/development.rb` due to #33133, which essentially means no code reloading for Sidekiq:
```
config.cache_classes = Sidekiq.server? ? true : false
config.eager_load = Sidekiq.server? ? true : false
```

I'm hopeful that moving to Rails 6 and migrating the autoloader to use zeitwerk will resolve this particular issue, though that's obviously a time consuming move.

**Comment by ziaulrehman40** [comment]
Someone please reopen this

**Comment by YutaFujii0** [comment]
Let me just add another example of this issue (looks same as what @ajw725 post before).
A very quick sequence of http request can cause either

- `ArgumentError` A copy of XXX has been removed from the module tree but is still active!
- `LoadError` Unable to autoload constant XXX, expected /.../.../....rb to define it

This becomes bothering when I build Vue instance in rails and send multiple api request from the component.

Reproduction code here:
https://github.com/YutaFujii0/constant-demo

ruby 2.6.3
rails 6.0.3.6
*note*: I'm using Classic mode (not Zeitwerk)

**Comment by DimitriosLisenko** [comment]
We have switched to zeitwerk and I can confirm that this is no longer an issue once you do that.

**Comment by softbrada** [comment]
I am having this issue on Rails 6.1.7 and Ruby 3.0.4 with classic autoloader 

Any ideas how to fix this ? thank you . Without switching to zeitwerk, i am looking for a simple patch perhaps.

**Comment by Timmitry** [comment]
Since the classic autoloader is deprecated, I doubt that this issue will get fixed in Rails. @softbrada, I guess your best choice would be to switch to Zeitwerk, which you will have to do anyway at some point. Or try to use some of the workarounds mentioned here 🤷

**Comment by softbrada** [comment]
I honestly believe this would get fixed if these changes https://github.com/rails/rails/pull/41877

I had a similar issue with resque-scheduler using Object.const_missing which is overridden by ActiveSupport::Dependencies::ModuleConstMissing  . Once i used instead Object.const_get it worked fine.  


I am using ruby 3.0.4 . perhaps the changes can be done to  support this only for Ruby >= 2.7 so that on older rubies the behavior remains, but on ruby >= 2.7  we could use Object.const_get. 

Would this make sense?

**Comment by pkaruovic** [comment]
I've encountered the same issue on the project I'm working on. After some investigation I found the following.
If we take this code as an example
```ruby
# controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  Billing::Invoice 
end

# models/billing/invoice.rb
module Billing
  class Invoice
  end
end
```
The process of loading `Billing::Invoice` constant can be described by following pseudocode:
1. load const `Billing` (it is not resolved by ruby so it has to be autoloaded)
1.1. check if file `billing.rb` exists in autoload paths
1.2. check if directory `billing` exists in autoload paths (it does)
    1.2.1. create module `Billing`
2. load const `Invoice`
2.1. check if file `billing/invoice.rb` exists in autoload paths (it does)
    2.1.1. load/require the file `billing/invoice.rb`
    2.1.2. check if the constant `Invoice` is now defined on the `Billing` module and raise `LoadError` error if not

The issue with concurrent execution arises on step 1.2.1 as the code which creates "automatic" modules is not thread
safe. See [`autoload_module!`](https://github.com/rails/rails/blob/v6.1.7.6/activesupport/lib/active_support/dependencies.rb#L499C4-L507C8) method
```ruby
def autoload_module!(into, const_name, qualified_name, path_suffix)
  return nil unless base_path = autoloadable_module?(path_suffix)
  mod = Module.new
  into.const_set const_name, mod
  autoloaded_constants << qualified_name unless autoload_once_paths.include?(base_path)
  autoloaded_constants.uniq!
  mod
end
```
Rails does not check if the module is already defined and does not synchronise access to this method which in turn results
in multiple instances of `Billing` module being created. On each of those instances the `const_missing` method is later invoked (in step 2)
for the constant `Invoice`. The code that loads the `Invoice` constant is thread safe (see [load_missing_constant](https://github.com/rails/rails/blob/v6.1.7.6/activesupport/lib/active_support/dependencies.rb#L540) and [require_or_load](https://github.com/rails/rails/blob/v6.1.7.6/activesupport/lib/active_support/dependencies.rb#L397) methods) and
loads the `Invoice` constant only once. The `Invoice` constant is then saved in the constants table of one of created 
`Billing` modules, but step 2.1.2 is invoked for each of them resulting in the `LoadError` error being raised.

It seems that the issue can be solved by simply making `autoload_module!` method thread safe. I've experimented with 
this solution and it appears to have resolved the issue.

**Comment by bogdanRada** [comment]
@pkaruovic can you share how you resolved this issue please? Just out of curiosity. Thank you. I would love to learn something new

**Comment by pkaruovic** [comment]
@bogdanRada  sure. I've monkey-patched the `autoload_module!` method to make it thread-safe and added a check to see if the module is already defined before attempting to define it. See the code below. 
```ruby
def autoload_module!(into, const_name, qualified_name, path_suffix)
  return nil unless base_path = autoloadable_module?(path_suffix)

  ActiveSupport::Dependencies.load_interlock do
    if into.const_defined? const_name, false
      into.const_get const_name, false
    else
      mod = Module.new
      into.const_set const_name, mod
      autoloaded_constants << qualified_name unless autoload_once_paths.include?(base_path)
      autoloaded_constants.uniq!
      mod
    end
  end
end
```
