### ISSUE TITLE
ActiveRecord issue when retrying transaction due to serialization error

### ISSUE THREAD

**Issue by intale** [rails/rails#33855]
### Steps to reproduce
I prepared a [repo](https://github.com/intale/ar_trx_retry_issue) that has a description of issue and executable to reproduce it(see [Issue description](https://github.com/intale/ar_trx_retry_issue#issue-description)). A copy-paste from there:
To reproduce an issue, an executable file is created `bin/ar_test`. Just run `./bin/ar_test` from bash console.
Source code of `bin/ar_test`:

```ruby
#!/usr/bin/env ruby
#
require File.expand_path('../../config/environment.rb', __FILE__)

def subject
  query_parts = []
  callback = proc {|_, _, _, _, payload| query_parts << payload[:sql] unless payload[:name] == 'SCHEMA'}
  ActiveSupport::Notifications.subscribed callback, 'sql.active_record' do
    query
  end
  query_parts
end

def query
  ActiveRecord::Base.transaction do
    SerializationTest.where(value: 1).exists?
    SerializationTest.create(value: 1)
    sleep 1
  end
rescue => error
  if error.message.index('could not serialize')
    retry
  end
end

pid = fork do
  ActiveRecord::Base.transaction do
    SerializationTest.where(value: 1).exists?
    SerializationTest.create(value: 1)
  end
end

puts *subject
Process.waitpid(pid)
```

You will see next output:

```sql
WARNING:  there is no transaction in progress
BEGIN
SELECT  1 AS one FROM "serialization_tests" WHERE "serialization_tests"."value" = 1 LIMIT 1
INSERT INTO "serialization_tests" ("value") VALUES (1) RETURNING "id"
COMMIT
ROLLBACK
BEGIN
SELECT  1 AS one FROM "serialization_tests" WHERE "serialization_tests"."value" = 1 LIMIT 1
INSERT INTO "serialization_tests" ("value") VALUES (1) RETURNING "id"
COMMIT
```

Take a look at first transaction that was rolled back:

```sql
BEGIN
...
COMMIT
ROLLBACK
```

Do you see that redundant `COMMIT` statement? And, as a result, a warning from pg gem - 
`WARNING:  there is no transaction in progress`

That is it. By quickly inspecting the code, I concluded that it comes from the ActiveRecord(not from pg gem). It is there a statements are prepared and finally executed with `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter#exec_query`.
Of course `#exec_query` itself is not a source of a problem - I didn't try to dig deeper. Ideas/suggestions/notices are welcome.

### Expected behavior
`COMMIT` statement should not be executed on transaction's rollback

### Actual behavior
`COMMIT` statement is executed alongside with `ROLLBACK` statement when retrying a transaction.

### System configuration
**Rails version**: 5.2.1/6.0.0.alpha

**Ruby version**: 2.5.1

**Postgresql version**: 10.5

**OS version**: Ubuntu 18.04

**Postgresql transactions isolation level**: serializable

**Comment by y-yagi** [comment]
Thanks for your report. This already fixed with #32647.

**Comment by intale** [comment]
Hey, @y-yagi. Thanks for your reply. I set `gem 'rails', github: 'rails/rails'` in a test project I mentioned above, and an issue is still there.

**Comment by y-yagi** [comment]
Are there any issues yet? I tested your repo with `master`. It seems redundant `COMMIT` statement should not be executed.  


**5.2.1**

```
$ ./bin/ar_test
WARNING:  there is no transaction in progress
BEGIN
SELECT  1 AS one FROM "serialization_tests" WHERE "serialization_tests"."value" = 1 LIMIT 1
INSERT INTO "serialization_tests" ("value") VALUES (1) RETURNING "id"
COMMIT
ROLLBACK
BEGIN
SELECT  1 AS one FROM "serialization_tests" WHERE "serialization_tests"."value" = 1 LIMIT 1
INSERT INTO "serialization_tests" ("value") VALUES (1) RETURNING "id"
COMMIT 
```  

**master**
 
```
$ ./bin/ar_test
BEGIN
SELECT  1 AS one FROM "serialization_tests" WHERE "serialization_tests"."value" = 1 LIMIT 1
INSERT INTO "serialization_tests" ("value") VALUES (1) RETURNING "id"
ROLLBACK
BEGIN
SELECT  1 AS one FROM "serialization_tests" WHERE "serialization_tests"."value" = 1 LIMIT 1
INSERT INTO "serialization_tests" ("value") VALUES (1) RETURNING "id"
COMMIT
```

**Comment by intale** [comment]
Have just tested(cleared gemset before test and installed gems again) - an issue is still there. Mb there is some setting was added in rails 6 that tells rails to take into account isolation level? Just in case - your pg uses serializable transaction isolation? Could you please provide your postgresql.conf - I'll try it.

**Comment by y-yagi** [comment]
Here is my conf.

```
data_directory = '/var/lib/postgresql/9.5/main'		# use data in another directory
hba_file = '/etc/postgresql/9.5/main/pg_hba.conf'	# host-based authentication file
ident_file = '/etc/postgresql/9.5/main/pg_ident.conf'	# ident configuration file
external_pid_file = '/var/run/postgresql/9.5-main.pid'			# write an extra PID file

port = 5432				# (change requires restart)
max_connections = 100			# (change requires restart)
unix_socket_directories = '/var/run/postgresql'	# comma-separated list of directories
ssl = true				# (change requires restart)
ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'		# (change requires restart)
ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'		# (change requires restart)

shared_buffers = 128MB			# min 128kB
dynamic_shared_memory_type = posix	# the default is the first option
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
pg_stat_statements.max = 10000
track_activity_query_size = 2048

log_directory = 'pg_log'		# directory where log files are written,
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'	# log file name pattern,
log_min_duration_statement = 1000	# -1 is disabled, 0 logs all statements
log_line_prefix = '%t [%p-%l] %q%u@%d '			# special values:
log_timezone = 'Japan'

stats_temp_directory = '/var/run/postgresql/9.5-main.pg_stat_tmp'

default_transaction_isolation = 'serializable'

datestyle = 'iso, ymd'
timezone = 'Japan'

lc_messages = 'ja_JP.UTF-8'			# locale for system error message
lc_monetary = 'ja_JP.UTF-8'			# locale for monetary formatting
lc_numeric = 'ja_JP.UTF-8'			# locale for number formatting
lc_time = 'ja_JP.UTF-8'				# locale for time formatting

default_text_search_config = 'pg_catalog.simple'
```

**Comment by NirvashPrime** [comment]
That's a great find! Is this issue good to be closed?

**Comment by y-yagi** [comment]
Oh, sorry I misunderstood. I will try your repository later.

**Comment by 9mm** [comment]
soo is thi still a problem in rails 6? Im researching how to use serializable isolation level and came across this

**Comment by intale** [comment]
The warning is still there. It doesn't affect on anything, though.
