### ISSUE TITLE
Numericality validation does not work as intended with decimals

### ISSUE THREAD

**Issue by fschwahn** [rails/rails#35426]
### Steps to reproduce
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  # gem "activerecord", "~> 5.1.0"
  # gem "activerecord", "~> 5.2.0"
  gem "activerecord", "~> 6.0.0.beta2"
  gem "sqlite3", "~> 1.3.0"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
    t.decimal :pay, precision: 7, scale: 2
  end
end

class Post < ActiveRecord::Base
  validates :pay, numericality: { greater_than: 0, less_than: 10_000, allow_blank: true }
end

class BugTest < Minitest::Test
  def test_pay_validation
    post = Post.new(pay: 0.001)
    assert_equal post.pay, 0 # this passes
    assert post.pay.zero? # this passes
    assert_raises(ActiveRecord::RecordInvalid) { post.save! } # this fails
  end
end
```

### Expected behavior
A validation error is raised, because pay is 0 (as shown by the first assertion), and it should be greater than 0.

### Actual behavior
No validation error is raised. If I replace `0.001` with `0.00` the test passes.

### System configuration
**Rails version**: 6.0.0.beta2, but also 5.2.x, 5.1.x

**Ruby version**: 2.5.3

**Comment by bparanj** [comment]
**Rails version**: 6.0.0.beta2, 5.2.x, 5.1.x
**Ruby Version**: 2.6.1

Verified on Alpine Docker image. It is failing for me too.

```
  1) Failure:
BugTest#test_pay_validation [/usr/local/bin/test_case.rb:47]:
ActiveRecord::RecordInvalid expected but nothing was raised.

1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by fschwahn** [comment]
@bparanj If you set pay to `0.01` it is correct when the test fails, because 0.01 is greater than 0, so the validation passes (and no exception should be raised).

I think the error is connected to the rounding activerecord does for decimal values, and the fact that `NumericalityValidator` uses `pay_before_type_cast`, which is not rounded:

```ruby
post = Post.new(pay: 0.001)
puts post.pay # => 0
puts post.pay_before_type_cast # => 0.001
```

I think this is on purpose (see 47a6d788ddbab08b2a04c72cd80352aac44090ab), but it's still pretty confusing. We have invalid values in our database which we thought were caught by such a validation.

**Comment by azbshiri** [comment]
@kamipo I don't think this would be considered as inconsistency due  `_before_type_cast` postfix which exactly means what it should mean?!

I'd always assert against public interface of a model instead of digging for internal attributes

**Comment by fschwahn** [comment]
Still reproducible in `5-2-stable` and `master`

**Comment by fschwahn** [comment]
Still an issue with latest master

**Comment by simi** [comment]
:information_source: still present. I have extended original reproducer to contain also spec showing that validation is bypassed.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "~> 6.0.0"
  gem "sqlite3", "~> 1.3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
    t.decimal :pay, precision: 7, scale: 2
  end
end

class Post < ActiveRecord::Base
  validates :pay, numericality: { greater_than: 0, less_than: 10_000, allow_blank: true }
end

class BugTest < Minitest::Test
  def test_pay_validation
    post = Post.new(pay: 0.001)
    assert_equal post.pay, 0 # this passes
    assert post.pay.zero? # this passes
    assert_raises(ActiveRecord::RecordInvalid) { post.save! } # this fails
  end

  # pay should be greater than 0, but 0 is actually stored and validation is bypassed
  def test_bypassed_validation
    post = Post.new(pay: 0.001)
    assert_equal post.pay, 0 # this passes
    assert post.pay.zero? # this passes
    post.save # should not save, but it actually pass
    post.reload # reload data from DB
    refute_equal 0, post.pay # should pass, but fails since validation is bypassed
  end
end
```

**Comment by fschwahn** [comment]
Unfortunately, this was _not_ fixed by #36664

**Comment by simi** [comment]
I can confirm @gmcgibbon, my snippet at https://github.com/rails/rails/issues/35426#issuecomment-568896173 still fails on master.

**Comment by fschwahn** [comment]
Thanks for fixing this!
