### ISSUE TITLE
Deprecation warning re: single arity template handlers when running tests for new Rails 6 app

### ISSUE THREAD

**Issue by jasonrudolph** [rails/rails#35505]
### Steps to reproduce

Using Rails 6.0.0.beta2, generate a new app, set up the database, and run the tests:

```
$ rails new example --no-rc

$ cd example

$ rails db:create

$ rails db:migrate

$ rails test
```

### Expected behavior

Tests should run successfully without displaying any deprecation warnings.

### Actual behavior

Tests run successfully, but show a deprecation warning regarding the use of single arity template handlers:

```
$ rails test

DEPRECATION WARNING: Single arity template handlers are deprecated.  Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
  >> Class#call(template)
To:
  >> Class#call(template, source)
 (called from <main> at /private/tmp/example/config/environment.rb:5)
Running via Spring preloader in process 14588
DEPRECATION WARNING: Single arity template handlers are deprecated.  Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
  >> Class#call(template)
To:
  >> Class#call(template, source)
 (called from <main> at /private/tmp/example/config/environment.rb:5)
Run options: --seed 48493

# Running:

Finished in 0.080358s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

### System configuration

**Rails version**:

```
$ rails -v
Rails 6.0.0.beta2
```

**Ruby version**:

```
$ ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
```

---

Note: It looks like this deprecation warning was introduced in 28f88e0074f473f58c2d3fd54cb3daff81027c12 as part of https://github.com/rails/rails/pull/35119.

**Comment by bogdanvlviv** [comment]
Hey, thanks for the report. This warning comes from https://github.com/rails/jbuilder and it is already fixed by https://github.com/rails/jbuilder/pull/453. This warning will be eliminated when a new version of jbuilder is released.
/cc @tenderlove

**Comment by lrjbrual** [comment]
@bogdanvlviv I encounter same issue when I run rails db:migrate or rails s: 

```
DEPRECATION WARNING: Single arity template handlers are deprecated.  Template handlers must
now accept two parameters, the view object and the source for the view object.

Change:
  >> Class#call(template)
To:
  >> Class#call(template, source)
 (called from <main> at /Users/ryanjeff/railsprojects/portfolio/config/application.rb:18)
```

### System configuration
`Rails 6.0.0.beta3`
`ruby 2.6.2p47`

**Comment by alexpapworth** [comment]
@lrjbrual: As @bogdanvlviv mentioned, this has been fixed. Add this line to your gemfile for now 😄 

    gem 'jbuilder', github: 'rails/jbuilder', branch: 'master'

It should get added to the next release of the jbuilder gem.

**Comment by iarobinson** [comment]
Hummmm.... I'm still getting the exact deprecation error mentioned above. 

When I changed: 
`gem 'jbuilder', '~> 2.5'`
to
`gem 'jbuilder', github: 'rails/jbuilder', branch: 'master'`

The deprecation warning didn't change.

**Comment by donwildman** [comment]
Hi,
I'm getting this for more than one call
For example I get this error for
Coffee::Rails::TemplateHandler.call(template)
and
#<Mab::RailsHandler:0x00005635fb1ee740>.call(template)

any ideas?

**Comment by donwildman** [comment]
SOLVED
Updating coffee-rails to 5.0.0 fixed this for me

**Comment by conr** [comment]
I also had to update [temple](https://github.com/judofyr/temple/) from `0.8.0` to `0.8.2` in order to fix this.

**Comment by rtsinani** [comment]
Updating `jbuilder` with `bundle update jbuilder` worked for me.

**Comment by Deepak275** [comment]
Thanks @iarobinson and @donwildman 😄 , doing both helped me with rails 6 😅

**Comment by kalvinchang** [comment]
If you are getting the following, you need to upgrade hamlit to 2.11.0 as well https://github.com/k0kubun/hamlit/pull/138

```
Change:
  >> #<Hamlit::RailsTemplate:0x00007fdd2b18f320>.call(template)
To:
  >> #<Hamlit::RailsTemplate:0x00007fdd2b18f320>.call(template, source)
```

**Comment by danielricecodes** [comment]
How do you track down the source when `jbuilder` isn't in your `Gemfile`?

**Comment by danielricecodes** [comment]
> I also had to update [Temple](https://github.com/judofyr/temple/) from `0.8.0` to `0.8.2` in order to fix this.

`slim` depends on Temple.  In my case `bundle update slim-rails` solved the problem because this also updated Temple!

**Comment by vidurpunj** [comment]
Updated following gems:

# gem 'coffee-rails', '~> 4.2'

to: => gem 'coffee-rails'

and 

# gem 'jbuilder', '~> 2.5',
 to :=> gem 'jbuilder', github: 'rails/jbuilder', branch: 'master'

solved the warning issue
