### ISSUE TITLE
rails 6.0.0.beta3: undefined method `env_name' for [nil]:Array (NoMethodError) in active_record/database_configurations.rb:72

### ISSUE THREAD

**Issue by deepj** [rails/rails#35646]
I'm trying to upgrade one of my Rails apps I'm currenlly working. I have a standard `database.yml`. 

```
default: &default
  adapter: postgresql
  pool: 30
  timeout: 5000
  variables:
    statement_timeout: 10000

development: &development
  <<: *default
  database: database_development

test:
  <<: *development
  database: database_test

production:
  <<: *default
  host: 127.0.0.1
  pool: 4
  database: database_production
  username: database
  password: <%= Rails.application.credentials.db_password if Rails.env.production? %>

staging:
  <<: *default
  database: database_staging

database_backup: &database_backup
  <<: *default
  database: database

```
### Steps to reproduce
run an app with Rails 6.0.0.beta3 with the above `database.yml`

### Expected behavior
It doesn't throw the error

### Actual behavior
I get this

```
Traceback (most recent call last):
	161: from bin/rails:9:in `<main>'
	160: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `require'
	159: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:263:in `load_dependency'
	158: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `block in require'
	157: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	156: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	155: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	154: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	153: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	152: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/commands.rb:18:in `<main>'
	151: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/command.rb:46:in `invoke'
	150: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/command/base.rb:65:in `perform'
	149: from ~/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	148: from ~/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	147: from ~/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	146: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/commands/server/server_command.rb:136:in `perform'
	145: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/commands/server/server_command.rb:136:in `tap'
	144: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	143: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/commands/server/server_command.rb:36:in `start'
	142: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	141: from ~/.gem/ruby/2.5.3/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	140: from ~/.gem/ruby/2.5.3/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	139: from ~/.gem/ruby/2.5.3/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	138: from ~/.gem/ruby/2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	137: from ~/.gem/ruby/2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	136: from ~/.gem/ruby/2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	135: from config.ru:in `<main>'
	134: from config.ru:in `new'
	133: from ~/.gem/ruby/2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	132: from ~/.gem/ruby/2.5.3/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	131: from config.ru:5:in `block in <main>'
	130: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
	129: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `require'
	128: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:263:in `load_dependency'
	127: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `block in require'
	126: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	125: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	124: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	123: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	122: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	121: from ~/app/config/environment.rb:5:in `<main>'
	120: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/application.rb:362:in `initialize!'
	119: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/initializable.rb:60:in `run_initializers'
	118: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	117: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	116: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	115: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	114: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	113: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	112: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	111: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	110: from ~/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	109: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/initializable.rb:61:in `block in run_initializers'
	108: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/initializable.rb:32:in `run'
	107: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/initializable.rb:32:in `instance_exec'
	106: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/application/finisher.rb:141:in `block in <module:Finisher>'
	105: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/application/routes_reloader.rb:10:in `execute'
	104: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/file_update_checker.rb:83:in `execute'
	103: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/application/routes_reloader.rb:30:in `block in updater'
	102: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/application/routes_reloader.rb:20:in `reload!'
	101: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/application/routes_reloader.rb:41:in `load_paths'
	100: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/application/routes_reloader.rb:41:in `each'
	 99: from ~/.gem/ruby/2.5.3/gems/railties-6.0.0.beta3/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
	 98: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:291:in `load'
	 97: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:263:in `load_dependency'
	 96: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:291:in `block in load'
	 95: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 94: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 93: from ~/app/config/routes.rb:1:in `<main>'
	 92: from ~/.gem/ruby/2.5.3/gems/actionpack-6.0.0.beta3/lib/action_dispatch/routing/route_set.rb:413:in `draw'
	 91: from ~/.gem/ruby/2.5.3/gems/actionpack-6.0.0.beta3/lib/action_dispatch/routing/route_set.rb:431:in `eval_block'
	 90: from ~/.gem/ruby/2.5.3/gems/actionpack-6.0.0.beta3/lib/action_dispatch/routing/route_set.rb:431:in `instance_exec'
	 89: from ~/app/config/routes.rb:25:in `block in <main>'
	 88: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise/rails/routes.rb:242:in `devise_for'
	 87: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise/rails/routes.rb:242:in `each'
	 86: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise/rails/routes.rb:243:in `block in devise_for'
	 85: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise.rb:350:in `add_mapping'
	 84: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise.rb:350:in `new'
	 83: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise/mapping.rb:72:in `initialize'
	 82: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise/mapping.rb:162:in `default_used_route'
	 81: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise/mapping.rb:95:in `routes'
	 80: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise/mapping.rb:78:in `modules'
	 79: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise/mapping.rb:83:in `to'
	 78: from ~/.gem/ruby/2.5.3/gems/devise-4.6.1/lib/devise.rb:320:in `get'
	 77: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:626:in `constantize'
	 76: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:595:in `get'
	 75: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/inflector/methods.rb:280:in `constantize'
	 74: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/inflector/methods.rb:280:in `inject'
	 73: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/inflector/methods.rb:280:in `each'
	 72: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/inflector/methods.rb:282:in `block in constantize'
	 71: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/inflector/methods.rb:282:in `const_get'
	 70: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:201:in `const_missing'
	 69: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	 68: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 67: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
	 66: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:517:in `load_missing_constant'
	 65: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:47:in `require_or_load'
	 64: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 63: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `block in require_or_load'
	 62: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:362:in `require_or_load'
	 61: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:37:in `load_interlock'
	 60: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 59: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 58: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 57: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 56: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:379:in `block in require_or_load'
	 55: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:482:in `load_file'
	 54: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:674:in `new_constants_in'
	 53: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:483:in `block in load_file'
	 52: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 51: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 50: from ~/app/app/models/user.rb:3:in `<main>'
	 49: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:201:in `const_missing'
	 48: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	 47: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 46: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
	 45: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:517:in `load_missing_constant'
	 44: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:47:in `require_or_load'
	 43: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 42: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `block in require_or_load'
	 41: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:362:in `require_or_load'
	 40: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:37:in `load_interlock'
	 39: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 38: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 37: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 36: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 35: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:379:in `block in require_or_load'
	 34: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:482:in `load_file'
	 33: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:674:in `new_constants_in'
	 32: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:483:in `block in load_file'
	 31: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 30: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 29: from ~/app/app/models/application_record.rb:3:in `<main>'
	 28: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `require'
	 27: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:261:in `load_dependency'
	 26: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:674:in `new_constants_in'
	 25: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:261:in `block in load_dependency'
	 24: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/dependencies.rb:297:in `block in require'
	 23: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	 22: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	 21: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	 20: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	 19: from ~/.gem/ruby/2.5.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	 18: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/base.rb:27:in `<main>'
	 17: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
	 16: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	 15: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/lazy_load_hooks.rb:51:in `each'
	 14: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	 13: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	 12: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	 11: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/lazy_load_hooks.rb:72:in `block in execute_hook'
	 10: from ~/.gem/ruby/2.5.3/gems/activesupport-6.0.0.beta3/lib/active_support/lazy_load_hooks.rb:72:in `class_eval'
	  9: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/railtie.rb:202:in `block (2 levels) in <class:Railtie>'
	  8: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/connection_handling.rb:50:in `establish_connection'
	  7: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/connection_handling.rb:173:in `resolve_config_for_connection'
	  6: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/connection_adapters/connection_specification.rb:140:in `resolve'
	  5: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/connection_adapters/connection_specification.rb:219:in `resolve_connection'
	  4: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/connection_adapters/connection_specification.rb:246:in `resolve_symbol_connection'
	  3: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/database_configurations.rb:71:in `find_db_config'
	  2: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/database_configurations.rb:71:in `find'
	  1: from ~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/database_configurations.rb:71:in `each'
~/.gem/ruby/2.5.3/gems/activerecord-6.0.0.beta3/lib/active_record/database_configurations.rb:72:in `block in find_db_config': undefined method `env_name' for [nil]:Array (NoMethodError)
```

### System configuration
**Rails version**: 6.0.0.beta3

**Ruby version**: Ruby 2.5.3

**Comment by morgoth** [comment]
This should be fixed in https://github.com/rails/rails/pull/35497 - can you try master which contains this patch?

**Comment by deepj** [comment]
@morgoth thanks, but I've tried the recent master (d8d6bd5e63a9), but the issue is still there.

**Comment by eileencodes** [comment]
This PR https://github.com/rails/rails/pull/35663 should fix the problem found here. Will merge once the tests pass. Thanks for the report @deepj!

**Comment by deepj** [comment]
@eileencodes thank you!
