### ISSUE TITLE
Implement ActionCable with Async

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#35657]
Is there any interest in simplifying the concurrency model and improving the scalability of ActionCable by using Async?

**Comment by schneems** [comment]
Generally we limit issues to only bugs and prefer discussion to happen on the mailing list (though in reality it’s kinda dead anyway).

I appreciate your libraries and your work. I’m not as intimately familiar with the internals of action cable and I’m curious to hear if there is interest here. I like the Puma PR and see that clearly epoll and friends are clearly better than select, though again I don’t know the details of how action cable concurrency is implemented.

**Comment by ioquatix** [comment]
Do you mind linking to the Puma PR, I'm not familiar with it.

To your other points, `Async` isn't just about `select` vs `epoll`, but more about sequential concurrency which makes it easier to write scalable systems.

ActionCable concurrency is currently a bespoke solution built on top of `concurrent-ruby` and `nio4r`. It uses a mixture of threads and event driven callbacks. My understand is that it doesn't scale very well, but I could be wrong.

**Comment by jeremy** [comment]
> any interest in simplifying the concurrency model and improving the scalability of ActionCable

Yes and yes.

> by using Async

What do you propose? (I'm not familiar with Async.)

/cc @palkan @matthewd

**Comment by ioquatix** [comment]
> What do you propose? (I'm not familiar with Async.)

The first thing if you have time is to get a bit more familiar with Async: https://github.com/socketry/async

We are currently exploring `async-websocket` client and server build directly on top of `async-http` which is performance comparable with puma.

https://github.com/socketry/async-websocket/pull/8

The proposal would basically be to build a compatible server on top of `async`. In the first instance, that might look like:

- Make some performance specs on top of existing code base (if they don't already exist).
- Remove nio4r event loop and `concurrent-ruby` timers and replace with `Async::Reactor`.
- Look at how the server should scale up - either the existing background thread approach, or something which operates independently (i.e. a separate server process which starts up multiple containers).

**Comment by palkan** [comment]
Hi @ioquatix!
That sounds interesting.

> Remove nio4r event loop and concurrent-ruby timers and replace with Async::Reactor.

Is this gonna be much different from running Action Cable with Falcon? (I guess, we still need `rack.hijack`).

I like the idea of having a separate server implementation (and actually proposed it [a while ago](https://github.com/rails/rails/pull/27648), check this PR for some caveats with the current implementation).

> ActionCable concurrency is currently a bespoke solution built on top of concurrent-ruby and nio4r. It uses a mixture of threads and event driven callbacks. My understand is that it doesn't scale very well, but I could be wrong.

It doesn't scale very well, right. The main reason though is the memory usage.
Broadcasting performance also not that good when dealing with large number of connections per stream (and that's what could be improved with a better concurrency model, I think).

> Make some performance specs on top of existing code base (if they don't already exist).

You can check my benchmarks: https://github.com/anycable/anycable/tree/master/benchmarks. [This one](https://github.com/anycable/anycable/blob/master/benchmarks/2018-10-27.md) includes Action Cable + Falcon and also `async-websocket`.

**Comment by ioquatix** [comment]
@palkan Thanks for implementing such a benchmark. You did a great job.

It's very interesting and a useful comparison since it's hard to find good benchmarks. I would like to see a combined graph too.

What's interesting to me is most servers performing very similarly. What this tells me is that the benchmark is probably not specific/isolated enough to reveal the performance characteristics of the individual servers. i.e. something other than server overhead is dominating a large percentage of the latency (maybe even `websocket-driver` itself, or the benchmark script itself).

Broadcast is a tricky issue. The typical implementation looks like this:

```ruby
connections.each do |connection|
	connection.send_message(message)
end
```

The problem with this approach is that sending the message for any given client increase the latency of all subsequent messages.

A more practical approach with `async` might look something like:

```ruby
Async do |task|
	connections.each do |connection|
		task.async do
			connection.send_message(message)
		end
	end
	
	task.children.each(&:wait)
end
```

This will still be limited to one processor/thread but hopefully this operation is mostly I/O bound. The only problem is, spinning up millions of tasks isn't free either, so you might like to batch this:

```ruby
require 'async'
require 'async/semaphore'

connections = (1...10).to_a

Async do |task|
	semaphore = Async::Semaphore.new(2)
	
	connections.each do |connection|
		semaphore.async do |subtask|
			puts connection
			subtask.sleep 1
		end
	end
	
	task.children.each(&:wait)
end
```

(I changed the example slightly so you can actually run it to see how it works, but you should get the general idea).

Finally, if you want to scale this up over multiple processes, you just do the same thing but use a shared backend e.g. Postgres, Redis, etc or some kind of pipe based pub/sub. While this solution has limitations, it should probably solve like 90% of problems with scaling large broadcasts. Ruby probably isn't the right solution for million+ connected clients/broadcasts, but if you are happy with 10k-100k  connections per server I think you'll be okay.

**Comment by ioquatix** [comment]
> I like the idea of having a separate server implementation.

There are some tricky issues with this direction.

You need to define some abstractions for dealing with concurrency which defer to the server event loop.

Something similar was implemented here: https://github.com/slack-ruby/slack-ruby-client#concurrency

Because it was done, it shows it's not impossible. But it's also hard for users because you don't solve concurrency for them and just kind of have to choose the best common interface between all servers, which sometimes doesn't give good results.

When I designed `async`, I took this into consideration. You can use `Async do...end` like `Thread.new do...end`. As long as you inject the right primitives, you can achieve some improvements to I/O concurrency.

One way to do this would be to extend some model of concurrency to the Rack SPEC:

```ruby
env['rack.concurrent'].call do |response|
	# Default implementation is similar to `Thread.new`.
	response.headers = {"cat" => "dog"}
	response.body.write("some data")
	response.close
end
```

You should allow more elaborate things such as web sockets by doing:

```ruby
if websocket?(request)
	env['rack.concurrent'].call do |response|
		websocket = WebSocket.new(request, response)
		while message = websocket.read_message
			# ... websocket.send_message(...)
		end
	end
end
```

The main point about this abstraction is you *might* want to define a standard set of IPC, or just defer back to ActiveRecord which is probably the simplest thing to do. Because most (good) models are semantically similar to `Thread`, it's the best one to use as a baseline, and think of `Async` as `Thread` but more scalable. That's probably the best, generic model.

**Comment by ioquatix** [comment]
I would like to give a summary of where I'm at with this.

I've implemented both full and partial hijack in falcon.

After doing that, I could implement HTTP/2 websocket support, which is only possible using partial hijack. Partial hijack is also better for HTTP/1 websocket implementation too.

So, I honestly think, for forwards compatibility, full hijack is a mistake, and should be removed in Rack 3.0.

Partial hijack is okay, but the way it works is a pain (response headers). It's better if we support response body with `call(stream)` for partial hijack. But it presents some compatibility issues.

Regarding this implementation, the main point is how do we support websockets and servers. Well, actually I believe the best approach is to use partial hijack, and have the server manage the concurrency. Right now, it's impossible to manage how actioncable works, and it feels like a hack because existing Ruby web servers don't handle many simultaneous connections, except falcon which I tested up to 100k concurrent connections with a single ruby process.

So, I think that:

- Full hijack doesn't make any sense w.r.t. HTTP/2.
- We should adopt partial hijack for WebSocket connections.
- We should remove full hijack from Rack and improve partial hijack implementation.
- ActionCable as it currently exists doesn't make sense for servers which support high levels of concurrency.

**Comment by dbackeus** [comment]
My personal findings when looking into this in 2023:

- The [ActionCable section](https://socketry.github.io/falcon/guides/rails-integration/index.html#actioncable) of Falcon's Rails integration documentation mentions the `async` adapter which is typically only used in development envioronments. It also mentions: _"You might like to try out [async-redis](https://github.com/socketry/async-redis) as an asynchronous message bus"_. But I'm not sure what the implications of this would be. Is there some readily available code to make use of `async-redis`?
- It seems like two projects that were attempted to implement ActionCable servers using async were abandoned pretty much right after their inception 4 years ago (https://github.com/piecehealth/async_cable and https://github.com/senid231/async_cable/tree/604b72b467d9a4a33cc8f67b8455ce5781e6bc23).
- The latest results of the AnyCable's WebSocket shootout [from 2020](https://github.com/anycable/anycable/blob/master/benchmarks/2020-06-30.md) only compares Puma and AnyCable. When trying to run the bench with `./bento --falcon` I personally got slightly worse results than with `--puma` on my M1 MacBook Pro. Considering how old the benchmarking code is I'm guessing there should be room for improvement.

@ioquatix any thoughts on progress ~4 years later? It seems like a WebSocket server for ActionCable using the new fiber scheduler could make sense. I'm not sure how to interpret your point stating _ActionCable as it currently exists doesn't make sense for servers with high levels of concurrency_. Do you feel like things could be improved or is there something fundamentally flawed with the underlying architecture?

For the record, Palkan's made a nice presentation on the ActionCable architecture at Rails World: [Untangling cables and demystifying twisted transistors](https://www.youtube.com/watch?v=GrHpop5HtxM&pp=ygURcmFpbHMgd29ybGQgY2FibGU%3D). Could be useful for anyone looking into this.

**Comment by palkan** [comment]
@dbackeus @ioquatix 

> The latest results of the AnyCable's WebSocket shootout [from 2020](https://github.com/anycable/anycable/blob/master/benchmarks/2020-06-30.md) only compares Puma and AnyCable

Yeah, I haven't published the results I got with this `./bento` script, but I still have some in this [dev.to draft](https://dev.to/palkan_tula/ruby-32-yjit-websockets-123d-temp-slug-2201718?preview=423dc949cbea6cadffd211c23da9c146c531b80258247f9d94477abbf6cf73e142b9410845c6b155bdf5f28c78128987023f2364b86f03da0950245f). There are two different benchmarks, one using [websocket-bench](https://github.com/anycable/websocket-bench) and another one using k6. The former shows good results for Falcon (forked) but the latter demonstrates suspiciously bad numbers; unfortunately, I haven't had time to investigate further.

**Comment by ioquatix** [comment]
I have been having a conversation with @matthewd about the implementation of ActionCable.

The "problem" right now is that the current design does not provide any way for alternative internal implementations.

I don't expect the performance to be any different between Falcon and Puma except perhaps the initial connection setup (before hijack). However, I'd personally like to remove hijack from Falcon as it's an extremely rough edge in the interface. In order to do that and still support ActionCable, we need a way to do the following:

- A mechanism to configure the ActionCable server class.
- A mechanism for the server class to specify the implementation of the worker pool.
- A mechanism for the server class to accept and handle an incoming rack request -> websocket connection (traditionally hijack).

Currently proposed entry points:

- Replacing https://github.com/rails/rails/blob/main/actioncable/lib/action_cable/connection/base.rb#L64 with `server.accept_client` or `server.websocket_for_request`, and then Server would have a configurable `websocket_class` or whatever.
- https://github.com/rails/rails/blob/4c5c904a212a850c43adb7a3c3a719ca3d2b9159/actioncable/lib/action_cable/server/base.rb#L36 might be a suitable configuration point.

**Comment by palkan** [comment]
> The "problem" right now is that the current design does not provide any way for alternative internal implementations.

That's true. I've been talking about this since the very early days (back in the [Google Groups days](https://groups.google.com/g/rubyonrails-core/c/PSbhfZ2LCWo/m/PJBf4VmzEgAJ)).

> I don't expect the performance to be any different between Falcon and Puma in the current implementation except perhaps the initial connection setup (before hijack)

Yeah, if you just replace the server part, that wouldn't help. That's why in my benchmarks I didn't use Action Cable server (and worker pool) at all. Instead, I used AnyCable (Ruby/Rails part) and connected it to Falcon _natively_: https://github.com/anycable/anycable/blob/master/benchmarks/rails/bento#L113

I also added an async-aware subscription adapter: https://github.com/anycable/anycable/blob/b7d2e86c5611a9660baaf166183ccea12da2c6da/benchmarks/rails/bento#L223

(though I think, it's still using internal threaded executor).

The code is far from perfect but it kinda demonstrates how an alternative server implementation may look like and which interface is required on the Action Cable side.

**Comment by ioquatix** [comment]
@palkan it sounds like we should work on this together along with @matthewd if he has time.

You probably have more context around the design space and what should be changed. Can we start hacking on a PR to make this possible? (a interface separating the application logic from the server implementation).

**Comment by palkan** [comment]
> Can we start hacking on a PR to make this possible? 

Yeah, let's do that. I'd be glad to start pocking around and prepare a draft but not earlier than next week. I wonder if it would make sense to create a separate channel at Ruby on Rails contributors Discord and continue discussion there 🤔

**Comment by washu** [comment]
Any updates from you guys re: Pr or draft speccs, and can alternate inut engines be considered i.e. assume it could be falcon or passenger or puma/thin.

**Comment by ioquatix** [comment]
Yes, the work is being done in this PR: https://github.com/rails/rails/pull/50979

**Comment by ioquatix** [comment]
With https://github.com/anycable/actioncable-next gem, it is possible to implement https://github.com/socketry/async-cable - this is an out of the box solution for Rails 8+ and perhaps older. If someone is able to test that in a production environment and report back on #50979, it would be be extremely helpful.
