### ISSUE TITLE
ActiveSupport::EventedFileUpdateChecker broken with no directories to watch

### ISSUE THREAD

**Issue by spuyet** [rails/rails#36158]
I've some trouble with `ActiveSupport::EventedFileUpdateChecker` on a project in dev mode.

```ruby
# config/development.rb
config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```
```ruby
# Gemfile
group :development do
  gem 'listen', require: false
end
```
When I start the app locally, the `ActiveSupport::EventedFileUpdateChecker::Listen` constant cannot be found:

```
$ bundle exec rails s
=> Booting Puma
=> Rails 5.2.2.1 application starting in development 
=> Run `rails server -h` for more startup options
Exiting
/home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `block in load_missing_constant': uninitialized constant ActiveSupport::EventedFileUpdateChecker::Listen (NameError)
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:76:in `rescue in load_missing_constant'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/evented_file_update_checker.rb:96:in `boot!'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/evented_file_update_checker.rb:67:in `initialize'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot_rails-5.0.1/lib/factory_bot_rails/reloader.rb:23:in `new'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot_rails-5.0.1/lib/factory_bot_rails/reloader.rb:23:in `build_reloader'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot_rails-5.0.1/lib/factory_bot_rails/reloader.rb:13:in `run'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot_rails-5.0.1/lib/factory_bot_rails/railtie.rb:22:in `block in <class:Railtie>'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
	from /home/sebastien/Projects/updown/config/environment.rb:5:in `<main>'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from config.ru:3:in `block in <main>'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:27:in `app'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:51:in `start'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/command/base.rb:65:in `perform'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/command.rb:46:in `invoke'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.2.1/lib/rails/commands.rb:18:in `<main>'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/sebastien/Projects/updown/bin/rails:8:in `<top (required)>'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /home/sebastien/Projects/updown/bin/spring:16:in `require'
	from /home/sebastien/Projects/updown/bin/spring:16:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

After having isolated the issue:
```
irb(main):001:0> require 'active_support'
=> true
irb(main):002:0> ActiveSupport::EventedFileUpdateChecker.new([]) {}
NameError: uninitialized constant ActiveSupport::EventedFileUpdateChecker::Listen
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/evented_file_update_checker.rb:96:in `boot!'
	from /home/sebastien/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/evented_file_update_checker.rb:67:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /home/sebastien/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
irb(main):003:0> 
```
It seems to be related to the way that we lazy load the `listen` gem here: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/evented_file_update_checker.rb#L68

We load the gem only if there is any directory to watch while the `#boot!` method which is always called is using the `Listen` constant. BTW we should probably use `::Listen` instead of `Listen`.

The fix is probably to call `#boot!` only if there is directories to watch or to remove this condition.

WDYT ?

### System configuration
ruby: `MRI 2.4.1`
rails: `5.2.2.1`

**Comment by y-yagi** [comment]
First, the cause of this error is `factory_bot_rails`. Since the error was fixed in https://github.com/thoughtbot/factory_bot_rails/pull/331, it does not occur in v5.0.2.

Of course, this error still occurs if you do not specify a target for a watch. However, it seems to me that it should be an argument error if the watch target is unspecified.

**Comment by spuyet** [comment]
Thanks for the explanation. I agree that we should raise an argument error when the array is empty, and more precisely once we've filtered out gem files, redundant and non-existent files.

**Comment by spuyet** [comment]
@y-yagi I've updated the code to raise an argument error in case of empty paths. I've also update the code of the [file update checker](https://github.com/rails/rails/pull/36163/files)(polling version of the files watcher) for consistency but this is breaking some specs as you can see [here](https://buildkite.com/rails/rails/builds/60923) in `activemodel`, `railties`, etc

That makes me think to different things:
- Does the argument error is the right solution ? the [FileUpdateChecker](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/file_update_checker.rb) is doing nothing special without paths, shouldn't we stick to this behavior for [EventedFileUpdateChecker](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/evented_file_update_checker.rb) too ?
- If we keep the argument error way, should we also update the FileUpdateChecker ? (like I did in the PR) Not sure about the possible side effects that will bring on all projects because in rails itself we already have some case with no paths :thinking:

**Comment by spuyet** [comment]
ping @y-yagi :smile:

**Comment by y-yagi** [comment]
I remembered why I didn't fix this myself.  

Since `EventedFileUpdateChecker` is a private API, it is assumed to be used only inside Rails. And this issue doesn't happen inside Rails.
https://github.com/rails/rails/blob/233927965d0bd79752274bbc7394d21efeda54c0/activesupport/lib/active_support/evented_file_update_checker.rb#L35 

If the external library encounters this issue using `EventedFileUpdateChecker`, it is the library's matter. So, I think that it is good to leave it as it is with respect to this.  
I missed considering that raising `ArgumentError` can be a issue when expanding `FileUPdateChecker`. Sorry for the confusion!

**Comment by spuyet** [comment]
Hmm I encountered the problem in rails at first and extracted the issue in a second time for clarity. It happened because my `rails` binstub has been wrapped by an old version of `spring` and was setting the `GEM_HOME` to `""` and then raising the above exception.

I understand your point but I think that the actual behavior doesn't make sense as we're calling a constant which may not be defined because we require the gem defining the constant only when we need it. I still think that `EventedFileUpdateChecker` should have the same behavior than `FileUpdateChecker`:

```
irb(main):001:0> require 'active_support'
=> true
irb(main):002:0> ActiveSupport::FileUpdateChecker.new([]) {}
=> #<ActiveSupport::FileUpdateChecker:0x005579760c3808 @files=[], @glob=nil, @block=#<Proc:0x005579760c37b8@(irb):2>, @watched=nil, @updated_at=nil, @last_watched=[], @last_update_at=1970-01-01 01:00:00 +0100>
irb(main):003:0>
```

IMHO this [commit](https://github.com/rails/rails/pull/36163/commits/6ccc990ca04e562da87f9428f78598fec6b6abb0) is the right thing to do, that is, doing nothing when there is no folders to watch.
