### ISSUE TITLE
webpack fails to compile with ActionText

### ISSUE THREAD

**Issue by willnet** [rails/rails#36368]
### Steps to reproduce

```sh
rails new sampleapp
cd sampleapp
./bin/rails action_text:install
./bin/webpack 
```

### Expected behavior

webpack compile without errors

### Actual behavior

```
Hash: a8bf5b9bd28ddb3deacf
Version: webpack 4.32.2
Time: 3186ms
Built at: 2019/05/31 14:33:31
                                     Asset       Size       Chunks             Chunk Names
    js/application-498850090c9b38b11a80.js    870 KiB  application  [emitted]  application
js/application-498850090c9b38b11a80.js.map    771 KiB  application  [emitted]  application
                             manifest.json  364 bytes               [emitted]  
Entrypoint application = js/application-498850090c9b38b11a80.js js/application-498850090c9b38b11a80.js.map
[./app/javascript/channels sync recursive _channel\.js$] ./app/javascript/channels sync _channel\.js$ 160 bytes {application} [built]
[./app/javascript/channels/index.js] 487 bytes {application} [built]
[./app/javascript/packs/application.js] 799 bytes {application} [built]
[./node_modules/webpack/buildin/amd-options.js] (webpack)/buildin/amd-options.js 80 bytes {application} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 1.01 KiB {application} [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 822 bytes {application} [built]
    + 302 hidden modules

ERROR in ./node_modules/@rails/actiontext/app/javascript/actiontext/attachment_upload.js 19:28-40
"export 'DirectUpload' was not found in '@rails/activestorage'
 @ ./node_modules/@rails/actiontext/app/javascript/actiontext/index.js
 @ ./app/javascript/packs/application.js
```

### System configuration
**Rails version**:
6.0.0.rc1
**Ruby version**:
2.6.3

**Comment by abhaynikam** [comment]
I can reproduce this issue on Rails `6.0.0.rc1` but not on the `master`.

**Comment by y-yagi** [comment]
Maybe related to https://github.com/rails/webpacker/issues/2109#issuecomment-497510204, https://github.com/rails/webpacker/pull/2111.

**Comment by jakeNiemiec** [comment]
Related issue: https://github.com/rails/rails/issues/36278#issuecomment-497778793

This should be fixed with 4.0.6.

**Comment by abhaynikam** [comment]
> This should be fixed with @rails/webpacker@4.0.6

@jakeNiemiec : I tried creating an app with Rails `6.0.0.rc1` and `@rails/webpacker@4.0.6`. It still fails with the same error.

here is the gist of files you had asked in the comment -> https://gist.github.com/abhaynikam/62f9c4b32ebe81fb01052c59dca63ea4

**Comment by jakeNiemiec** [comment]
Did you run `rails action_text:install`? Also, can you post the exact error to the gist?

**Comment by jernestosuarez** [comment]
Same error here with 6.0.0.rc1 and webpacker 4.0.6 after rails action_text:install in a fresh app.

**Comment by 0x2C6** [comment]
Same here

**Comment by jakeNiemiec** [comment]
@jernestosuarez @0x2C6 @abhaynikam Can you tell me if changing line 61 in your `babel.config.js` file fixes it?

```diff
      [
        require('@babel/plugin-transform-runtime').default,
        {
          helpers: false,
          regenerator: true,
-         corejs: 3
+         corejs: false
        }
      ],
```

If not, can you post a gist like this: https://github.com/rails/rails/issues/36368#issuecomment-497845766 (👆4 comments up)

**Comment by abhaynikam** [comment]
@jakeNiemiec : With the change suggested in the `babel.config.js` in the above comment(https://github.com/rails/rails/issues/36368#issuecomment-498289737). 

Webpack compile worked for me. 👍

**Comment by jernestosuarez** [comment]
@jakeNiemiec : works for me too.

**Comment by atstockland** [comment]
corejs: false Fixed me up too

**Comment by jakeNiemiec** [comment]
Glad to hear it. PR to fix for everyone: https://github.com/rails/webpacker/pull/2116
