### ISSUE TITLE
Preloading associations into multiple in-memory copies of the same record causes duplicates

### ISSUE THREAD

**Issue by pstare** [rails/rails#36396]
### Steps to reproduce

`::ActiveRecord::Associations::Preloader#preload` takes both `records` and `associations` as arguments. When preloading an association into multiple in-memory representations of the same underlying record (i.e. same `.id`, different `.object_id`), duplicates are created in the associations of both copies.

This gist is a runnable Ruby script that will result in 4 failures when used with Rails 6.0. The test failure output and test descriptions indicate the divergence in expected and actual behaviour:

https://gist.github.com/pstare/98674b05af5b70c45eea50d141462578

The issue seems to have been introduced between Rails 5.2 and 6.0, specifically in rails/rails#35496.

### Expected behavior

```ruby
post = Post.create!
comment = Comment.create!
post.comments << comment
post.save

post_object_1 = Post.find(1)
post_object_2 = Post.find(1)

::ActiveRecord::Associations::Preloader.new.preload([post_object_1, post_object_2], :comments)

post_object_1.comments  # expected: [<Comment(id: 1)>]
post_object_2.comments  # expected: [<Comment(id: 1)>]
```

### Actual behavior

```ruby
post_object_1.comments  # actual: [<Comment(id: 1)>, <Comment(id: 1)>]
post_object_2.comments  # actual: [<Comment(id: 1)>, <Comment(id: 1)>]
```

### System configuration
**Rails version**:
6.0.0.rc1

**Ruby version**:
2.6.2p47 

@bogdan @kamipo

**Comment by bogdan** [comment]
The problem comes from a fact that:

``` ruby
post_object_1 = Post.find(1)
post_object_2 = Post.find(1)
a = {}
a[post_object_1] = 1
a[post_object_2] = 2
a.length # => 1
```

It can be fixed by using `owner.object_id` instead of `owner` for a key in `Preloader#records_by_owner` (making it `records_by_owner_object_id`).

A more hacky way is this:

``` diff
           def owners_by_key
-            @owners_by_key ||= owners.each_with_object({}) do |owner, result|
+            @owners_by_key ||= owners.uniq.each_with_object({}) do |owner, result|
               key = convert_key(owner[owner_key_name])
               (result[key] ||= []) << owner if key
             end
```

It makes a green build with with new regression test introduced. However, it is a little hacky solution because we ignore some owners when forming `owners_by_key` because its doesn't need to be perfect in current structure.


I personally would not fix that because using preloader directly is not in the test suite and there is no way to ensure that no regression occur for that use case.

**Comment by kamipo** [comment]
We had already fixed similar issue #16436, but it was not added strict test case.

This regression could easily reproduce with public API by `Post.joins(:comments).preload(:comments)`, so we should fix this regression.

@bogdan Are you interested to make a PR to fix this?

**Comment by bogdan** [comment]
> This regression could easily reproduce with public API by Post.joins(:comments).preload(:comments), so we should fix this regression.

I don't think so that because I don't see a way you can have multiple instances for model with the same ID inside preloader: all records are loaded once for each id and then pushed to different associations if used twice while the remain the same object.
Did you reproduce it or just guessing?

The "true" way of fixing this is to introduce a special hash like `ActiveSupport::HashWithDifferentAccess` where cache key uniqueness is determined by `key1.object_id != key2.object_id` instead of `key1 != key2`. Does anyone know the way to easily get such behavour in Ruby+ActiveSupport?

**Comment by zhangyonguu** [comment]
@bogdan 

I have tried your hacky way, but I found that it still have a problem

Suppose A has_many B, and B has_many C

If I have a query:

```
query {
  A{
    B{
      C{
        field
       }
     }
  }
}
```

this hacky way can uniq A and B records, but C records still probably duplicated read. I came across it.

**Comment by bogdan** [comment]
@zhangyonguu  see https://github.com/rails/rails/pull/36429 for the right patch
