### ISSUE TITLE
Rails 6.0.0.rc1 'follower' database not configured for the 'beta' environment

### ISSUE THREAD

**Issue by sqlninja** [rails/rails#36595]
### Expected behavior
Read database configuration from database.yml

### Actual behavior
Seems to be ignoring the config

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.3

Getting the following error once app is deployed to heroku:
```
! Unable to load application: ActiveRecord::AdapterNotSpecified: The `follower` database is not configured for the `beta` environment.
2019-07-03T18:00:50.479868+00:00 app[web.1]: 
2019-07-03T18:00:50.479884+00:00 app[web.1]: Available databases configurations are:
2019-07-03T18:00:50.479885+00:00 app[web.1]: 
2019-07-03T18:00:50.479887+00:00 app[web.1]: default
2019-07-03T18:00:50.479889+00:00 app[web.1]: development
2019-07-03T18:00:50.479892+00:00 app[web.1]: test
2019-07-03T18:00:50.479893+00:00 app[web.1]: beta
2019-07-03T18:00:50.479895+00:00 app[web.1]: production
2019-07-03T18:00:50.480031+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.6.0/bin/puma)
2019-07-03T18:00:50.480171+00:00 app[web.1]: ActiveRecord::AdapterNotSpecified: The `follower` database is not configured for the `beta` environment.
2019-07-03T18:00:50.480174+00:00 app[web.1]: 
2019-07-03T18:00:50.480176+00:00 app[web.1]: Available databases configurations are:
2019-07-03T18:00:50.480178+00:00 app[web.1]: 
2019-07-03T18:00:50.480180+00:00 app[web.1]: default
2019-07-03T18:00:50.480182+00:00 app[web.1]: development
2019-07-03T18:00:50.480184+00:00 app[web.1]: test
2019-07-03T18:00:50.480185+00:00 app[web.1]: beta
2019-07-03T18:00:50.480188+00:00 app[web.1]: production
2019-07-03T18:00:50.480190+00:00 app[web.1]: 
2019-07-03T18:00:50.480192+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:251:in `resolve_symbol_connection'
2019-07-03T18:00:50.480195+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:219:in `resolve_connection'
2019-07-03T18:00:50.480197+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:140:in `resolve'
2019-07-03T18:00:50.480199+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:180:in `resolve_config_for_connection'
2019-07-03T18:00:50.480201+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:72:in `block in connects_to'
2019-07-03T18:00:50.480203+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:71:in `each'
2019-07-03T18:00:50.480205+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:71:in `connects_to'
2019-07-03T18:00:50.480208+00:00 app[web.1]:   /app/app/models/application_record.rb:3:in `<class:ApplicationRecord>'
2019-07-03T18:00:50.480214+00:00 app[web.1]:   /app/app/models/application_record.rb:1:in `<main>'
```

My database.yml file is configured like so:
```
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: app_name_dev
  follower:
    <<: *default
    database: app_name_dev

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: app_name_test
  follower:
    <<: *default
    database: app_name_test

beta:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  follower:
    <<: *default
    url: <%= ENV['FOLLOWER_DATABASE_URL'] %>

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  follower:
    <<: *default
    url: <%= ENV['FOLLOWER_DATABASE_URL'] %>
```

On heroku I have the following env vars setup:
```
ENVIRONMENT: beta
RACK_ENV: beta
RAILS_ENV: beta
DATABASE_URL: postgres://******:*********@ec2-54-146-144-124.compute-1.amazonaws.com:5432/***
FOLLOWER_DATABASE_URL: postgres://******:*********@ec2-3-218-119-149.compute-1.amazonaws.com:5432/***
```
As you can see the `beta` environment is declared in the yaml file , and seems to be found based on the environment specified in the error...

**Comment by sqlninja** [comment]
Just tested a deploy to my prod environment and got the same error on heroku:
```
ActiveRecord::AdapterNotSpecified: The `follower` database is not configured for the `production` environment.
Available databases configurations are:
default
development
test
beta
production
```

**Comment by eileencodes** [comment]
Can you create a sample application the reproduces the error? Also how are you establishing the connections to the other databases? I don't have enough information from this report to debug what the problem could be.

**Comment by eileencodes** [comment]
Specifically I wonder what's going on in `app/models/application_record.rb`.

If `follower` is supposed to be a replica you should first add `replica: true` to the database.yml declarations for the `follower` database. Then you need to make sure that ApplicationRecord calls `connects_to writing: :primary, reading: :follower`.

If `follower` is supposed to be another writer then you cannot connect to `follower` and `primary` using the same model. You must have 2 separate base models if they're both writers. The documentation [here](https://github.com/rails/rails/blob/master/guides/source/active_record_multiple_databases.md) describes this in detail.

**Comment by sqlninja** [comment]
Sorry forgot to post that:
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :follower }
end
```

**Comment by sqlninja** [comment]
The `follower` is indeed a replica on heroku...

So the database.yml should look like this? :
```
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: app_name_dev
  follower:
    <<: *default
    replica: true
    database: app_name_dev

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: app_name_test
  follower:
    <<: *default
    replica: true
    database: app_name_test

beta:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  follower:
    <<: *default
    replica: true
    url: <%= ENV['FOLLOWER_DATABASE_URL'] %>

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  follower:
    <<: *default
    replica: true
    url: <%= ENV['FOLLOWER_DATABASE_URL'] %>
```

**Comment by eileencodes** [comment]
Yes follower needs the `replica: true` entry in the database yaml.

**Comment by sqlninja** [comment]
Well, just deployed that to the beta environment on Heroku and it's still failing...

The full error is: 
```RAILS_ENV=beta environment is not defined in config/webpacker.yml, falling back to production environment
rails aborted!
ActiveRecord::AdapterNotSpecified: The `follower` database is not configured for the `beta` environment.
Available databases configurations are:
default
development
test
beta
production
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:251:in `resolve_symbol_connection'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:219:in `resolve_connection'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:140:in `resolve'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:180:in `resolve_config_for_connection'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:72:in `block in connects_to'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:71:in `each'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:71:in `connects_to'
/app/app/models/application_record.rb:3:in `<class:ApplicationRecord>'
/app/app/models/application_record.rb:1:in `<main>'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.1.8/lib/zeitwerk/kernel.rb:16:in `require'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activesupport/lib/active_support/dependencies.rb:302:in `require'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:213:in `primary_class?'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:207:in `connection_specification_name'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:231:in `retrieve_connection'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:199:in `connection'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/internal_metadata.rb:32:in `table_exists?'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/internal_metadata.rb:37:in `create_table'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/migration.rb:1199:in `initialize'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/migration.rb:1053:in `new'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/migration.rb:1053:in `up'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/migration.rb:1028:in `migrate'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/tasks/database_tasks.rb:236:in `migrate'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/railties/databases.rake:85:in `block (3 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/railties/databases.rake:83:in `each'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/railties/databases.rake:83:in `block (2 levels) in <main>'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/railties/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/railties/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/railties/lib/rails/command.rb:48:in `invoke'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/railties/lib/rails/commands.rb:18:in `<main>'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
/app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activesupport/lib/active_support/dependencies.rb:302:in `require'
/app/bin/rails:9:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by sqlninja** [comment]
This is from the release command which runs `rails db:migrate`

I'm going to try commenting that real quick to see if the build gets any further.

**Comment by eileencodes** [comment]
Ok, I don't see anything wrong with your setup so if you're unable to figure out the cause I'll need you to create a sample application the reproduces the error or provide a test case that reproduces it.

**Comment by sqlninja** [comment]
Ok so removing the `rails db:migrate` command did let the build finish.
But the app still crashes with the same error as above with minor variations:
```
2019-07-05T18:28:23.408508+00:00 app[web.1]: ! Unable to load application: ActiveRecord::AdapterNotSpecified: The `follower` database is not configured for the `beta` environment.
2019-07-05T18:28:23.408532+00:00 app[web.1]: 
2019-07-05T18:28:23.408535+00:00 app[web.1]: Available databases configurations are:
2019-07-05T18:28:23.408537+00:00 app[web.1]: 
2019-07-05T18:28:23.408540+00:00 app[web.1]: default
2019-07-05T18:28:23.408542+00:00 app[web.1]: development
2019-07-05T18:28:23.408544+00:00 app[web.1]: test
2019-07-05T18:28:23.408546+00:00 app[web.1]: beta
2019-07-05T18:28:23.408548+00:00 app[web.1]: production
2019-07-05T18:28:23.408803+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.6.0/bin/puma)
2019-07-05T18:28:23.408924+00:00 app[web.1]: ActiveRecord::AdapterNotSpecified: The `follower` database is not configured for the `beta` environment.
2019-07-05T18:28:23.408927+00:00 app[web.1]: 
2019-07-05T18:28:23.408929+00:00 app[web.1]: Available databases configurations are:
2019-07-05T18:28:23.408931+00:00 app[web.1]: 
2019-07-05T18:28:23.408933+00:00 app[web.1]: default
2019-07-05T18:28:23.408935+00:00 app[web.1]: development
2019-07-05T18:28:23.408938+00:00 app[web.1]: test
2019-07-05T18:28:23.408940+00:00 app[web.1]: beta
2019-07-05T18:28:23.408942+00:00 app[web.1]: production
2019-07-05T18:28:23.408944+00:00 app[web.1]: 
2019-07-05T18:28:23.408947+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:251:in `resolve_symbol_connection'
2019-07-05T18:28:23.408949+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:219:in `resolve_connection'
2019-07-05T18:28:23.408952+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_adapters/connection_specification.rb:140:in `resolve'
2019-07-05T18:28:23.408954+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:180:in `resolve_config_for_connection'
2019-07-05T18:28:23.408956+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:72:in `block in connects_to'
2019-07-05T18:28:23.408958+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:71:in `each'
2019-07-05T18:28:23.408960+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.6.0/bundler/gems/rails-a23128ad3e76/activerecord/lib/active_record/connection_handling.rb:71:in `connects_to'
2019-07-05T18:28:23.408963+00:00 app[web.1]:   /app/app/models/application_record.rb:3:in `<class:ApplicationRecord>'
2019-07-05T18:28:23.408965+00:00 app[web.1]:   /app/app/models/application_record.rb:1:in `<main>'
```

I suppose I can see if I can make a sample app, I'll get back to you soon

**Comment by sqlninja** [comment]
@eileencodes should any special go in the `puma.rb` to support the reader/writer setup?
Also same question for Sidekiq...

**Comment by eileencodes** [comment]
> should anything special go in the puma.rb to support the reader/writer setup?
Also same question for Sidekiq...

For puma, no, all my sample apps are using puma and the config didn't need changing. As for sidekiq, if this is a Rails bug, reproducing in an app without Sidekiq should be possible.

**Comment by eileencodes** [comment]
Hrm I just noticed there's something wrong with the output from your database's inability to connect.

In a test app I have I specifically entered a database that wasn't spelled right so I could reproduce the error.

The output looked like this:

```
/Users/eileencodes/open_source/real_rails/activerecord/lib/active_record/connection_adapters/connection_specification.rb:250:in `resolve_symbol_connection': The `primary_replica_wat` database is not configured for the `development` environment. (ActiveRecord::AdapterNotSpecified)

Available databases configurations are:

default
default_replica
development: primary, primary_replica, meals, meals_replica, desserts, desserts_replica
test: primary, primary_replica, meals, meals_replica, desserts, desserts_replica
production: primary, primary_replica, meals, meals_replica, desserts, desserts_replica
```

Your output doesn't look like that which makes me wonder if your indentation is off in the database config or you're not using Rails 6.0.0.rc1. It should look like:

```
ActiveRecord::AdapterNotSpecified: The `follower` database is not configured for the `beta` environment.

Available databases configurations are:

default
development: primary, follower
test: primary, follower
beta: primary: follower
production: primary, follower
```

**Comment by sqlninja** [comment]
Hmmm, could you share your database.yml file then, because mine is pasted in the original posting but it doesn’t really have much going on?

John Henderson

**Comment by sqlninja** [comment]
@eileencodes  Thought it might be worth posting the Gemfile.lock, from heroku, seems like it is indeed running rc1:
```
~ $ cat Gemfile.lock

GEM
  remote: https://rubygems.org/
  specs:
    ...
    
    activerecord (6.0.0.rc1)
      activemodel (= 6.0.0.rc1)
      activesupport (= 6.0.0.rc1)
    
    ...
    
    
    pg (1.1.4)
    
    ...
    
    puma (3.12.1)

    ...
    
    rack (2.0.7)

    ...
    
    rails (6.0.0.rc1)
      actioncable (= 6.0.0.rc1)
      actionmailbox (= 6.0.0.rc1)
      actionmailer (= 6.0.0.rc1)
      actionpack (= 6.0.0.rc1)
      actiontext (= 6.0.0.rc1)
      actionview (= 6.0.0.rc1)
      activejob (= 6.0.0.rc1)
      activemodel (= 6.0.0.rc1)
      activerecord (= 6.0.0.rc1)
      activestorage (= 6.0.0.rc1)
      activesupport (= 6.0.0.rc1)
      bundler (>= 1.3.0)
      railties (= 6.0.0.rc1)
      sprockets-rails (>= 2.0.0)

    ...

PLATFORMS
  ruby

...

RUBY VERSION
   ruby 2.6.3p62

BUNDLED WITH
   1.17.3
```

And best I can tell there are no indentation issues on the database.yml as it now looks like this: https://github.com/rails/rails/issues/36595#issuecomment-508831540

So I'm not sure what else would be the issue here...

**Comment by sqlninja** [comment]
FWIW: I am having issues locally when using `gem 'rails', '~> 6.0.0.rc1'` in my gemfile.
I get the following error: 

> ActiveRecord::ConnectionNotEstablished (No connection pool with 'primary' found for the 'reading' role.):

Although, if I change my gemfile to: `gem 'rails', git: 'https://github.com/rails/rails.git', branch: '6-0-stable'` that error goes away...

Still doesn't solve my problem on Heroku though...

**Comment by eileencodes** [comment]
Does it work in dev and test?

**Comment by sqlninja** [comment]
I’ve started getting the error locally as well. I’m going to have to disable the multi-db code and revert my database.yml so I can get staging functional again.

I think I may pulls the rails repo down to local machine so I can debug into it...

John Henderson

**Comment by eileencodes** [comment]
I'm not really sure how to help. I can't reproduce this so please provide a sample app that reproduces the error so that I can debug further. Thanks!

**Comment by sqlninja** [comment]
Thanks, I’m also going to do some testing on a fresh Rails 6 app to see what happens there.

John Henderson

**Comment by Smcchoi** [comment]
I have the same problem, but I noticed don't have both configs: 

```
ActiveRecord::Base.configurations.configs_for(env_name: "development")
=> [#<ActiveRecord::DatabaseConfigurations::HashConfig:0x00007f8e37893ad8 @env_name="development", @spec_name="write", @config={"adapter"=>"postgis", "pool"=>5, "timeout"=>5000, "schema_search_path"=>"public", "database"=>"db"}>
```
but
```
YAML::load(File.open('config/database.yml'))["development"]
``` 
has 2 objects as expected so I know my yaml is not off

**Comment by eileencodes** [comment]
I can’t reproduce based off the information provided in this report.

Please provide a sample app that reproduces the bug. Thanks!

**Comment by Smcchoi** [comment]
@eileencodes I invited you to a sample app, sorry I didn't have time to create an app that's completely separate, but it has that same issue on heroku. I was able to get the error to not show up locally on rails6-0 stable.

**Comment by eileencodes** [comment]
Thanks for the sample app!

>  I was able to get the error to not show up locally on rails 6-0 stable.

So this is fixed on 6-0-stable?

**Comment by Smcchoi** [comment]
locally but still does the same thing when I push it to heroku, I am not certain what is different. 

Also the configs still doesn't show correctly locally, and I was only able to connect to the second db if I specify it, the connect switching was weird.

**Comment by eileencodes** [comment]
Hrm I can't seem to get your app running - I think my version of postgres isn't new enough and I can't upgrade right now. If this is only happening on Heroku that's going to be pretty difficult for me to reproduce. I'm really not sure what to do next if it can't be reproduced without Heroku.

**Comment by Smcchoi** [comment]
okay which version of pg are you running? I'll just to make a different sample app over the weekend.

**Comment by eileencodes** [comment]
I'm running 9.6

**Comment by wjessop** [comment]
It took a while but I managed to replicate the `ActiveRecord::Base.configurations.configs_for(env_name: "development")` divergence locally. It's fixed by this commit:

```
commit f2ad69fe7a605b01bb7c37eeac6a9b4e7deb488e
Author: eileencodes <eileencodes@gmail.com>
Date:   Thu Jun 27 12:56:30 2019 -0400

   Fix broken url configs

   This PR is to fix #36559 but I also found other issues that haven't been
   reported.

   The check for `(config.size == 1 && config.values.all? { |v| v.is_a?
   String })` was naive. The only reason this passed was because we had
   tests that had single hash size configs, but that doesn't mean we don't
   want to create a hash config in other cases. So this now checks for
   `config["database"] || config["adapter"] || ENV["DATABASE_URL"]`. In the
   end for url configs we still get a UrlConfig but we need to pass through
   the HashConfig to create the right kind of UrlConfig. The UrlConfig's
   are really complex and I don't necessarily understand everything that's
   needed in order to act the same as Rails 5.2.

   I edited the connection handler test to demonstrate how the previous
   implementation was broken when checking config size. Now old and new
   tests pass so I think this is closer to 5.2.

   Fixes #36559

.../lib/active_record/database_configurations.rb   |  2 +-
.../connection_adapters/connection_handler_test.rb |  2 +-
.../merge_and_resolve_default_url_config_test.rb   | 31 ++++++++++++++++++++++
```

You might want to stick with -stable until a release gets cut with this change.

**Comment by eileencodes** [comment]
Ok sounds like this is fixed in 6-0-stable. We're releasing an RC2 next week (hopefully) so this will be fixed in the release as well. Thanks for the investigation @wjessop 😄

**Comment by eileencodes** [comment]
I think this is the [bug](https://github.com/rails/rails/issues/36736) you both were facing. I'm going to leave this closed since the new bug report has a reproduction. Please follow along on the new issue if you want to know when it's fixed.

**Comment by eileencodes** [comment]
This should be fixed in the next release by https://github.com/rails/rails/pull/36756
