### ISSUE TITLE
`db:seed` fails to use the correct database for multi-db models

### ISSUE THREAD

**Issue by dpogue** [rails/rails#36817]
### Steps to reproduce

Clone the example repo at https://github.com/dpogue/rails6_multidb_seed_bug
Run `bin/rails db:create && bin/rails db:migrate && bin/rails db:seed`

### Expected behavior

`db:seed` should create 2 entries in the users table (in the users database) and 1 entry in the things table (in the primary database)

### Actual behavior

An exception is thrown, trying to find a table in the wrong database:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'testapp_users_development.things' doesn't exist
```

### System configuration
**Rails version**: 6.0.0.rc2

**Ruby version**: 2.6.3

**Comment by eileencodes** [comment]
Thanks @dpogue I will get this fixed up soon 👍

**Comment by eileencodes** [comment]
I've fixed this for the primary database. It looks `db:seed` was never implemented for multiple databases. We'll work on that but it likely won't make it into 6.0 and will be for 6.1.

**Comment by chengwang-cc** [comment]
@eileencodes need your help
when can this issue be fixed? it still exists in 6.1.4.4

**Comment by eileencodes** [comment]
@chengwang-cc You can call any of the models in `seeds.rb` and the correct connection will be used for each. If you're using sharding, you can use `connected_to` to switch the shard.

Is the issue that you want to be able to have 1 seed file per database and be able to run those individually? Or is there something else that's not working. If there's a bug please open a new issue with an application or script that reproduces the bug.

**Comment by brendon** [comment]
@eileencodes, was this ever taken any further? After much hunting and reading the source code I think there's still only the capability to run one seed process across all databases at one time?

In my test suite I only need to seed a secondary databases tables and I wondered if I could configure that seed file location under the `database.yml` config for that database.

It's no great issue if this isn't a thing as I can just move this code to the main `seeds.rb` which is currently empty.
