### ISSUE TITLE
Rails 6 on create new app error occur no implicit conversion of String into Integer (TypeError)

### ISSUE THREAD

**Issue by ashutoshpith** [rails/rails#36970]
After create rails new app with below config the app doesn't process webpacker:install it follow with this error
no implicit conversion of String into Integer (TypeError)  

### System configuration
**Rails version**:
* 6.0.0

**Ruby version**:
* 2.7.0-preview1

**Platform os**
* Linux ubuntu 19.04

**Comment by ezii123** [comment]
Got the same

```
         run  bundle exec spring binstub --all
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
* bin/rake: Spring inserted
* bin/rails: Spring inserted
       rails  webpacker:install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Traceback (most recent call last):
	36: from bin/rails:3:in `<main>'
	35: from bin/rails:3:in `load'
	34: from /Users/lemonandroid/Documents/banal-todo-1/bin/spring:15:in `<top (required)>'
	33: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	32: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	31: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	30: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	29: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	28: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	27: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	26: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	25: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	24: from /Users/lemonandroid/Documents/banal-todo-1/bin/rails:8:in `<top (required)>'
	23: from /Users/lemonandroid/Documents/banal-todo-1/bin/rails:8:in `require_relative'
	22: from /Users/lemonandroid/Documents/banal-todo-1/config/boot.rb:4:in `<top (required)>'
	21: from /Users/lemonandroid/Documents/banal-todo-1/config/boot.rb:4:in `require'
	20: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/setup.rb:30:in `<top (required)>'
	19: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap.rb:30:in `setup'
	18: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache.rb:9:in `setup'
	17: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	16: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	15: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
	14: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
	13: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	12: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	11: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	10: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 9: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 8: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/compile_cache/iseq.rb:1:in `<top (required)>'
	 7: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
	 6: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
	 5: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
	 4: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	 3: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	 2: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 1: from /Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/lemonandroid/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': no implicit conversion of String into Integer (TypeError)
```

**Comment by ashutoshpith** [comment]
I think issue is only with ruby version 2.7.0-preview1 .Rails version 6 is work fine with ruby version 2.6.2+.

**Comment by ezii123** [comment]
ok, thanks

**Comment by eugeneius** [comment]
This error is caused by an incompatibility between the bootsnap gem and [this change](https://github.com/ruby/ruby/commit/5da52d1210625fb00acd573b3f32281b4bde1730) in Ruby 2.7, which was fixed in https://github.com/Shopify/bootsnap/pull/267.

It hasn't been published yet, but removing the bootsnap gem or using the master branch are both viable workarounds. I expect a new version of bootsnap will be published before 2.7.0 is released.

**Comment by rmacklin** [comment]
For anyone else who ends up at this issue and is not using ruby 2.7 - don't be deterred. There was a _separate_ issue in bootsnap that was independent of the ruby version which would lead to this error - it was fixed here: https://github.com/Shopify/bootsnap/pull/199 (available in bootsnap >= 1.3.2)

**Comment by ezra40b** [comment]
I seem to be having a similar problem with 500 errors on any controller, saying 
`no implicit conversion of Symbol to Integer`
The application trace is blank, or is an empty array, so I'm pretty sure it isn't a problem on my end. I'm using Ruby 2.7.0 but the problem is still there on 2.6.5 and 2.6.2, and removing and reinstalling bootsnap did nothing. Webpacker is still working.

**Comment by iamcristos** [comment]
Hello I'm still getting this error currently using ruby 2.7.1

**Comment by jameshibbard** [comment]
Updating bootsnap to the latest version (1.4.6) fixed it for me: `bundle update bootsnap`

**Comment by patsch** [comment]
I am using Bootsnap 1.4.6 and Ruby 2.7.1 and am experiencing the same issue. On startup of the app:

`/www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:45:in `accumulate_descendants': no implicit conversion of Hash into Integer (TypeError)
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:48:in `block in accumulate_descendants'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:86:in `block in each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:85:in `each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:85:in `each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:46:in `accumulate_descendants'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:48:in `block in accumulate_descendants'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:86:in `block in each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:85:in `each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:85:in `each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:46:in `accumulate_descendants'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:19:in `descendants'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/descendants_tracker.rb:64:in `descendants'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activerecord-6.0.3/lib/active_record/railtie.rb:151:in `block (3 levels) in <class:Railtie>'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activerecord-6.0.3/lib/active_record/railtie.rb:149:in `block (2 levels) in <class:Railtie>'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application/finisher.rb:129:in `block in <module:Finisher>'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `run'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `call'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	from /home/railsuser/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application.rb:363:in `initialize!'
	from /www/live.myapp.org/prod/rails/releases/20200609075013/config/environment.rb:5:in `<main>'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/application.rb:339:in `require_environment!'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/command/actions.rb:28:in `require_environment!'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/commands/console/console_command.rb:101:in `perform'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/command/base.rb:69:in `perform'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/command.rb:46:in `invoke'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/railties-6.0.3/lib/rails/commands.rb:18:in `<main>'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /www/live.myapp.org/prod/rails/shared/bundle/ruby/2.7.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
	from bin/rails:9:in `<main>'`

**Comment by Martfed** [comment]
> Updating bootsnap to the latest version (1.4.6) fixed it for me: `bundle update bootsnap`

Thank you! worked for me as well
