### ISSUE TITLE
Rails 6 / Ruby 2.6.4 - ActiveSupport's `#include?` extensions break with endless ranges

### ISSUE THREAD

**Issue by pond** [rails/rails#37172]
I originally thought this was a core Ruby bug and [submitted it](https://bugs.ruby-lang.org/issues/16165) but turns out it's from the [ActiveSupport extensions](https://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-range).

### Steps to reproduce

* Create any new Rails 6 project
* `bundle exec rails c` to access console
* Execute statement `(1..).include?(4)`

### Expected behavior

* Core Ruby will evaluate the statement to `true`, which is the expected outcome; you can try that in vanilla `irb`.

### Actual behavior

* The statement leads to the exception `RangeError (cannot get the last element of endless range)` being raised.
* Note that `#cover?` is _not_ misbehaving in this way, and can be used instead of `#include?` as a work-around.

### System configuration

**Rails version**: 6.0.0
**Ruby version**: 2.6.4

**Comment by y-yagi** [comment]
This already fixed by #36460. Please wait for next release of Rails. Thanks.

**Comment by pond** [comment]
Ah cool, thanks. I think I might've only searched open issues, so I didn't spot the recently-closed https://github.com/rails/rails/issues/36451.

**Comment by pond** [comment]
Wait a mo - #36451 does not fix this issue, at least only a small subset. In particular, it doesn't handle include or cover on a range itself. The PR above talks about not calling "last" but regrettably is not very thorough and does not check other parts of the ActiveSupport range extensions, which use "last" in a few places. Those all need fixing, so even though `.include?(<integer>)` is fine, range inclusions or cover checks are not. With #36451 applied:

```
$ irb
irb(main):001:0> (1..).cover?(2..3)
=> true
irb(main):002:0> (1..).include?(2..3)
=> false

$ bundle exec rails c
Loading development environment (Rails 6.0.0)
irb(main):001:0> (1..).cover?(2..3)
Traceback (most recent call last):
        1: from (irb):1
RangeError (cannot get the last element of endless range)
irb(main):002:0> (1..).include?(2..3)
Traceback (most recent call last):
        2: from (irb):2
        1: from (irb):2:in `rescue in irb_binding'
RangeError (cannot get the last element of endless range)
```

Please re-open this and I'll see if I can get a patch together.

**Comment by pond** [comment]
Followed up via https://github.com/rails/rails/issues/37177 and a patch is coming now.
