### ISSUE TITLE
Bundle Update Fails for Rails 6.1 if Ruby >= 2.6

### ISSUE THREAD

**Issue by cpruitt** [rails/rails#37224]
**NOTE:** This is in reference to running `bundle update` in a checked out copy of Rails 6.1 (master). This does not apply to updating gems for an app that **uses** Rails 6.1

## Applies to:

* Current Rails 6.1 `master`
* Any Ruby version `>= 2.6.0`
* Tested on MacOS / Darwin (I assume all systems are affected)

## Steps to Reproduce

Using any version of Ruby `>= 2.6.0`:

* Check out a copy of Rails `master`
* Run `bundle install` which will work
* Run `bundle update` which will fail

``` bash
git clone 'https://github.com/rails/rails/' ./tmprails
cd ./tmprails

# This will work OK
bundle install

# This will fail
bundle update
```

## Expected Behavior

Bundler will update dependencies.

## Actual Behavior

Bundler fails with:

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    mysql2 (~> 0.5) was resolved to 0.5.2, which depends on
      ruby (< 2.6) x64-mingw32

    mysql2 (~> 0.5) was resolved to 0.5.2, which depends on
      ruby (< 2.6) x86-mingw32

    nokogiri (>= 1.8.1) was resolved to 1.10.4, which depends on
      ruby (>= 2.3) x64-mingw32

    nokogiri (>= 1.8.1) was resolved to 1.10.4, which depends on
      ruby (>= 2.3) x86-mingw32

    rails was resolved to 6.1.0.alpha, which depends on
      ruby (>= 2.5.0)
```

## Details. A problem with `mysql2` version `0.5`

This appears to have been introduced in https://github.com/rails/rails/pull/37191 where we bumped `mysql2` to version `0.5`. The Windows binaries for `mysql2` versions `>= 0.5` have a Ruby version requirement of `< 2.6, >= 2.0` (e.g. https://rubygems.org/gems/mysql2/versions/0.5.0-x86-mingw32). This Ruby requirement is imposed on all platforms such that even non-windows systems can not update unless using `ruby (< 2.6)`.

_`mysql2` versions earlier than `0.5` had a Ruby requirement of `>= 0`._

## Related Background:

At GitHub, this is currently blocking us from testing with Rails 6.1. Our process for vendoring Rails began failing for our "Rails Next" update after the https://github.com/rails/rails/pull/37191 PR. This is because our process includes a `bundle install` step that happens in such a way as to cause dependencies on all platforms to be re-checked in the same way that `bundle update` does.

**As a side note:** I'm not entirely sure whether this is a Rails issue, a MySQL2 issue, or a bundler issue. I'm opening this as a first step to figuring that out.

CC: @kamipo as author of the PR mentioned above, @eileencodes for visibility

**Comment by cpruitt** [comment]
Update: @eileencodes pointed out https://github.com/brianmario/mysql2/issues/1064 which looks to be related.

**Comment by yahonda** [comment]
This is a Bundler issue. It should be addressed by updating bundler `gem install bundler --pre`.

**Comment by eileencodes** [comment]
Problem is we can’t upgrade bundler to a pre version because we vendor bundler. We’re not able to keep upgrading bundler every couple of weeks.

**Comment by kamipo** [comment]
I found the need #37191 from CI failure https://buildkite.com/rails/rails/builds/63617#3c3f9954-8199-44a8-adfa-0c6ac2e705f1/6-55.

If we hit the bundler bug, mysql2 gem might be installed as 0.4.10, then AR would raise "NameError: uninitialized constant Mysql2::Error::TimeoutError".

**Comment by yahonda** [comment]
Bundler 2.1.0.pre2 has been included to Ruby itself https://github.com/ruby/ruby/commit/1cb8cf5df0b2a7dbf8b1d616ac5268d76140aab6

Also, I have confirmed this error has been addressed at Rails CI https://buildkite.com/rails/rails/builds/63747#c25af0c3-09e6-4a7d-833b-315874162724

**Comment by cpruitt** [comment]
I'm still looking for ways to work around this but felt it was worth mentioning that I am still unable to `bundle update` with 2.1.0.pre1 or .pre2. I'm not ruling out that it's a mistake on my part but I'd be interested in knowing if anyone else has been able to update with these bundler versions.

```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
$ bundle -v
Bundler version 2.1.0.pre.2
$ bundle update
[DEPRECATED] Pass --all to `bundle update` to update everything
Fetching https://github.com/QueueClassic/queue_classic.git
Fetching https://github.com/matthewd/websocket-client-simple.git
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby

    mysql2 (~> 0.5) was resolved to 0.5.2, which depends on
      Ruby (< 2.6) x64-mingw32

    mysql2 (~> 0.5) was resolved to 0.5.2, which depends on
      Ruby (< 2.6) x86-mingw32

    nokogiri (>= 1.8.1) was resolved to 1.10.4, which depends on
      Ruby (>= 2.3) x64-mingw32

    nokogiri (>= 1.8.1) was resolved to 1.10.4, which depends on
      Ruby (>= 2.3) x86-mingw32

    rails was resolved to 6.1.0.alpha, which depends on
      Ruby (>= 2.5.0)
```

**Comment by carrot555** [comment]
@sodabrew unfortunately does not have time to upgrade the mysql2 plug-in. We are waiting now almost a year for it.  Could Rails developers team pick this up? The plug-in actually important for Rails 6 and mysql compatibility. Many people are using mysql. It is actually baffling why such plugins are actually not part of Rails. Rails require databases to run. Mysql2 plug-in is actually dragging Rails back. The old plug-in also have problem with Mysql 8.0 “Mysql2::Error: Authentication", now days security is important with all new CVS and no one stays on top of it, as for example @sodabrew does not have time. Please think about it.

**Comment by yahonda** [comment]
I'm wondering if this is still an issue with mysql2 gem 0.4.6 which should have addressed https://github.com/brianmario/mysql2/issues/1021

**Comment by sodabrew** [comment]
Hey, no, I think this remains an open issue, regardless of whether I'm timely in releasing new Windows builds. The Windows Ruby dev toolkits traditionally have lagged months behind the Dec 25 new Ruby releases. Maybe lately that's improved, but I suggest to focus on the underlying problem here:

> This Ruby requirement is imposed on all platforms such that even non-windows systems can not update unless using ruby (< 2.6).

If I have a gem with a binary build for some platforms, that binary build will only be available for the Ruby platforms that were known at build time. Imposing the version requirement to other platforms doesn't make sense to me. I would solve this problem by halting Windows builds and telling Windows users that they're on their own to figure out how to compile the gem, right? So that way I'm only distributing the `ruby` architecture variant. If that's what it takes, but that'd be sad. About five year sago, I spent over a year deeply figuring this out for myself and getting working builds for Windows for mysql2 and eventmachine, and that's on top of the incredible work of folks like @kou, @larskanis, @MSP-Greg creating Rake Compiler and Ruby Installer. But maybe the build-at-installation capability for Windows is commonplace now? Traditionally Windows systems do not have compilers widely available.

I propose as an acid test: if I get a request on December 25 that I've broken mysql2 installation for Ruby 2.7 users on platforms other than Windows, that we're doing something wrong by default.

**Comment by MSP-Greg** [comment]
@sodabrew (thanks for the ping, hadn't seen this)

> But maybe the build-at-installation capability for Windows is commonplace now?

A qualified yes, for Ruby 2.4 and later...  Ruby versions 2.3 and earlier used a custom packaged MSYS system for DevKit, Ruby versions 2.4 an later use a standard MSYS2 install for DevKit.  There can be issues when a library in MSYS2 is a later version than Ruby was built with (e.g. OpenSSL).

Anyway, as one who does 90% of my work with gem repos using Ruby master, if Bundler would resolve to a '--platform=ruby' gem if the platform specific (pre-compiled) gem didn't meet Ruby version requirements, that would solve a lot of problems.  Last I checked, it did not do that, it just stops...

**Comment by kou** [comment]
Ruby 2.3 reaches EOL. So we don't need to care about it.

I recommend build-at-installation approach. No  "*-mingw32" gems.

Let's report the `--platform=ruby` problem to Bundler and solve it. Then we don't need "*-mingw" gems. We don't need to wait for releasing gems for new Ruby by gem maintainers.

**Comment by larskanis** [comment]
It's new that "platform=ruby" is also affected, but non-ruby platform support in the resolver of bundler did never really work. I discussed this two years ago in https://github.com/bundler/bundler/pull/6247 and it has been accepted as a bug, but hasn't been fixed so far.

Given that mysql2 installs out of the box on RubyInstaller with `--platform ruby`, it's indeed questionable whether the `mysql2-*-mingw32` gems should be published any longer. Unfortunately this would probably push the issue further to other gems like `pg` and `ffi`, which I currently don't want to publish as "platform=ruby"-only gems.

**Comment by kou** [comment]
rubygems/bundler#6247 has been fixed by rubygems/bundler#7522.
Bundler 2.2.0 will fix this.
