### ISSUE TITLE
Debug page in development w/ ActiveStorage disabled

### ISSUE THREAD

**Issue by keeguon** [rails/rails#38196]
### Steps to reproduce

First of all this is a development related problem only.

Whenever a SQL request fails (like say using `where` on a column which doesn't exists) in a controller and with ActiveStorage disabled, either manually by commenting out `require active_storage/engine` in `application.rb` and removing the config lines in the environments file or starting a new application with the `--skip-active-storage` option, the debug page with the application trace and framework trace doesn't show up and the default 500.html page is displayed instead.

### Expected behavior

The debug page with the application trace and framework trace should show up in development.

### Actual behavior

The default 500.html page appears instead.

### System configuration
**Rails version**: 5.2+

**Ruby version**: 2.5+

**Comment by gmcgibbon** [comment]
I'm unable to reproduce the issue. Can you provide a sample application that demonstrates the problem? Also double checked your environment to make sure the app isn't booting in an unexpected mode (via `RACK_ENV` or `RAILS_ENV`).

**Comment by keeguon** [comment]
@gmcgibbon did a sample app here : https://github.com/keeguon/weblog, as you can see in `config/application.rb`, ActiveStorage is disabled, generated a very simple "Article" resource (see migrations) and in the controller deliberately wrote a SQL request supposed to fail. When I start the rails server (with `bundle exec rails s`) and I go to the resource the default 500 page is displayed. If I re-enable ActiveStorage I have the debug page showing the SQL error.

**Comment by gmcgibbon** [comment]
Ah, I see it now. The problem is the exception debugging template for `ActiveRecord::StatementInvalid` referenced `ActiveStorage`, which is fixed in Rails 6 by https://github.com/rails/rails/pull/35139. Please upgrade to see this issue resolved. Thanks!

**Comment by keeguon** [comment]
@gmcgibbon thanks we'll do for the Rails 6 apps we have but we still have a bunch of Rails 5 apps, if it could be backported somehow in a future release that would be great !

**Comment by gmcgibbon** [comment]
Unfortunately, we don't backport bug fixes to Rails 5 anymore (see [maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html)). You'll have to upgrade to Rails 6. Sorry for the inconvenience!
