### ISSUE TITLE
Migration on Mariadb: text column default value reads back with extra quotes

### ISSUE THREAD

**Issue by msg7086** [rails/rails#38218]
### Steps to reproduce
With MariaDB / possibly also MySQL, text column with a default value is not recorded properly into schema.rb. Instead of empty string, it reads back as a pair of quotes.

```
create_table do |t|
      t.text :content, null: false, default: ''
end
```

### Expected behavior

In schema.rb

```
t.text "content", default: "", null: false
```

### Actual behavior

```
t.text "content", default: "''", null: false
```

### System configuration
**Rails version**: 5.2.4.1

**Ruby version**: 2.5.5p157 (2019-03-15 revision 67260)

MariaDB: 10.3.18-MariaDB-0+deb10u1

---

I'm not even sure if this has been reported before, since it seems to be easy to hit. The table is created properly, but somehow read back is incorrect.

```
CREATE TABLE ... ( `content` text DEFAULT '' NOT NULL )

+-------------+---------------+------+-----+---------+----------------+ 
| Field       | Type          | Null | Key | Default | Extra          |
+-------------+---------------+------+-----+---------+----------------+        
| content     | text          | NO   |     | ''      |                |
+-------------+---------------+------+-----+---------+----------------+
```

And inserting a record indeed gives me empty string, instead of a pair of quotes.

I found this issue because when I create a model I get a pair of quotes in the content field by default.

I only tested against Debian MariaDB. Possibly affecting MySQL also.

**Comment by Morozzzko** [comment]
Can confirm: I can totally reproduce it and wasted quite a lot of time thinking there's something wrong with MariaDB.

Here's a little more info on how it behaves:

1. When I create a record, the field reader returns `"''"`
2. When I run a `select` manually via SQL, I get an empty string. No extra quotes
3. When I run `#reload` on the created record, the field reader returns an empty string. No extra quotes

**Comment by p8** [comment]
@msg7086 Could you add a bug report template to reproduce the error?
https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb

**Comment by telyn** [comment]
I'm having the same issue on Rails 6, too. Here's an executable test case

```ruby
# This bug occurs at least with MariaDB 10.3, and Rails 5.2 and 6.0
# I've never made a bug report for rails before - and the documentation doesn't
# say what to do re: setting up the adaptor for a mysql-specific issue. So I've left
# everything apart from "adapter" blank - I'm assuming ENV["DATABASE_URL"]
# will work to let you specify the connection details.

# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "mysql2",
                                        database: "test",
                                        username: "root")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :body, null: false, default: ""
  end
end

class Post < ActiveRecord::Base; end

class BugTest < Minitest::Test
  def test_default_reads_correctly
    post = Post.create!

    assert_equal "", post.body
  end
end
```

**Comment by msg7086** [comment]
Thanks, telyn. I've been involved and can't spend time working on a test case.

**Comment by wkechel** [comment]
I observe the same behaviour for rails 6 with fields of type json.

**Comment by telyn** [comment]
Confirmed - this bug still occurs on `6-1-stable` and on the `main` branch. Attached is the modified executable test - which uses docker to boot a mariadb container, if docker exists.

```
# This bug occurs at least with MariaDB 10.3, and Rails 5.2 and 6.0
# The documentation doesn't say what to do re: setting up the adaptor for a
# mysql-specific issue, so I've written it to detect if docker is available and
# run a mariadb 10.3 container (and delete it afterwards) - and if not, use
# ENV["DATABASE_URL"] to specify the connection details.

BRANCH = ENV["RAILS_BRANCH"] || "main"

class MariaDBContainer
  class << self
    def mysql_port
      @mysql_port ||= rand(16_384..65_535)
    end

    def should_start?
      return if ENV["DATABASE_URL"]

      system("docker ps > /dev/null")
      unless $?.success?
        puts "Couldn't connect to docker. Using empty connection details for " \
             "mariadb (will most likely attempt local mysql socket)"
        return false
      end

      true
    end

    def start
      return unless should_start?

      image = "mariadb:10.3"
      system("docker pull #{image}")
      puts "Starting mariadb on port #{mysql_port}"
      command = "docker run --rm " \
        "--name \"rails-38218-port-#{mysql_port}\" " \
        "-e MYSQL_ALLOW_EMPTY_PASSWORD=yes " \
        "-e MYSQL_DATABASE=test " \
        "-d -p #{mysql_port}:3306 #{image}"
      @mariadb_container_id = `#{command}`
      if $?.success?
        puts "Started container #{@mariadb_container_id}"
      else
        puts "couldn't start container"
        exit 1
      end
      fork { exec("docker logs -f #{@mariadb_container_id}") }
    end

    def running?
      @mariadb_container_id
    end

    def stop
      return unless running?

      puts "Stopping mariadb container.."
      # container was booted with --rm, so no rm needed
      system("docker stop #{@mariadb_container_id}")

      if $?.success?
        puts "Stopped and deleted database container"
      else
        puts "Failed to stop and delete container - check the " \
          "container #{@mariadb_container_id} isn't still running"
      end
    end

    def connection_params
      connection_params = { adapter: "mysql2" }

      if running?
        connection_params.merge!(host: "127.0.0.1",
                                 database: "test",
                                 port: mysql_port,
                                 username: "root")
      end
    end
  end
end

MariaDBContainer.start

begin
  # give the container some time to boot
  sleep 15 if MariaDBContainer.running?

  require "bundler/inline"

  gemfile(true) do
    source "https://rubygems.org"

    git_source(:github) { |repo| "https://github.com/#{repo}.git" }

    gem "activerecord", github: "rails/rails", branch: ::BRANCH
    gem "mysql2"
  end

  require "active_record"
  require "minitest/autorun"
  require "logger"

  ActiveRecord::Base.establish_connection(MariaDBContainer.connection_params)
  ActiveRecord::Base.logger = Logger.new(STDOUT)

  ActiveRecord::Schema.define do
    create_table :posts, force: true do |t|
      t.text :body, null: false, default: ""
    end
  end
rescue StandardError, Interrupt
  MariaDBContainer.stop
end

class Post < ActiveRecord::Base; end

class BugTest < Minitest::Unit
  def test_default_reads_correctly
    post = Post.create!

    # "" is what we want, but "''" is what we get
    assert_equal "", post.body
  ensure
    MariaDBContainer.stop
  end
end
```

**Comment by intrip** [comment]
I do confirm this issue is only for `MariaDB`

MariaDB returns the default text values wrapped in `''` but it doesn't wrap default values in `''` for `varchar`.

```sql
MariaDB [test1]> show columns from posts;
+-------+--------------+------+-----+---------+----------------+
| Field | Type         | Null | Key | Default | Extra          |
+-------+--------------+------+-----+---------+----------------+
| id    | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| body  | text         | NO   |     | ''      |                |
| name  | varchar(255) | NO   |     |         |                |
+-------+--------------+------+-----+---------+----------------+
```

I'll write a PR to deal with this behaviour. /cc @kamipo

**Comment by intrip** [comment]
I've just found that https://github.com/rails/rails/pull/40822 should fix this.

**Comment by telyn** [comment]
Still able to reproduce on 6-1-stable and main using the script from [my earlier comment](https://github.com/rails/rails/issues/38218#issuecomment-801912387), I'm afraid.

I've made some changes to the script in that post to support changing repos, and using @fatkodima's change from #40822 does fix the issue :-)

```console
Lonsdaelite ~ » RAILS_REPO=rails/rails RAILS_BRANCH=main ruby rails-test.rb 2>&1 | tail -n 1 
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
Lonsdaelite ~ » RAILS_REPO=fatkodima/rails RAILS_BRANCH=fix-mysql-column-default ruby rails-test.rb 2>&1 | tail -n 1 
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by chrise86** [comment]
This is also still an issue for me, but it seems @fatkodima 's branch has been removed.

**Comment by telyn** [comment]
> This is also still an issue for me, but it seems @fatkodima 's branch has been removed.

It was merged into rails edge: https://github.com/rails/rails/pull/40822

Searching for the commit message seems to imply that that's all it's been merged into, so far.
