### ISSUE TITLE
Deprecation errors with Ruby 2.7.0 and rails 6.0.2.1

### ISSUE THREAD

**Issue by jasonnoble** [rails/rails#38245]
### Steps to reproduce
```
$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
$ rails -v
Rails 6.0.2.1
$ rails new test_app
[...]
      append  .gitignore
/Users/jasonn/.rvm/gems/ruby-2.7.0@rails6/gems/activesupport-6.0.2.1/lib/active_support/message_encryptor.rb:175: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/jasonn/.rvm/gems/ruby-2.7.0@rails6/gems/activesupport-6.0.2.1/lib/active_support/messages/metadata.rb:17: warning: The called method `wrap' is defined here
      create  config/boot.rb
[...]
$ cd test_app
$ rails s
=> Booting Puma
=> Rails 6.0.2.1 application starting in development
=> Run `rails server --help` for more startup options
/Users/jasonn/.rvm/gems/ruby-2.7.0@rails6/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/jasonn/.rvm/gems/ruby-2.7.0@rails6/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
Puma starting in single mode...
* Version 4.3.1 (ruby 2.7.0-p0), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
Use Ctrl-C to stop
```

### Expected behavior
No deprecation errors

### Actual behavior
I see deprecation errors. Note, the last argument as keyword parameters is scheduled to be [removed in Ruby 3](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/)

### System configuration
**Rails version**: `6.0.2.1`

**Ruby version**: `2.7.0`

**Comment by rafaelfranca** [comment]
Thank you for the issue but this is already fixed.

**Comment by jasonnoble** [comment]
Looks like it was fixed via #37935.  Thx.

**Comment by guss77** [comment]
I still get deprecation warnings with release 6.0.2.2 (the latest release as of March 2020) and Ruby 2.7:

```
/home/guss77/.gem/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/associations.rb:1860: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/guss77/.gem/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/associations.rb:1370: warning: The called method `has_many' is defined here
/home/guss77/.gem/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/mysql/database_statements.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/guss77/.gem/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:96: warning: The called method `select_all' is defined here
/home/guss77/.gem/ruby/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/guss77/.gem/ruby/2.7.0/gems/activemodel-6.0.2.2/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here
```

Wasn't this supposed to be fixed already?

**Comment by breisig** [comment]
Can we get a 6.0.2.3 release to get rid of the Ruby 2.7 warnings?

**Comment by sergey-alekseev** [comment]
Rails 6.0.3 has been [released](https://weblog.rubyonrails.org/2020/5/6/Rails-6-0-3-has-been-released/) :tada:  

---
To @breisig and everyone else who is subscribed and waiting.

**Comment by Tshamp7** [comment]
Im still having this issue with Rails 6.0.3 and Ruby 2.7.1

**Comment by tlowrimore** [comment]
Perhaps I've done something wrong, but I'm still seeing these warnings in 6.0.3.2 with Ruby 2.7.1.  See below:

```
/home/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.2/lib/action_dispatch/testing/integration.rb:211: warning: The called method `process' is defined here
/home/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.2/lib/action_dispatch/testing/integration.rb:418: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

**Comment by kamipo** [comment]
Actually this is an issue of the caller side for `method_missing`.

https://github.com/rails/rails/blob/fbe2433be6e052a1acac63c7faf287c52ed3c5ba/actionpack/lib/action_dispatch/testing/integration.rb#L416-L425

Can you find the caller for `method_missing` by using `warning` gem with `Warning.process('', keyword_separation: :raise)`?

https://discuss.rubyonrails.org/t/new-2-7-3-0-keyword-argument-pain-point/74980/45

**Comment by tlowrimore** [comment]
@kamipo Thank you very much for the quick response!  Your hint helped me track this down to my use of an older version of the `rails-controller-testing` gem.  After updating, all was fine.

I apologize for the false alarm!
