### ISSUE TITLE
Rails 6 return 500 error without information in production

### ISSUE THREAD

**Issue by mm580486** [rails/rails#39008]
hi
in my server i get 500 error in production , i checked production.log but i have only one error without information 
```

I, [2020-04-21T16:05:31.764482 #1]  INFO -- : [02340258-b640-43e6-811b-18b76867f8ad] Processing by SessionsController#login as HTML
I, [2020-04-21T16:05:31.766391 #1]  INFO -- : [02340258-b640-43e6-811b-18b76867f8ad]   Rendering sessions/login.html.erb within layouts/application
I, [2020-04-21T16:05:31.768061 #1]  INFO -- : [02340258-b640-43e6-811b-18b76867f8ad]   Rendered sessions/login.html.erb within layouts/application (Duration: 1.5ms | Allocations: 309)
I, [2020-04-21T16:05:31.791413 #1]  INFO -- : [02340258-b640-43e6-811b-18b76867f8ad] Completed 500 Internal Server Error in 27ms (ActiveRecord: 0.0ms | Allocations: 5899)

```

my login action has no action code only have one simple view file, every page in my development system works fine but i cant find real error 

also i change this conf in production env

```
config.consider_all_requests_local       = true
config.action_controller.perform_caching = false

```
but again not report full error in production.log

### System configuration
**Rails version**:
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
**Ruby version**:
ruby:2.6.1

**Comment by mm580486** [comment]
also i change this conf in production env 
  ```
config.consider_all_requests_local       = true
  config.action_controller.perform_caching = false

```
but again not report full error in production.log

**Comment by eileencodes** [comment]
This was fixed in https://github.com/rails/rails/issues/38222 and will be available in the next release.

**Comment by mm580486** [comment]
@eileencodes I changed app/assets/config/manifest.js to this code
but problem not solved 

```
// ldink_tree ../images
//= link_directory ../stylesheets .css
```

**Comment by eileencodes** [comment]
Sorry I linked to the wrong PR, this is the fix https://github.com/rails/rails/pull/38250.
