### ISSUE TITLE
Test failure: IO.console.winsize cannot be set with io-console 0.5.6

### ISSUE THREAD

**Issue by pvalena** [rails/rails#40020]
### Steps to reproduce
Run Test, without terminal: `rails test test/dispatch/routing/inspector_test.rb:319`

### Expected behavior
`IO.console.winsize = [0, 23]` shouldn't be set

### Actual behavior
```
Error:
ActionDispatch::Routing::RoutesInspectorTest#test_routes_when_expanded:
NoMethodError: undefined method `winsize=' for nil:NilClass
    test/dispatch/routing/inspector_test.rb:362:in `ensure in test_routes_when_expanded'
    test/dispatch/routing/inspector_test.rb:362:in `test_routes_when_expanded'

rails test test/dispatch/routing/inspector_test.rb:319
```
Test was executed like so in Fedora, while doing build checks:
```
ruby -Itest -- test/dispatch/routing/inspector_test.rb
```

### System configuration
**Rails version**: 6.0.3.1

**Ruby version**: 2.7.1

**Comment by KapilSachdev** [comment]
Can you append `bundle exec` before the command and verify if the `NoMethodError` exception is still raised

Running
```ruby
bundle exec ruby -Itest -- test/dispatch/routing/inspector_test.rb
```

in place of 
```ruby
ruby -Itest -- test/dispatch/routing/inspector_test.rb
```

Also what do you mean by `Run Test, without terminal` ?

**Comment by KapilSachdev** [comment]
Might have been fixed in #36937 (also helped me understand what you meant by `without terminal`).
Can you confirm by using `master` branch.

**Comment by jonathanhefner** [comment]
Yes, this was fixed by #36937.  Thank you for the report @pvalena, and thank you for looking in to it @KapilSachdev!

**Comment by pvalena** [comment]
@jonathanhefner one more issue persists, when I apply the patch:

```
# Running:

....................E

Error:
ActionDispatch::Routing::RoutesInspectorTest#test_routes_when_expanded:
ArgumentError: unknown keyword: :width
    /usr/share/gems/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/inspector.rb:131:in `initialize'
    test/dispatch/routing/inspector_test.rb:329:in `new'
    test/dispatch/routing/inspector_test.rb:329:in `test_routes_when_expanded'

rails test test/dispatch/routing/inspector_test.rb:319
```
Do I need 6.0.3.2 for that to work?

**Comment by KapilSachdev** [comment]
Actually thats why i initially asked you to use `bundle exec`.

**Comment by jonathanhefner** [comment]
@pvalena You need all of #36937, including [these lines](https://github.com/rails/rails/pull/36937/files#diff-60097f346084392ae09bff3e41506b68R203-R206).  You may also wish to pull in #38062.

> Do I need 6.0.3.2 for that to work?

#36937 was not a part of Rails 6.0.  It will be included in Rails 6.1.

**Comment by pvalena** [comment]
> Actually thats why i initially asked you to use `bundle exec`.

@KapilSachdev I'm not running it locally, for my convenience. In Fedora we actually [package](https://fedoraproject.org/wiki/Changes/Ruby_on_Rails_6.0) all those components and test them with each build (in our infrastracture, where network is not available). And `bundler` should (hopefully) make no difference. Currently I'm in middle of 6.0.3.1, but I can finish without this test passing.

_ _ _ _

@joankaradimov Yes, I've tried with the  [whole PR patch](https://github.com/rails/rails/pull/36937.patch) applied, but thinking about it the issue may be because this is the second phase of bootstrap, so the patched part of the code didin't get pulled in properly.
