### ISSUE TITLE
undefined method `attachment_reflections' for nil:NilClass when removing an entry with Active Storage with variants from console

### ISSUE THREAD

**Issue by juansecaro** [rails/rails#40962]
### Steps to reproduce
Building a scaffold with an Active Storage image and at least 1 variant in a view throw this error when destroy.

In console it happens everytime, in the browser I have this error 1 time but I haven't been able to reproduce.

All images are still found after destroy in the system

### Expected behavior
After detroy the image and its variants should be removed silently and without throwing any error.

### Actual behavior

An error is thrown and all the images are still in the folder storage

![rails_fails](https://user-images.githubusercontent.com/5209472/103245564-db4ee180-4960-11eb-85a9-9266e14f8085.png)
![rails_fails2](https://user-images.githubusercontent.com/5209472/103245566-ddb13b80-4960-11eb-8c0f-2fe9d37cf6b5.png)

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.2

**Comment by josh-m-sharpe** [comment]
FWIW (possibly not much), I just ran into this issue as well (amongst other odd behavior).  After digging around, I found this issue: https://github.com/rails/rails/issues/40986 which relates to UUID primary keys.  After I implemented the fix at the bottom of that issue *this/your* issue has gone away - along with all the other bad behavior.

Based on your example, It doesn't look like you're using UUID primary keys, so that may not be worth much, but who knows...?  Best of luck!

**Comment by josh-m-sharpe** [comment]
<img width="835" alt="undefined_method_`attachment_reflections__for_nil_NilClass_when_removing_an_entry_with_Active_Storage_with_variants_from_console_·_Issue__40962_·_rails_rails" src="https://user-images.githubusercontent.com/39473/103395255-5ba94a00-4afb-11eb-8282-c5b4a5564b66.png">

**Comment by filipjakubowski** [comment]
I had attachment_reflections errors for Nil class as well using rails 6.1. Error was not on deleting but processing variant. 

```
gem 'rails', '~> 6.1.0'
gem 'image_processing', '~> 1.2'
```
updating imagemagic solved problem (MAC) 
`brew upgrade imagemagick`

**Comment by juansecaro** [comment]
I have this version (1.2) of image_processing and the problem keep going. It looks like @josh-m-sharpe is right and it's related to having UUID as a primary id. It's good to know that not using UUID is a work around, but I wonder if there is an easy fix to this.

**Comment by Korkey128k** [comment]
I've fixed this with a migration to remove the `record_id` column from `active_storage_attachments` and add it back with the `:uuid` option. 
```ruby
class ChangeActiveStorageRecordReferencesToUuid < ActiveRecord::Migration[6.1]
  def change
    remove_column :active_storage_attachments, :record_id
    add_column :active_storage_attachments, :record_id, :uuid, null: false
  end
end
```
You could also fix this by adding `type: :uuid` to the `record_id` reference in the initial migration.  
This seems to work fine, but not fully confident it wouldn't have side effects. YMMV.

**Comment by juansecaro** [comment]
I have decided to stick to default BigInt, but thanks for your help guys. Knowing the reason and an alternative solution is enough for me, but I don't feel 100% safe knowing it could be a source of pain and incompatibilities in the future win gems and integrations so I will take this time the safe road.

**Comment by ahanel13** [comment]
This is still an issue as of today 
![image](https://user-images.githubusercontent.com/47185077/114256907-27f38100-9982-11eb-97e8-6e0220bc4ef4.png)

**Comment by zzak** [comment]
Related to #40986

**Comment by donmb1** [comment]
> add_column :active_storage_attachments, :record_id, :uuid, null: false

this solved it for me. But what if we have one model using `ActiveStorage` which has `Integer` as primary key and one has `uuid`? Seems like it cannot be mixed but its a common usecase.

**Comment by reinaldonunes** [comment]
> I've fixed this with a migration to remove the `record_id` column from `active_storage_attachments` and add it back with the `:uuid` option.
> 
> ```ruby
> class ChangeActiveStorageRecordReferencesToUuid < ActiveRecord::Migration[6.1]
>   def change
>     remove_column :active_storage_attachments, :record_id
>     add_column :active_storage_attachments, :record_id, :uuid, null: false
>   end
> end
> ```
> 
> You could also fix this by adding `type: :uuid` to the `record_id` reference in the initial migration. This seems to work fine, but not fully confident it wouldn't have side effects. YMMV.

I had the same problem just now, I applied your resolution and it worked perfectly o/

**Comment by asmrtfm** [comment]
how would we handle this bug if only some of our tables use UUID?
