### ISSUE TITLE
ActiveSupport::Logger is overtaken by Logger

### ISSUE THREAD

**Issue by sonu1989** [rails/rails#41053]
I have upgraded the ruby version to 3.0.0 and rails version to 6.1.1, I am getting this issue **ERROR RuntimeError: class variable @@silencer of ActiveSupport::Logger is overtaken by Logger**

> [2021-01-08 17:46:17] ERROR RuntimeError: class variable @@silencer of ActiveSupport::Logger is overtaken by Logger
	/home/rails/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.0/lib/active_support/logger_silence.rb:12:in `silencer'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.0/lib/active_support/logger_silence.rb:18:in `silence'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.0/lib/active_support/logger.rb:62:in `block (2 levels) in broadcast'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:11:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/actionpack-6.1.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/actionpack-6.1.0/lib/action_dispatch/middleware/request_id.rb:26:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/skylight-core-4.3.2/lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/actionpack-6.1.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/actionpack-6.1.0/lib/action_dispatch/middleware/static.rb:24:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/actionpack-6.1.0/lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/railties-6.1.0/lib/rails/engine.rb:539:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
	/home/rails/.rvm/gems/ruby-3.0.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
127.0.0.1 - - [08/Jan/2021:17:46:17 IST] "GET /assets/users/30/icon-madhan.png?1407330942 HTTP/1.1" 500 353
http://localhost:3000/users?query%5Bteam_id_eq%5D=&query%5Bstatus_eq%5D=active&query%5Bdisplay_name_cont%5D= -> /assets/users/30/icon-madhan.png?1407330942

### Steps to reproduce
Change the ruby and rails version in gemfile and run bundle install, after this started rails server and open localhost:3000 in my browser

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 3.0.0

**Ubuntu version**:  18.04.5 LTS

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by fauzipadlaw** [comment]
I'm facing the same issue after upgrading to rails 6.1.1 and ruby 3.0.0. Start the server and it gives me the error. @rafaelfranca what more information do I need to provide?

**Comment by fauzipadlaw** [comment]
```
Puma caught this error: class variable @@silencer of ActiveSupport::Logger is overtaken by Logger (RuntimeError)
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/logger_silence.rb:12:in `silencer'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/logger_silence.rb:18:in `silence'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.1/lib/active_support/logger.rb:62:in `block (2 levels) in broadcast'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/debug_view.rb:50:in `render'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/host_authorization.rb:66:in `block in <class:HostAuthorization>'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.1/lib/action_dispatch/middleware/host_authorization.rb:100:in `call'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/rack-mini-profiler-2.3.0/lib/mini_profiler/profiler.rb:373:in `call'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/railties-6.1.1/lib/rails/engine.rb:539:in `call'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/puma-5.1.1/lib/puma/configuration.rb:246:in `call'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/puma-5.1.1/lib/puma/request.rb:76:in `block in handle_request'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/puma-5.1.1/lib/puma/thread_pool.rb:337:in `with_force_shutdown'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/puma-5.1.1/lib/puma/request.rb:75:in `handle_request'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/puma-5.1.1/lib/puma/server.rb:431:in `process_client'
/Users/efzet/work/elxr_backend/vendor/bundle/ruby/3.0.0/gems/puma-5.1.1/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

`uname -a`:
`Darwin fz 20.3.0 Darwin Kernel Version 20.3.0: Mon Dec  7 22:03:58 PST 2020; root:xnu-7195.80.16.111.1~1/RELEASE_ARM64_T8101 arm64`

**Comment by sonu1989** [comment]
> You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

As I mentioned I have changes the ruby and rails version in gemfile and run the bundle update, bundle update work successfully, after I start rails server that give me this error

**Comment by morus** [comment]
I have a similar issue and could track it down to the usage of `activerecord-session_store-1.1.3` which enhances `::Logger` with a `cattr_accessor  :silencer`. Since `ActiveSupport::Logger` inherits from `::Logger` and has it's own `cattr_accessor :silencer` there are two now, which causes the error.
If I comment out the declaration for `ActiveSupport::Logger` (in `activesupport-6.1.1/lib/active_support/logger_silence.rb`) the error goes away (which is not a solution, not even a workaround but some prove that the duplicate declaration causes the issue).

Not sure how this can be fixed. I'd consider it an active record session store issue...

**Comment by jonathanhefner** [comment]
Fixed by rails/activerecord-session_store#159.

**Comment by Charly3X** [comment]
Rails 6.1
gem 'activerecord-session_store', '2.1.0'

error is still here... 
RuntimeError (class variable @@silencer of ActiveSupport::Logger is overtaken by Logger):


how to fix this?

**Comment by gremz** [comment]
@Charly3X I used `gem 'activerecord-session_store', '~>2.1.0'` fixed it for me. (Rails 6.1.7.6, Ruby 3.2)

**Comment by xrnm** [comment]
removed fixed version by changing Gemfile to

`gem 'activerecord-session_store'`

removing `Gemfile.lock` and running `bundle install`
