### ISSUE TITLE
MissingTemplate issues in Rails 3.0

### ISSUE THREAD

**Issue by rishav** [rails/rails#4127]
This issue was reported earlier, but its not fixed in 3.0.x latest and some people have reported in 3.1.x as well.

https://github.com/rails/rails/issues/701

**Comment by iangreenleaf** [comment]
Confirmed still occurs in 4.2.0.

**Comment by firedev** [comment]
Also I am getting errors with the following `* HTTP_ACCEPT : : */*`

**Comment by ggeorgiev1** [comment]
Confirmed still occurs in Rails 3.2.13. Raising ActionView::MissingTemplate even with a ```#render :status => 422, :json => {:errors => 'error'}```

**Comment by gregkare** [comment]
We've ran into this issue with Rails 4.1.11: when a user sets the Accept header to "*/*;" we get a `ActionView::MissingTemplate` exception.

Adding `defaults: { format: 'html' }` to the route fixed it, but I'm not sure it's the right way, especially since it means changing all the routes in our application.

**Comment by blarralde** [comment]
Works great @gregkare

**Comment by purp** [comment]
That workaround may result in accepting requests which aren't able to properly accept an HTML response, @gregkare, @blarralde. Works if you don't care about this condition (which you likely don't), but if the thing on the other end wants JSON or somesuch, and if you wanted to produce JSON, that before_filter might cost you some debugging time until someone finds and removes it.

**Comment by blarralde** [comment]
@pup Just found that out. I've added `if request.format.to_sym.nil?` to validate that no other valid format had been set. What do you think?

**Comment by purp** [comment]
Hmmm. Don't know, @blarralde. It's been a couple of years since I was deep in that code. However, @antage's noted (Oct 19, 2012) that "hc/url;*/*" tripped it, which I think wouldn't show nil. Depends on how request.format maps to the Accept header.

In the end, if it works okay for you, you're probably good. Man, we need to get this one fixed.

**Comment by blarralde** [comment]
I've tested it multiple bogus accept headers, and since they're not in https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/mime_types.rb they don't have a symbol set. When a format is passed to the URL or as a accept header it takes precedence over the default response format. So:

* `curl www.example.com` returns HTML
* `curl -H "Accept: hc/url;/" www.example.com` returns HTML
* `curl www.example.com/.json` and `curl -H "Accept: hc/url;/" www.example.com/.json` return JSON if a JSON template is defined, missing template otherwise

**Comment by blarralde** [comment]
My previous solution created bugs in some parts of the app where format might be implied. So eventually I've replaced it with:

```ruby
BOGUS_REQUEST_FORMATS = ['*/*;', '/;', 'hc/url;*/*']
DEFAULT_RESPONSE_FORMAT = :html  
before_filter :set_default_response_format

def set_default_response_format
  request.format = DEFAULT_RESPONSE_FORMAT if request.format.in? BOGUS_REQUEST_FORMATS
end

**Comment by akaspick** [comment]
I was experiencing this issue with bots (and could reproduce with a curl command).  JSON was my default format, which was wrong.  I noticed I had this in my application_controller.rb

```ruby
respond_to :json, :html
```
Changed it to
```ruby
respond_to :html, :json
```
And the issue is resolved.

**Comment by tannusesquerdo** [comment]
I have the same issue.

ActionView::MissingTemplate: Missing template /home/index with {:formats=>[:json, :js, "*/*"]

**Comment by lustremedia** [comment]
Having this issue in 4.2.3
HTTP_ACCEPT    text/plain

Mostly from bots

**Comment by ryancheung** [comment]
I confirmed this issue in Rails 4.2 with:

`curl -H"Accept: */*;" http://localhost:3000/`

I found this issue was caused by a browser sending a invalid Http Accept header, which is  `*/*;`. This mean users of using this kind of buggy browser cannot visit your site. 

This happens rarely unless you're in China and programmers in Baidu.com made a fucking silly mistake. And most importantly, they have a large number of  users using the buggy browser they made.

Can't Rails framework just ignore this and set to the default format :html instead of throwing a exception? @dhh

**Comment by purp** [comment]
Sadly, @ryancheung, that leads to unintended consequences as a few folks in this thread have discovered. Accepting "*/*" is legit, and usually a bot that wants to accept anything. If you change the default format, you end up killing anything that wants json (or other formats), which may work for **your** app, but might not work for all apps.

See [this comment above](https://github.com/rails/rails/issues/4127#issuecomment-113147026) and the next seven or so comments for an illustration of where it goes wrong.

**Comment by purp** [comment]
**THIS IS FINALLY FIXED IN RAILS 5.0.0!** 

The example to reproduce this below will properly return `406 Not Acceptable` in Rails 5.0.0. Huge thanks to whoever reworked content negotiation to eliminate this issue.

Here's a quick and easy way to reproduce with any Rails version prior to 5.0.0:

```
> rails new rails-4127 && cd rails-4127 && rails server

# New terminal
> curl -H"Accept: hc/url;*/*" -I http://localhost:3000/
```

If it's broken, you'll get this in the curl terminal:

```
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=utf-8
Content-Length: 141744
[...]
```

... and something like this in the server terminal:

```
Started GET "/" for ::1 at 2016-08-08 17:29:47 -0700
Processing by Rails::WelcomeController#index as hc/url;*/*
Completed 500 Internal Server Error in 17ms (ActiveRecord: 0.0ms)

ActionView::MissingTemplate (Missing template rails/welcome/index, rails/application/index with {:locale=>[:en], :formats=>["hc/url;*/*"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/railties-4.2.7/lib/rails/templates"
):
[...]
```

In Rails 5.0.0 you get this in the curl terminal:

```
HTTP/1.1 406 Not Acceptable
Content-Type: text/html; charset=utf-8
[...]
```

... and something like this in the server terminal:

```
Started HEAD "/" for ::1 at 2016-08-08 17:53:48 -0700
Processing by Rails::WelcomeController#index as hc/url;*/*
  Parameters: {"internal"=>true}
Completed 406 Not Acceptable in 55ms (ActiveRecord: 0.0ms)
```

If you still need a workaround, here's what a slightly wiser me would offer now:

```ruby
class ApplicationController < ActionController::Base
  rescue_from ActionView::MissingTemplate, :with => :catch_unacceptable_requests

  def catch_unacceptable_requests(exception)
    if !ActionController::MimeResponds::Collector.new(collect_mimes_from_class_level).negotiate_format(request)
      head :not_acceptable
    else
      raise exception
    end
  end
```

_(about friggin' time! ;)_

**Comment by ryancheung** [comment]
@purp Thanks! This should only be worked around in my own site. For illegal accept headers, either fallback to :html or return 406.

**Comment by h8rry** [comment]
@purp I am using Rails 5 and still see "missing a template for this request format and variant". If I previously upgraded from 4 to 5, what are the things I should remove manually to fix this? Thanks!

**Comment by purp** [comment]
@h8rry I'm unclear what you're asking here. Are you saying that you implemented the fix above in Rails 4, and upon upgrading to Rails 5 you're having this problem, or is this problem with a new Rails 5 app?
