### ISSUE TITLE
Creating a new (edge) rails project fails with undefined method assets for ...

### ISSUE THREAD

**Issue by roelandmoors** [rails/rails#43422]
### Steps to reproduce
`rails new demo -d postgresql --edge --css=tailwind`
EDIT: this also fails: `rails new demo --edge`

### Expected behavior
It shoud create a new rails project without error
Without the edge option it works fine:
`rails new demo -d postgresql --css=tailwind`

### Actual behavior
```
Using turbo-rails 0.8.1
Bundle complete! 15 Gemfile dependencies, 63 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x0000000153c06148 @root=#<Pathname:/Users/roeland/dev/demo4>, @generators=#<Rails::Configuration::Generators:0x0000000150f91388 @aliases={}, @options={:rails=>{:orm=>:active_record, :test_framework=>:test_unit, :integration_tool=>:test_unit, :system_tests=>:test_unit, :template_engine=>:tailwindcss}, :active_record=>{:migration=>true, :timestamps=>true}, :test_unit=>{:fixture=>true, :fixture_replacement=>nil}}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_generate_callbacks=[]>, @middleware=#<Rails::Configuration::MiddlewareStackProxy:0x0000000153c05518 @operations=[], @delete_operations=[]>, @javascript_path="javascript", @encoding=#<Encoding:UTF-8>, @allow_concurrency=nil, @consider_all_requests_local=true, @filter_parameters=[], @filter_redirect=[], @helpers_paths=[], @hosts=[".localhost", #<IPAddr: IPv4:0.0.0.0/0.0.0.0>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/0000:0000:0000:0000:0000:0000:0000:0000>], @host_authorization={}, @public_file_server=#<ActiveSupport::OrderedOptions {:enabled=>true, :index_name=>"index"}>, @force_ssl=false, @ssl_options={:hsts=>{:subdomains=>true}}, @session_store=nil, @time_zone="UTC", @beginning_of_week=:monday, @log_level=:debug, @cache_store=:null_store, @railties_order=[:all], @relative_url_root=nil, @reload_classes_only_on_change=true, @file_watcher=ActiveSupport::FileUpdateChecker, @exceptions_app=nil, @autoflush_log=true, @log_formatter=#<ActiveSupport::Logger::SimpleFormatter:0x0000000153bff9d8 @datetime_format=nil>, @eager_load=false, @secret_key_base=nil, @api_only=false, @debug_exception_response_format=nil, @x=#<Rails::Application::Configuration::Custom:0x0000000153bff898 @configurations={}>, @enable_dependency_loading=false, @read_encrypted_secrets=false, @content_security_policy=nil, @content_security_policy_report_only=false, @content_security_policy_nonce_generator=nil, @content_security_policy_nonce_directives=nil, @require_master_key=false, @loaded_config_version=7.0, @credentials=#<ActiveSupport::OrderedOptions {:content_path=>#<Pathname:/Users/roeland/dev/demo4/config/credentials.yml.enc>, :key_path=>#<Pathname:/Users/roeland/dev/demo4/config/master.key>}>, @disable_sandbox=false, @add_autoload_paths_to_load_path=true, @permissions_policy=nil, @rake_eager_load=false, @server_timing=false, @paths=#<Rails::Paths::Root:0x0000000153d273d8 @path=#<Pathname:/Users/roeland/dev/demo4>, @root={"app"=>#<Rails::Paths::Path:0x0000000153d26de8 @paths=["app"], @current="app", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="{*,*/concerns}", @exclude=["assets", "javascript"], @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/assets"=>#<Rails::Paths::Path:0x0000000153d268e8 @paths=["app/assets"], @current="app/assets", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/controllers"=>#<Rails::Paths::Path:0x0000000153d26668 @paths=["app/controllers"], @current="app/controllers", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/channels"=>#<Rails::Paths::Path:0x0000000153d26438 @paths=["app/channels"], @current="app/channels", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="**/*_channel.rb", @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/helpers"=>#<Rails::Paths::Path:0x0000000153d26208 @paths=["app/helpers"], @current="app/helpers", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/models"=>#<Rails::Paths::Path:0x0000000153d25fd8 @paths=["app/models"], @current="app/models", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/mailers"=>#<Rails::Paths::Path:0x0000000153d25da8 @paths=["app/mailers"], @current="app/mailers", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/views"=>#<Rails::Paths::Path:0x0000000153d25b78 @paths=["app/views"], @current="app/views", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib"=>#<Rails::Paths::Path:0x0000000153d25948 @paths=["lib"], @current="lib", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "lib/assets"=>#<Rails::Paths::Path:0x0000000153d25650 @paths=["lib/assets"], @current="lib/assets", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/tasks"=>#<Rails::Paths::Path:0x0000000153d25420 @paths=["lib/tasks"], @current="lib/tasks", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="**/*.rake", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config"=>#<Rails::Paths::Path:0x0000000153d252b8 @paths=["config"], @current="config", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environments"=>#<Rails::Paths::Path:0x0000000153d24ea8 @paths=["config/environments"], @current="config/environments", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="development.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/initializers"=>#<Rails::Paths::Path:0x0000000153d24c78 @paths=["config/initializers"], @current="config/initializers", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/locales"=>#<Rails::Paths::Path:0x0000000153d24a48 @paths=["config/locales"], @current="config/locales", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="**/*.{rb,yml}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes.rb"=>#<Rails::Paths::Path:0x0000000153d248e0 @paths=["config/routes.rb"], @current="config/routes.rb", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes"=>#<Rails::Paths::Path:0x0000000153d246b0 @paths=["config/routes"], @current="config/routes", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db"=>#<Rails::Paths::Path:0x0000000153d244a8 @paths=["db"], @current="db", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/migrate"=>#<Rails::Paths::Path:0x0000000153d24318 @paths=["db/migrate"], @current="db/migrate", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/seeds.rb"=>#<Rails::Paths::Path:0x0000000153d241d8 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Rails::Paths::Path:0x0000000153d1fef8 @paths=["vendor"], @current="vendor", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Rails::Paths::Path:0x0000000153d1fcc8 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/database"=>#<Rails::Paths::Path:0x0000000153d1fa98 @paths=["config/database.yml"], @current="config/database", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/secrets"=>#<Rails::Paths::Path:0x0000000153d1f868 @paths=["config"], @current="config/secrets", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob="secrets.yml{,.enc}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environment"=>#<Rails::Paths::Path:0x0000000153d1f638 @paths=["config/environment.rb"], @current="config/environment", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/templates"=>#<Rails::Paths::Path:0x0000000153d1f4d0 @paths=["lib/templates"], @current="lib/templates", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "log"=>#<Rails::Paths::Path:0x0000000153d1f188 @paths=["log/development.log"], @current="log", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public"=>#<Rails::Paths::Path:0x0000000153d1f048 @paths=["public"], @current="public", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/javascripts"=>#<Rails::Paths::Path:0x0000000153d1ee68 @paths=["public/javascripts"], @current="public/javascripts", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/stylesheets"=>#<Rails::Paths::Path:0x0000000153d1ed00 @paths=["public/stylesheets"], @current="public/stylesheets", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "tmp"=>#<Rails::Paths::Path:0x0000000153d1eaf8 @paths=["tmp"], @current="tmp", @root=#<Rails::Paths::Root:0x0000000153d273d8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @cache_classes=false>
Did you mean?  asset_host
/Users/roeland/dev/demo4/config/environments/development.rb:57:in `block in <main>'
/Users/roeland/dev/demo4/config/environments/development.rb:3:in `<main>'
/Users/roeland/dev/demo4/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.
       rails  tailwindcss:install
rails aborted!
```

### System configuration
**Rails version**: Rails 7.0.0.alpha2

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]

**Comment by ghiculescu** [comment]
I think https://github.com/rails/rails/pull/43261 is the culprit, since [this line](https://github.com/rails/rails/pull/43261/files#diff-22357f8be507e1f3f2366d30c196086a10d34b33c983a2f1be36750bb473bd4cL18) was removed and so [this line](https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/railtie.rb#L96) wouldn't fire.

**Comment by roelandmoors** [comment]
no, there is no `sprocket-rails`

```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Use specific branch of Rails
gem "rails", github: "rails/rails", branch: "main"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails", ">= 0.3.4"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails", ">= 0.7.11"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails", ">= 0.4.0"

# Use Tailwind CSS [https://github.com/rails/tailwindcss-rails]
gem "tailwindcss-rails", ">= 0.4.3"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder", "~> 2.7"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Use Sass to process CSS
# gem "sassc-rails", "~> 2.1"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # Start debugger with binding.b [https://github.com/ruby/debug]
  gem "debug", ">= 1.0.0", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console", ">= 4.1.0"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler", ">= 2.3.3"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

**Comment by roelandmoors** [comment]
I did use Rails 7.0.0.alpha2, but maybe you mean a later or final Rails 7? I don't have a problem with that.

**Comment by jonathanhefner** [comment]
> This is expected in the sense that --edge will bind to GitHub Rails, but still use the Rails app generator included in the installed version of Rails (6.x).

#39663 will address this, if anyone wants to give that a go.

**Comment by rmacklin** [comment]
This issue should be resolved now that rails v7.0.0.rc1 has been released, which includes https://github.com/rails/rails/pull/43261.

I installed rails v7.0.0.rc1 locally and generated a new app with `--asset_pipeline=sprockets`. With or without the `--edge` option, it no longer produces the errors `Don't know how to build task 'assets:precompile'` or ```NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x000055a94e494b78>```

**Comment by jakeonfire** [comment]
Seems like this is still an issue with Rails 7.1.0alpha - when using `--javascript=importmap` option the generator adds e.g. ```ruby
pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true
```
but fails to add `sprockets-rails`, which is required for precompiling said assets, and for avoiding `NoMethodError: undefined method \`assets'` errors since other generated files (`assets.rb`, `development.rb`) reference`config.assets`.

**Comment by skipkayhil** [comment]
> Seems like this is still an issue with Rails `7.1.0.alpha`

I would open a new issue if you are having a problem, discussion on closed issues usually doesn't go very far.

That being said, I just tried generating an app using `railties/exe/rails` and sprockets-rails is in the Gemfile so some more details for how to reproduce will definitely be necessary.

**Comment by jakeonfire** [comment]
fwiw i ran:
```
rails new myrailsproject --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-active-record --skip-active-job --main --javascript=importmap
```
but i'll open a new issue if i run into it again.
