### ISSUE TITLE
NoMethodError: undefined method `action_mailer' for #<Rails::Application::Configuration when using --skip-active-job flag

### ISSUE THREAD

**Issue by wscourge** [rails/rails#46295]
### Steps to reproduce
Run `rails new skip_active_job_error -T -a sprockets -j rollup -c bulma -d sqlite3 --skip-active-job -f`. The guilty part is `--skip-active-job`, there's no error without it.

### Expected behavior
No errors.

### Actual behavior
> NoMethodError: undefined method `action_mailer' for #<Rails::Application::Configuration

<details>
  <summary>Stacktrace</summary>

  <pre>
$ rails new sqlite_rollup_manual -T -a sprockets -j rollup -c bulma -d sqlite3 --skip-active-job -f                            35s
      create
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      remove  app/jobs
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies.......
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using minitest 5.16.3
Using nio4r 2.5.8
Using erubi 1.11.0
Using racc 1.6.0
Using bundler 2.3.23
Using rack 2.2.4
Using crass 1.0.6
Using method_source 1.0.0
Using thor 1.2.1
Using zeitwerk 2.6.1
Using io-console 0.5.11
Using sqlite3 1.5.3 (arm64-darwin)
Using i18n 1.12.0
Using tzinfo 2.0.5
Using puma 5.6.5
Using websocket-extensions 0.1.5
Using mini_mime 1.1.2
Using reline 0.3.1
Using marcel 1.0.2
Using builder 3.2.4
Using timeout 0.3.0
Using bindex 0.8.1
Using msgpack 1.6.0
Using nokogiri 1.13.9 (arm64-darwin)
Using activesupport 7.0.4
Using loofah 2.19.0
Using rack-test 2.0.2
Using rails-dom-testing 2.0.3
Using rails-html-sanitizer 1.4.3
Using globalid 1.0.0
Using websocket-driver 0.7.5
Using mail 2.7.1
Using net-protocol 0.1.3
Using bootsnap 1.13.0
Using net-imap 0.3.1
Using net-pop 0.1.2
Using net-smtp 0.3.2
Using irb 1.4.2
Using sprockets 4.1.1
Using actionview 7.0.4
Using debug 1.6.2
Using actionpack 7.0.4
Using activejob 7.0.4
Using railties 7.0.4
Using jbuilder 2.11.5
Using cssbundling-rails 1.1.1
Using actioncable 7.0.4
Using sprockets-rails 3.4.2
Using actionmailer 7.0.4
Using jsbundling-rails 1.0.3
Using stimulus-rails 1.1.0
Using turbo-rails 1.3.1
Using activemodel 7.0.4
Using activerecord 7.0.4
Using web-console 4.2.0
Using activestorage 7.0.4
Using actionmailbox 7.0.4
Using actiontext 7.0.4
Using rails 7.0.4
Bundle complete! 13 Gemfile dependencies, 61 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  javascript:install:rollup
rails aborted!
NoMethodError: undefined method `action_mailer' for #<Rails::Application::Configuration:0x000000010b18c638 @root=#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual>, @generators=#<Rails::Configuration::Generators:0x0000000108a44c10 @aliases={}, @options={:rails=>{:orm=>:active_record, :system_tests=>nil}, :active_record=>{:migration=>true, :timestamps=>true}}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_generate_callbacks=[]>, @middleware=#<Rails::Configuration::MiddlewareStackProxy:0x000000010b187ae8 @operations=[], @delete_operations=[]>, @javascript_path="javascript", @encoding=#<Encoding:UTF-8>, @allow_concurrency=nil, @consider_all_requests_local=true, @filter_parameters=[], @filter_redirect=[], @helpers_paths=[], @hosts=[".localhost", #<IPAddr: IPv4:0.0.0.0/0.0.0.0>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/0000:0000:0000:0000:0000:0000:0000:0000>], @host_authorization={}, @public_file_server=#<ActiveSupport::OrderedOptions {:enabled=>true, :index_name=>"index"}>, @force_ssl=false, @ssl_options={:hsts=>{:subdomains=>true}}, @session_store=nil, @time_zone="UTC", @beginning_of_week=:monday, @log_level=:debug, @cache_store=:null_store, @railties_order=[:all], @relative_url_root=nil, @reload_classes_only_on_change=true, @file_watcher=ActiveSupport::FileUpdateChecker, @exceptions_app=nil, @autoflush_log=true, @log_formatter=#<ActiveSupport::Logger::SimpleFormatter:0x000000010b32d7d0 @datetime_format=nil>, @eager_load=false, @secret_key_base=nil, @api_only=false, @debug_exception_response_format=nil, @x=#<Rails::Application::Configuration::Custom:0x000000010b32d6b8 @configurations={}>, @enable_dependency_loading=false, @read_encrypted_secrets=false, @content_security_policy=nil, @content_security_policy_report_only=false, @content_security_policy_nonce_generator=nil, @content_security_policy_nonce_directives=nil, @require_master_key=false, @loaded_config_version=7.0, @credentials=#<ActiveSupport::OrderedOptions {:content_path=>#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/credentials.yml.enc>, :key_path=>#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/master.key>}>, @disable_sandbox=false, @add_autoload_paths_to_load_path=true, @permissions_policy=nil, @rake_eager_load=false, @server_timing=true, @paths=#<Rails::Paths::Root:0x000000010b38dce8 @path=#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual>, @root={"app"=>#<Rails::Paths::Path:0x000000010b38db30 @paths=["app"], @current="app", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="{*,*/concerns}", @exclude=["assets", "javascript"], @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/assets"=>#<Rails::Paths::Path:0x000000010b38d9c8 @paths=["app/assets"], @current="app/assets", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/controllers"=>#<Rails::Paths::Path:0x000000010b38d900 @paths=["app/controllers"], @current="app/controllers", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/channels"=>#<Rails::Paths::Path:0x000000010b38d860 @paths=["app/channels"], @current="app/channels", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/helpers"=>#<Rails::Paths::Path:0x000000010b38d7c0 @paths=["app/helpers"], @current="app/helpers", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/models"=>#<Rails::Paths::Path:0x000000010b38d720 @paths=["app/models"], @current="app/models", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/mailers"=>#<Rails::Paths::Path:0x000000010b38d680 @paths=["app/mailers"], @current="app/mailers", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/views"=>#<Rails::Paths::Path:0x000000010b38d5e0 @paths=["app/views"], @current="app/views", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib"=>#<Rails::Paths::Path:0x000000010b38d540 @paths=["lib"], @current="lib", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "lib/assets"=>#<Rails::Paths::Path:0x000000010b38d400 @paths=["lib/assets"], @current="lib/assets", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/tasks"=>#<Rails::Paths::Path:0x000000010b38d2e8 @paths=["lib/tasks"], @current="lib/tasks", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="**/*.rake", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config"=>#<Rails::Paths::Path:0x000000010b38d248 @paths=["config"], @current="config", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environments"=>#<Rails::Paths::Path:0x000000010b38d0e0 @paths=["config/environments"], @current="config/environments", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="development.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/initializers"=>#<Rails::Paths::Path:0x000000010b38d040 @paths=["config/initializers"], @current="config/initializers", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/locales"=>#<Rails::Paths::Path:0x000000010b38cfa0 @paths=["config/locales"], @current="config/locales", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="**/*.{rb,yml}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes.rb"=>#<Rails::Paths::Path:0x000000010b38cf28 @paths=["config/routes.rb"], @current="config/routes.rb", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes"=>#<Rails::Paths::Path:0x000000010b38ce88 @paths=["config/routes"], @current="config/routes", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db"=>#<Rails::Paths::Path:0x000000010b38ce10 @paths=["db"], @current="db", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/migrate"=>#<Rails::Paths::Path:0x000000010b38cd98 @paths=["db/migrate"], @current="db/migrate", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/seeds.rb"=>#<Rails::Paths::Path:0x000000010b38cd20 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Rails::Paths::Path:0x000000010b38cc80 @paths=["vendor"], @current="vendor", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Rails::Paths::Path:0x000000010b38cac8 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/database"=>#<Rails::Paths::Path:0x000000010b38c988 @paths=["config/database.yml"], @current="config/database", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/secrets"=>#<Rails::Paths::Path:0x000000010b38c820 @paths=["config"], @current="config/secrets", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob="secrets.yml{,.enc}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environment"=>#<Rails::Paths::Path:0x000000010b38c6b8 @paths=["config/environment.rb"], @current="config/environment", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/templates"=>#<Rails::Paths::Path:0x000000010b38c578 @paths=["lib/templates"], @current="lib/templates", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "log"=>#<Rails::Paths::Path:0x000000010b38c2d0 @paths=["log/development.log"], @current="log", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public"=>#<Rails::Paths::Path:0x000000010b38c028 @paths=["public"], @current="public", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/javascripts"=>#<Rails::Paths::Path:0x000000010b3879b0 @paths=["public/javascripts"], @current="public/javascripts", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/stylesheets"=>#<Rails::Paths::Path:0x000000010b386f10 @paths=["public/stylesheets"], @current="public/stylesheets", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "tmp"=>#<Rails::Paths::Path:0x000000010b386e70 @paths=["tmp"], @current="tmp", @root=#<Rails::Paths::Root:0x000000010b38dce8 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @cache_classes=false>
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environments/development.rb:37:in `block in <main>'
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environments/development.rb:3:in `<main>'
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
rails aborted!
NoMethodError: undefined method `action_mailer' for #<Rails::Application::Configuration:0x0000000107bcfa40 @root=#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual>, @generators=#<Rails::Configuration::Generators:0x00000001074e4438 @aliases={}, @options={:rails=>{:orm=>:active_record, :system_tests=>nil}, :active_record=>{:migration=>true, :timestamps=>true}}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_generate_callbacks=[]>, @middleware=#<Rails::Configuration::MiddlewareStackProxy:0x0000000107bcf4a0 @operations=[], @delete_operations=[]>, @javascript_path="javascript", @encoding=#<Encoding:UTF-8>, @allow_concurrency=nil, @consider_all_requests_local=true, @filter_parameters=[], @filter_redirect=[], @helpers_paths=[], @hosts=[".localhost", #<IPAddr: IPv4:0.0.0.0/0.0.0.0>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/0000:0000:0000:0000:0000:0000:0000:0000>], @host_authorization={}, @public_file_server=#<ActiveSupport::OrderedOptions {:enabled=>true, :index_name=>"index"}>, @force_ssl=false, @ssl_options={:hsts=>{:subdomains=>true}}, @session_store=nil, @time_zone="UTC", @beginning_of_week=:monday, @log_level=:debug, @cache_store=:null_store, @railties_order=[:all], @relative_url_root=nil, @reload_classes_only_on_change=true, @file_watcher=ActiveSupport::FileUpdateChecker, @exceptions_app=nil, @autoflush_log=true, @log_formatter=#<ActiveSupport::Logger::SimpleFormatter:0x0000000107bc5130 @datetime_format=nil>, @eager_load=false, @secret_key_base=nil, @api_only=false, @debug_exception_response_format=nil, @x=#<Rails::Application::Configuration::Custom:0x0000000107bc5018 @configurations={}>, @enable_dependency_loading=false, @read_encrypted_secrets=false, @content_security_policy=nil, @content_security_policy_report_only=false, @content_security_policy_nonce_generator=nil, @content_security_policy_nonce_directives=nil, @require_master_key=false, @loaded_config_version=7.0, @credentials=#<ActiveSupport::OrderedOptions {:content_path=>#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/credentials.yml.enc>, :key_path=>#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/master.key>}>, @disable_sandbox=false, @add_autoload_paths_to_load_path=true, @permissions_policy=nil, @rake_eager_load=false, @server_timing=true, @paths=#<Rails::Paths::Root:0x0000000107c442f0 @path=#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual>, @root={"app"=>#<Rails::Paths::Path:0x0000000107d1bf20 @paths=["app"], @current="app", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="{*,*/concerns}", @exclude=["assets", "javascript"], @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/assets"=>#<Rails::Paths::Path:0x0000000107d1bdb8 @paths=["app/assets"], @current="app/assets", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/controllers"=>#<Rails::Paths::Path:0x0000000107d1bcf0 @paths=["app/controllers"], @current="app/controllers", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/channels"=>#<Rails::Paths::Path:0x0000000107d1bc50 @paths=["app/channels"], @current="app/channels", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/helpers"=>#<Rails::Paths::Path:0x0000000107d1bbb0 @paths=["app/helpers"], @current="app/helpers", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/models"=>#<Rails::Paths::Path:0x0000000107d1bb10 @paths=["app/models"], @current="app/models", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/mailers"=>#<Rails::Paths::Path:0x0000000107d1ba70 @paths=["app/mailers"], @current="app/mailers", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/views"=>#<Rails::Paths::Path:0x0000000107d1b9d0 @paths=["app/views"], @current="app/views", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib"=>#<Rails::Paths::Path:0x0000000107d1b930 @paths=["lib"], @current="lib", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "lib/assets"=>#<Rails::Paths::Path:0x0000000107d1b868 @paths=["lib/assets"], @current="lib/assets", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/tasks"=>#<Rails::Paths::Path:0x0000000107d1b7c8 @paths=["lib/tasks"], @current="lib/tasks", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="**/*.rake", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config"=>#<Rails::Paths::Path:0x0000000107d1b750 @paths=["config"], @current="config", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environments"=>#<Rails::Paths::Path:0x0000000107d1b638 @paths=["config/environments"], @current="config/environments", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="development.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/initializers"=>#<Rails::Paths::Path:0x0000000107d1b598 @paths=["config/initializers"], @current="config/initializers", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/locales"=>#<Rails::Paths::Path:0x0000000107d1b4f8 @paths=["config/locales"], @current="config/locales", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="**/*.{rb,yml}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes.rb"=>#<Rails::Paths::Path:0x0000000107d1b480 @paths=["config/routes.rb"], @current="config/routes.rb", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes"=>#<Rails::Paths::Path:0x0000000107d1b3e0 @paths=["config/routes"], @current="config/routes", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db"=>#<Rails::Paths::Path:0x0000000107d1b368 @paths=["db"], @current="db", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/migrate"=>#<Rails::Paths::Path:0x0000000107d1b2f0 @paths=["db/migrate"], @current="db/migrate", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/seeds.rb"=>#<Rails::Paths::Path:0x0000000107d1b278 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Rails::Paths::Path:0x0000000107d1b1d8 @paths=["vendor"], @current="vendor", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Rails::Paths::Path:0x0000000107d1b138 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/database"=>#<Rails::Paths::Path:0x0000000107d1b098 @paths=["config/database.yml"], @current="config/database", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/secrets"=>#<Rails::Paths::Path:0x0000000107d1aff8 @paths=["config"], @current="config/secrets", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob="secrets.yml{,.enc}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environment"=>#<Rails::Paths::Path:0x0000000107d1af58 @paths=["config/environment.rb"], @current="config/environment", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/templates"=>#<Rails::Paths::Path:0x0000000107d1aee0 @paths=["lib/templates"], @current="lib/templates", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "log"=>#<Rails::Paths::Path:0x0000000107d1adf0 @paths=["log/development.log"], @current="log", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public"=>#<Rails::Paths::Path:0x0000000107d1ad78 @paths=["public"], @current="public", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/javascripts"=>#<Rails::Paths::Path:0x0000000107d1ad00 @paths=["public/javascripts"], @current="public/javascripts", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/stylesheets"=>#<Rails::Paths::Path:0x0000000107d1ac88 @paths=["public/stylesheets"], @current="public/stylesheets", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "tmp"=>#<Rails::Paths::Path:0x0000000107d1ac10 @paths=["tmp"], @current="tmp", @root=#<Rails::Paths::Root:0x0000000107c442f0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @cache_classes=false>
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environments/development.rb:37:in `block in <main>'
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environments/development.rb:3:in `<main>'
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.
You must either be running with node (package.json) or importmap-rails (config/importmap.rb) to use this gem.
       rails  css:install:bulma
rails aborted!
NoMethodError: undefined method `action_mailer' for #<Rails::Application::Configuration:0x0000000106dca2b0 @root=#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual>, @generators=#<Rails::Configuration::Generators:0x00000001069efaf0 @aliases={}, @options={:rails=>{:orm=>:active_record, :system_tests=>nil}, :active_record=>{:migration=>true, :timestamps=>true}}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_generate_callbacks=[]>, @middleware=#<Rails::Configuration::MiddlewareStackProxy:0x0000000106dc9d10 @operations=[], @delete_operations=[]>, @javascript_path="javascript", @encoding=#<Encoding:UTF-8>, @allow_concurrency=nil, @consider_all_requests_local=true, @filter_parameters=[], @filter_redirect=[], @helpers_paths=[], @hosts=[".localhost", #<IPAddr: IPv4:0.0.0.0/0.0.0.0>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/0000:0000:0000:0000:0000:0000:0000:0000>], @host_authorization={}, @public_file_server=#<ActiveSupport::OrderedOptions {:enabled=>true, :index_name=>"index"}>, @force_ssl=false, @ssl_options={:hsts=>{:subdomains=>true}}, @session_store=nil, @time_zone="UTC", @beginning_of_week=:monday, @log_level=:debug, @cache_store=:null_store, @railties_order=[:all], @relative_url_root=nil, @reload_classes_only_on_change=true, @file_watcher=ActiveSupport::FileUpdateChecker, @exceptions_app=nil, @autoflush_log=true, @log_formatter=#<ActiveSupport::Logger::SimpleFormatter:0x0000000106dbb210 @datetime_format=nil>, @eager_load=false, @secret_key_base=nil, @api_only=false, @debug_exception_response_format=nil, @x=#<Rails::Application::Configuration::Custom:0x0000000106dbb058 @configurations={}>, @enable_dependency_loading=false, @read_encrypted_secrets=false, @content_security_policy=nil, @content_security_policy_report_only=false, @content_security_policy_nonce_generator=nil, @content_security_policy_nonce_directives=nil, @require_master_key=false, @loaded_config_version=7.0, @credentials=#<ActiveSupport::OrderedOptions {:content_path=>#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/credentials.yml.enc>, :key_path=>#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/master.key>}>, @disable_sandbox=false, @add_autoload_paths_to_load_path=true, @permissions_policy=nil, @rake_eager_load=false, @server_timing=true, @paths=#<Rails::Paths::Root:0x000000010701a358 @path=#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual>, @root={"app"=>#<Rails::Paths::Path:0x000000010701a1a0 @paths=["app"], @current="app", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="{*,*/concerns}", @exclude=["assets", "javascript"], @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/assets"=>#<Rails::Paths::Path:0x000000010701a038 @paths=["app/assets"], @current="app/assets", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/controllers"=>#<Rails::Paths::Path:0x0000000107019f70 @paths=["app/controllers"], @current="app/controllers", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/channels"=>#<Rails::Paths::Path:0x0000000107019ed0 @paths=["app/channels"], @current="app/channels", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/helpers"=>#<Rails::Paths::Path:0x0000000107019e30 @paths=["app/helpers"], @current="app/helpers", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/models"=>#<Rails::Paths::Path:0x0000000107019d90 @paths=["app/models"], @current="app/models", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/mailers"=>#<Rails::Paths::Path:0x0000000107019cf0 @paths=["app/mailers"], @current="app/mailers", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/views"=>#<Rails::Paths::Path:0x0000000107019c50 @paths=["app/views"], @current="app/views", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib"=>#<Rails::Paths::Path:0x0000000107019bb0 @paths=["lib"], @current="lib", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "lib/assets"=>#<Rails::Paths::Path:0x0000000107019ae8 @paths=["lib/assets"], @current="lib/assets", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/tasks"=>#<Rails::Paths::Path:0x0000000107019a48 @paths=["lib/tasks"], @current="lib/tasks", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="**/*.rake", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config"=>#<Rails::Paths::Path:0x00000001070199d0 @paths=["config"], @current="config", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environments"=>#<Rails::Paths::Path:0x00000001070198b8 @paths=["config/environments"], @current="config/environments", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="development.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/initializers"=>#<Rails::Paths::Path:0x0000000107019818 @paths=["config/initializers"], @current="config/initializers", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/locales"=>#<Rails::Paths::Path:0x0000000107019778 @paths=["config/locales"], @current="config/locales", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="**/*.{rb,yml}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes.rb"=>#<Rails::Paths::Path:0x0000000107019700 @paths=["config/routes.rb"], @current="config/routes.rb", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes"=>#<Rails::Paths::Path:0x0000000107019660 @paths=["config/routes"], @current="config/routes", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db"=>#<Rails::Paths::Path:0x00000001070195e8 @paths=["db"], @current="db", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/migrate"=>#<Rails::Paths::Path:0x0000000107019570 @paths=["db/migrate"], @current="db/migrate", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/seeds.rb"=>#<Rails::Paths::Path:0x00000001070194f8 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Rails::Paths::Path:0x0000000107019458 @paths=["vendor"], @current="vendor", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Rails::Paths::Path:0x00000001070193b8 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/database"=>#<Rails::Paths::Path:0x0000000107019318 @paths=["config/database.yml"], @current="config/database", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/secrets"=>#<Rails::Paths::Path:0x0000000107019278 @paths=["config"], @current="config/secrets", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob="secrets.yml{,.enc}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environment"=>#<Rails::Paths::Path:0x00000001070191d8 @paths=["config/environment.rb"], @current="config/environment", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/templates"=>#<Rails::Paths::Path:0x0000000107019160 @paths=["lib/templates"], @current="lib/templates", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "log"=>#<Rails::Paths::Path:0x0000000107019070 @paths=["log/development.log"], @current="log", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public"=>#<Rails::Paths::Path:0x0000000107018ff8 @paths=["public"], @current="public", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/javascripts"=>#<Rails::Paths::Path:0x0000000107018f80 @paths=["public/javascripts"], @current="public/javascripts", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/stylesheets"=>#<Rails::Paths::Path:0x0000000107018f08 @paths=["public/stylesheets"], @current="public/stylesheets", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "tmp"=>#<Rails::Paths::Path:0x0000000107018e90 @paths=["tmp"], @current="tmp", @root=#<Rails::Paths::Root:0x000000010701a358 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @cache_classes=false>
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environments/development.rb:37:in `block in <main>'
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environments/development.rb:3:in `<main>'
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
rails aborted!
NoMethodError: undefined method `action_mailer' for #<Rails::Application::Configuration:0x0000000109e4e738 @root=#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual>, @generators=#<Rails::Configuration::Generators:0x000000010956f900 @aliases={}, @options={:rails=>{:orm=>:active_record, :system_tests=>nil}, :active_record=>{:migration=>true, :timestamps=>true}}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_generate_callbacks=[]>, @middleware=#<Rails::Configuration::MiddlewareStackProxy:0x0000000109e4e198 @operations=[], @delete_operations=[]>, @javascript_path="javascript", @encoding=#<Encoding:UTF-8>, @allow_concurrency=nil, @consider_all_requests_local=true, @filter_parameters=[], @filter_redirect=[], @helpers_paths=[], @hosts=[".localhost", #<IPAddr: IPv4:0.0.0.0/0.0.0.0>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/0000:0000:0000:0000:0000:0000:0000:0000>], @host_authorization={}, @public_file_server=#<ActiveSupport::OrderedOptions {:enabled=>true, :index_name=>"index"}>, @force_ssl=false, @ssl_options={:hsts=>{:subdomains=>true}}, @session_store=nil, @time_zone="UTC", @beginning_of_week=:monday, @log_level=:debug, @cache_store=:null_store, @railties_order=[:all], @relative_url_root=nil, @reload_classes_only_on_change=true, @file_watcher=ActiveSupport::FileUpdateChecker, @exceptions_app=nil, @autoflush_log=true, @log_formatter=#<ActiveSupport::Logger::SimpleFormatter:0x0000000109e44260 @datetime_format=nil>, @eager_load=false, @secret_key_base=nil, @api_only=false, @debug_exception_response_format=nil, @x=#<Rails::Application::Configuration::Custom:0x0000000109e44198 @configurations={}>, @enable_dependency_loading=false, @read_encrypted_secrets=false, @content_security_policy=nil, @content_security_policy_report_only=false, @content_security_policy_nonce_generator=nil, @content_security_policy_nonce_directives=nil, @require_master_key=false, @loaded_config_version=7.0, @credentials=#<ActiveSupport::OrderedOptions {:content_path=>#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/credentials.yml.enc>, :key_path=>#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/master.key>}>, @disable_sandbox=false, @add_autoload_paths_to_load_path=true, @permissions_policy=nil, @rake_eager_load=false, @server_timing=true, @paths=#<Rails::Paths::Root:0x0000000109f9a2e0 @path=#<Pathname:/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual>, @root={"app"=>#<Rails::Paths::Path:0x0000000109f9a128 @paths=["app"], @current="app", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="{*,*/concerns}", @exclude=["assets", "javascript"], @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/assets"=>#<Rails::Paths::Path:0x0000000109f99fc0 @paths=["app/assets"], @current="app/assets", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/controllers"=>#<Rails::Paths::Path:0x0000000109f99ef8 @paths=["app/controllers"], @current="app/controllers", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/channels"=>#<Rails::Paths::Path:0x0000000109f99e58 @paths=["app/channels"], @current="app/channels", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/helpers"=>#<Rails::Paths::Path:0x0000000109f99db8 @paths=["app/helpers"], @current="app/helpers", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/models"=>#<Rails::Paths::Path:0x0000000109f99d18 @paths=["app/models"], @current="app/models", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/mailers"=>#<Rails::Paths::Path:0x0000000109f99c78 @paths=["app/mailers"], @current="app/mailers", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/views"=>#<Rails::Paths::Path:0x0000000109f99bd8 @paths=["app/views"], @current="app/views", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib"=>#<Rails::Paths::Path:0x0000000109f99b38 @paths=["lib"], @current="lib", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "lib/assets"=>#<Rails::Paths::Path:0x0000000109f99a70 @paths=["lib/assets"], @current="lib/assets", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/tasks"=>#<Rails::Paths::Path:0x0000000109f999d0 @paths=["lib/tasks"], @current="lib/tasks", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="**/*.rake", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config"=>#<Rails::Paths::Path:0x0000000109f99958 @paths=["config"], @current="config", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environments"=>#<Rails::Paths::Path:0x0000000109f99840 @paths=["config/environments"], @current="config/environments", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="development.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/initializers"=>#<Rails::Paths::Path:0x0000000109f997a0 @paths=["config/initializers"], @current="config/initializers", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/locales"=>#<Rails::Paths::Path:0x0000000109f99700 @paths=["config/locales"], @current="config/locales", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="**/*.{rb,yml}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes.rb"=>#<Rails::Paths::Path:0x0000000109f99688 @paths=["config/routes.rb"], @current="config/routes.rb", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes"=>#<Rails::Paths::Path:0x0000000109f995e8 @paths=["config/routes"], @current="config/routes", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db"=>#<Rails::Paths::Path:0x0000000109f99570 @paths=["db"], @current="db", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/migrate"=>#<Rails::Paths::Path:0x0000000109f994f8 @paths=["db/migrate"], @current="db/migrate", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/seeds.rb"=>#<Rails::Paths::Path:0x0000000109f99480 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Rails::Paths::Path:0x0000000109f993e0 @paths=["vendor"], @current="vendor", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Rails::Paths::Path:0x0000000109f99340 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/database"=>#<Rails::Paths::Path:0x0000000109f992a0 @paths=["config/database.yml"], @current="config/database", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/secrets"=>#<Rails::Paths::Path:0x0000000109f99200 @paths=["config"], @current="config/secrets", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob="secrets.yml{,.enc}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environment"=>#<Rails::Paths::Path:0x0000000109f99160 @paths=["config/environment.rb"], @current="config/environment", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/templates"=>#<Rails::Paths::Path:0x0000000109f990e8 @paths=["lib/templates"], @current="lib/templates", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "log"=>#<Rails::Paths::Path:0x0000000109f98ff8 @paths=["log/development.log"], @current="log", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public"=>#<Rails::Paths::Path:0x0000000109f98f80 @paths=["public"], @current="public", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/javascripts"=>#<Rails::Paths::Path:0x0000000109f98f08 @paths=["public/javascripts"], @current="public/javascripts", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/stylesheets"=>#<Rails::Paths::Path:0x0000000109f98e90 @paths=["public/stylesheets"], @current="public/stylesheets", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "tmp"=>#<Rails::Paths::Path:0x0000000109f98e18 @paths=["tmp"], @current="tmp", @root=#<Rails::Paths::Root:0x0000000109f9a2e0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @cache_classes=false>
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environments/development.rb:37:in `block in <main>'
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environments/development.rb:3:in `<main>'
/Users/me/ws/tzif.io/hix/tryouts/sqlite_rollup_manual/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)
  </pre>
</details>

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
I can reproduce on rails 7.0.4, but cannot on `main`. That was already fixed by https://github.com/rails/rails/pull/45354.

**Comment by wscourge** [comment]
OK, thank you. Closing.

**Comment by skipkayhil** [comment]
Reopening because #45354 is is included in 7.0.4 but did not fix the issue. I opened #46308 to address it for the next 7.0 release.

**Comment by wilsonsilva** [comment]
I started getting this on `7.0.4`. Here's the command I used:
```
rails new bug \
--database=postgresql \
--skip-keeps \
--skip-active-job \
--skip-test \
--css tailwind
```
