### ISSUE TITLE
Primary key is not updated when using another mechanism than auto increment, such as Vitess sequences

### ISSUE THREAD

**Issue by dbussink** [rails/rails#50001]
### Steps to reproduce

When you run your Rails app against a sharded database using Vitess and when [Vitess sequences](https://vitess.io/docs/17.0/reference/features/vitess-sequences/) are used for primary keys, those are no longer set properly on the object when it is stored. 

At the MySQL protocol level, `last_insert_id` is still set and available. The problem is due to https://github.com/rails/rails/pull/48241 which hardcodes the assumption that you must be using the `auto_increment` flag on the primary key. In general, that is not recommended with Vitess since in case of wrong usage, you can generate duplicate primary keys on different shards. 

I was a bit surprised here that GitHub didn't already run into this as well, but @arthurschreiber has more details on why there. 

There are a few somewhat related issues where this assumption from the referenced PR also caused problems. https://github.com/rails/rails/pull/49955 seems to be a work in progress fix, but not 100% sure if that also solves this case. Also cc @fatkodima as the author of that PR who might know if it also resolves this issue.

### Expected behavior

The primary key value is filled in on the model.

### Actual behavior

The primary key value is missing and the value from `last_insert_id` is ignored.

### System configuration
**Rails version**:

7.1.1

**Ruby version**:

3.2.2

**Comment by arthurschreiber** [comment]
> I was a bit surprised here that GitHub didn't already run into this as well, but @arthurschreiber has more details on why there.

The schemas on our individual shards still have the `AUTO_INCREMENT` option set on their primary keys, which is why we don't run into this problem. This is not _great_, and something I'd like to get fixed eventually (which would then cause us to run into this problem as well).

**Comment by dbussink** [comment]
Right now we're doing the following workaround:

```
# frozen_string_literal: true

module ShardedTable
  # This is necessary because a recent change in rails makes it so that only
  # auto increment columns will be set following an insert. Since sharded
  # tables in vitess are not auto increment (because ids are assigned by vitess
  # sequences), this causes models to not get their id assigned after they are
  # created.
  #
  # This is a work around until this is fixed in rails hopefully.
  def _returning_columns_for_insert
    [primary_key]
  end
end
```

That's of course not a great way, since it overwrites internal private APIs. Even if the current behavior is classified as "works as intended", it would be great to have a way to overwrite that configuration in a supported way and not with a hack like the above.

**Comment by fatkodima** [comment]
> https://github.com/rails/rails/pull/49955 seems to be a work in progress fix, but not 100% sure if that also solves this case. Also cc @fatkodima as the author of that PR who might know if it also resolves this issue.

That PR is going to always include a primary key in the returning (https://github.com/rails/rails/pull/49955/files#r1385679027), so I think yes, that should solve this issue. Do you use MariaDB?

**Comment by dbussink** [comment]
@fatkodima no, we use Vitess and MySQL.

**Comment by nvasilevski** [comment]
@dbussink out of curiosity, given a column name and a table name, is there any way to ask Vitess whether the column is being populated by a sequence? Or perhaps the opposite, is there a way to get all the sequences along with columns that use the value from it? Sorry couldn't immediately see it in the Vitess docs. Thanks!

**Comment by dbussink** [comment]
> UPD: I think it should be possible if we read `VSchema` as on the example below:

That's not available over the MySQL protocol interface though and through an entirely separate path with Vitess specific tooling. I don't think it's really suited for Rails to directly read and seems like an overly complex solution. 

For us what would be ideal is that if a record has no primary key value and `last_insert_id` returns a value, it would update the record with that. If that's not possible, that at a minimum a way to configure / hook into it to create that behavior (like a blessed way to do https://github.com/rails/rails/issues/50001#issuecomment-1805768840 then essentially).

**Comment by nvasilevski** [comment]
>I don't think it's really suited for Rails to directly read and seems like an overly complex solution.

I agree, I wasn't strongly considering it as a solution but was curious if for whatever reason I wanted to peek at this connection between the column name and vitess sequence where would I go. Thanks for clarifying!

**Comment by nvasilevski** [comment]
Hey folks, wanted to provide an update on what I think the state of this issue is:

- This is definitely a problem and more applications will experience it sooner or later
- This will most likely be fixed by ensuring we at least ask database to return `primary_key` value back if Rails wasn't able to find any auto-populated columns. I expect the fix to be the same as whichever fix is accepted for https://github.com/rails/rails/issues/49950 Possibly https://github.com/rails/rails/pull/49955
- While it may be sufficient to always append `primary_key` to the return columns list to fix this issue I think Rails still needs a way for application to manually declare list of columns that must be placed in the `RETURN` statement because Rails won't be able to detect if column is auto-populated by a db trigger, for example. PR fox this is https://github.com/rails/rails/pull/48434

**Comment by nvasilevski** [comment]
Should be fixed by https://github.com/rails/rails/pull/50783 and backported to `7-1-stable`
Please feel free to reopen if the fix doesn't work or it didn't cover your corner case. Thank you!

**Comment by dbussink** [comment]
@nvasilevski I'm testing upgrading to Rails 7.2 (it took a while) and it looks like there are things still missing this doesn't work. Looking at https://github.com/rails/rails/pull/50783, the scenario here is clear why it's not working either as well. 

The problem is that the table we have also has a number of other columns that are matched on auto returning values (they are `datetime` fields with a `CURRENT_TIMESTAMP(6)` default). 

So the returned columns doesn't end up including our `id` field which was set through a Vitess sequence. Is this something I should open up a new issue for? 

https://github.com/rails/rails/pull/48434 maybe would help to manually override the custom patch we'll have to keep then to enforce using the actual primary key value we got back.

**Comment by dbussink** [comment]
I think the control needed here in the end is not at the columns level, but being able to define / override `ActiveRecord::ConnectionAdapters::Column#auto_incremented_by_db?` somehow to specify that a certain column really is an auto increment under Vitess because right now that's tightly coupled to the schema.

**Comment by nvasilevski** [comment]
>the table we have also has a number of other columns that are matched on auto returning values (they are datetime fields with a CURRENT_TIMESTAMP(6) default)

Ugh, right, sorry :( 

>Is this something I should open up a new issue for?

Let's reopen this one

>being able to define / override ActiveRecord::ConnectionAdapters::Column#auto_incremented_by_db?

It is an option but I really want Rails to be capable of taking care of that, especially because it used to work fine, even if by an accident.

What I think is wrong right now is that we try to build an `auto_populated_columns` array even though we know that mysql will not be bothered by it as it's only capable of returning one value after insertion and this is the value of the primary key.
https://github.com/Shopify/rails/blob/5520bd835e3724ffafe3f719f9aafe951567f2f3/activerecord/lib/active_record/model_schema.rb#L438
So trying to dynamically find some columns feels semantically wrong as we know we won't be able to use it due to database limitations.
What I'd like to try is to avoid building `auto_populated_columns` if `supports_insert_returning?` is `true` for the given adapter. This sounds correct as I don't want to see `Model._returning_columns_for_insert` to ever return anything other than a primary key (if exists) when executed against mysql adapter (non-mariadb)

Though it may break in the future if mysql ever supports `RETURNING` statement. So I'd like to try adding `supports_insert_returning?` check along with always prepending the `primary_key` to the list. And unless I'm missing something that should result in `_returning_columns_for_insert` being `[primary_key]` for adapters that don't support `RETURNING` and `[primary_key, *auto_populated_columns].uniq` for adapters that do. This way `primary_key` will always be assumed to be returned as long as it exists and regardless of its properties like autoincrement.

I'll create a PR sometime this week and see if it works
