### ISSUE TITLE
Attribute aliases don't resolve dynamically like normal attribute methods

### ISSUE THREAD

**Issue by ajvondrak** [rails/rails#51717]
With #48533 circa Rails 7.1, attribute methods and aliases are defined "lazily" on AR subclasses, meaning they get defined on the first call to `ActiveRecord::Base#initialize` via `#init_internals`: https://github.com/rails/rails/blob/1818beb3a3ea5fdb498095d4885f8a7e512f24ca/activerecord/lib/active_record/core.rb#L755-L756

Since defining attribute methods (and thus aliases atop of them) may involve querying the database, it's preferable to evaluate these lazily, rather than (say) tying them to class definition time as the Rails app starts up.

However, when loading a model from a cache in a process that has yet to connect to the database, we can manage to create a new instance of an `ActiveRecord::Base` subclass _without_ calling the initializer, so the attribute methods & aliases never get defined by `#init_internals`. (Yes, we probably don't want to be storing models in the cache due to other issues like #49826. But the lazy evaluation does still cause a regression in behavior versus Rails 7.0, so I thought it was worth bringing up.)

This works out fine for regular attribute methods, since the `#attribute_missing` hook will dynamically look up values in the `@attributes` at run time: https://github.com/rails/rails/blob/c3c164ca12410983e07537531844c4255450ba9b/activemodel/lib/active_model/attribute_methods.rb#L484-L491 https://github.com/rails/rails/blob/c3c164ca12410983e07537531844c4255450ba9b/activemodel/lib/active_model/attribute_methods.rb#L498-L500

However, attribute aliases perform no such `method_missing` magic. This can lead us to fail with a `NoMethodError`—or perhaps more insidiously, silently delegate to a supermethod that _would_ have been clobbered by the alias.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 7.1.0"
  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "active_support/cache"
require "minitest/autorun"
require "logger"
require "tempfile"

database = Tempfile.create # shared database file so separate processes can reference it
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: database.path)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :models, force: true do |t|
    t.string :old_name
    t.string :value_from_attribute
  end
end

class Model < ActiveRecord::Base
  alias_attribute :new_name, :old_name

  def value_from_attribute_or_supermethod
    "value from supermethod"
  end
end

class ModelWithSupermethod < Model
  alias_attribute :value_from_attribute_or_supermethod, :value_from_attribute
end

$cache = ActiveSupport::Cache::FileStore.new(Dir.mktmpdir("file-store-")) # file store so separate processes can reference it

class AliasedAttributesTest < Minitest::Test
  def setup
    $cache.clear
  end

  def test_read_model_from_cache_without_connecting_to_database
    pid = fork do
      refute Model.instance_methods.include?(:old_name), "expected model not to define attribute methods until initialization"
      refute Model.instance_methods.include?(:new_name), "expected model not to define attribute aliases until initialization"
      model = Model.create!(old_name: "test")
      assert Model.instance_methods.include?(:old_name), "expected model to have lazily defined attribute methods on initialization"
      assert Model.instance_methods.include?(:new_name), "expected model to have lazily defined attribute aliases on initialization"
      assert_equal "test", model.old_name
      assert_equal "test", model.new_name
      $cache.write('model', model)
    end
    Process.wait(pid)
    assert $cache.exist?('model'), "expected cache to be populated by a separate process"
    refute Model.instance_methods.include?(:old_name), "expected separate process not to affect method definitions in this process"
    refute Model.instance_methods.include?(:new_name), "expected separate process not to affect method definitions in this process"
    model = $cache.read('model')
    refute Model.instance_methods.include?(:old_name), "expected model not to have defined attribute methods yet, since we haven't initialized"
    refute Model.instance_methods.include?(:new_name), "expected model not to have defined attribute aliases yet, since we haven't initialized"
    assert_instance_of Model, model
    assert_equal "test", model.old_name, "expected attribute method to still work dynamically due to attribute_missing hook"
    begin
      assert_equal "test", model.new_name
    rescue NoMethodError => e
      flunk "attribute aliases do not perform any method_missing magic\n#{e.class}: #{e.message}"
    end
  end

  def test_alias_that_should_have_clobbered_supermethod
    pid = fork do
      model = ModelWithSupermethod.new(value_from_attribute: "value from attribute")
      assert_equal "value from attribute", model.value_from_attribute_or_supermethod
      $cache.write('model', model)
    end
    Process.wait(pid)
    assert $cache.exist?('model'), "expected cache to be populated by a separate process"
    model = $cache.read('model')
    assert_instance_of ModelWithSupermethod, model
    assert_equal "value from attribute", model.value_from_attribute_or_supermethod, "supermethod did not get shadowed by attribute alias"
  end
end
```

### Expected behavior

Test cases above should pass.

### Actual behavior

```
F

Failure:
AliasedAttributesTest#test_read_model_from_cache_without_connecting_to_database [repro.rb:71]:
attribute aliases do not perform any method_missing magic
NoMethodError: undefined method `new_name' for #<Model id: 1, old_name: "test", value_from_attribute: nil>


bin/rails test repro.rb:48

F

Failure:
AliasedAttributesTest#test_alias_that_should_have_clobbered_supermethod [repro.rb:85]:
supermethod did not get shadowed by attribute alias.
Expected: "value from attribute"
  Actual: "value from supermethod"


bin/rails test repro.rb:75
```

### System configuration

**Rails version**: 7.1

**Ruby version**: 3.2.2

**Comment by justinko** [comment]
This fixes it: https://github.com/justinko/rails/commit/6b46732ed5b025ec02e85210429d2395497ce5bb

**Comment by justinko** [comment]
If attribute methods are lazily loaded, and aliases are tied to attributes (and should only be tied to attributes), then how would it be possible to make aliases lazy?

**Comment by byroot** [comment]
So part of this has been fixed in https://github.com/rails/rails/pull/50594, but the 7.1 ain't trivial.

**Comment by zzak** [comment]
There was a backport in #50705 but I don't have enough context here to say whether or not this is closed.

**Comment by ajvondrak** [comment]
FWIW, I ran the repro script above against Rails 7.1.4, and while one of the tests was fixed, the other one involving supermethods is still broken:

```
$ ruby tests.rb
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
-- create_table(:models, {:force=>true})
D, [2024-09-26T11:50:03.984482 #76007] DEBUG -- :    (0.2ms)  DROP TABLE IF EXISTS "models"
D, [2024-09-26T11:50:03.985733 #76007] DEBUG -- :    (0.8ms)  CREATE TABLE "models" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "old_name" varchar, "value_from_attribute" varchar)
   -> 0.0168s
D, [2024-09-26T11:50:03.986820 #76007] DEBUG -- :    (0.2ms)  CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY)
D, [2024-09-26T11:50:03.987916 #76007] DEBUG -- :    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2024-09-26T11:50:04.006022 #76007] DEBUG -- :   ActiveRecord::InternalMetadata Load (4.2ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
D, [2024-09-26T11:50:04.006714 #76007] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.3ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ('environment', 'development', '2024-09-26 18:50:04.006087', '2024-09-26 18:50:04.006090') RETURNING "key"
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from new at tests.rb:41)
Run options: --seed 39826

# Running:

D, [2024-09-26T11:50:04.075480 #76008] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
D, [2024-09-26T11:50:04.076164 #76008] DEBUG -- :   Model Create (0.8ms)  INSERT INTO "models" ("old_name") VALUES (?) RETURNING "id"  [["old_name", "test"]]
D, [2024-09-26T11:50:04.076929 #76008] DEBUG -- :   TRANSACTION (0.1ms)  commit transaction
.F

Failure:
AliasedAttributesTest#test_alias_that_should_have_clobbered_supermethod [tests.rb:85]:
supermethod did not get shadowed by attribute alias.
Expected: "value from attribute"
  Actual: "value from supermethod"


bin/rails test tests.rb:75



Finished in 0.190268s, 10.5115 runs/s, 57.8132 assertions/s.
2 runs, 11 assertions, 1 failures, 0 errors, 0 skips
```

So I suppose this isn't closed quite yet.
