### ISSUE TITLE
Test names are missing after updating to 7.2 when running "rails test -v"

### ISSUE THREAD

**Issue by xeron** [rails/rails#52697]
### Steps to reproduce

**The amount of tests should be enough for rails to start running them in parallel.**

* Run `./bin/rails test -v` with 7.1
* Run `./bin/rails test -v` with 7.2
* Compare output

With the new app:
```
bundle exec rails new --skip-docker --skip-jbuilder -f .
./bin/rails g scaffold post author:string title:string
./bin/rails g scaffold tag name:string
./bin/rails g scaffold author name:string
./bin/rails g scaffold category name:string
./bin/rails g scaffold car make:string model:string
./bin/rails g scaffold city name:string location:string
./bin/rails g scaffold parent name:string
./bin/rails g scaffold child name:string
./bin/rails db:migrate
./bin/rails test -v
```

Setting `parallelize(workers: 1)` in `class ActiveSupport::TestCase` fixes the issue.

### Expected behavior

```
$ ./bin/rails test -v
…
PostTest#test_default_order_by_published_at = 0.14 s = .
PostTest#test_: associations should have a has_many_attached called files.  = 0.00 s = .
DriversControllerTest#test_should_redirect_to_drivers_list_when_search_query_is_missing = 0.15 s = .
…
```

### Actual behavior

```
$ ./bin/rails test -v
…
0.21 s = .
0.22 s = .
0.20 s = .
…
```

### System configuration

**Rails version**: `7.2.1`
**Ruby version**: `3.1.6p260`

**Comment by rafaelfranca** [comment]
Did you try to reproduce in a new application?

**Comment by xeron** [comment]
Yes. It starts happening even in new application as soon as tests start to run in parallel. Creating a bunch of scaffolds easily triggers it.

**Comment by rafaelfranca** [comment]
Got it. I believe it is because of https://github.com/rails/rails/commit/932af452e865f80c4f76f9525ff1a274d58da1be. Maybe `prerecord` isn't called when parallelize is used.

**Comment by rafaelfranca** [comment]
Yes. It isn't called by our worker https://github.com/rails/rails/blob/ec667e5f114df58087493096253541f1034815af/activesupport/lib/active_support/testing/parallelization/worker.rb#L49

**Comment by jhawthorn** [comment]
Thanks for the report. This should be fixed by #52917, which I've backported into 7-2-stable and should make it into the next release

**Comment by xeron** [comment]
@jhawthorn running tests with `7.2.1.1` and I still see this issue.

**Comment by jhawthorn** [comment]
Yep! 7.2.1.1 is a security release only includes security patches on top of 7.2.1. This will be included u 7.2.2
