### ISSUE TITLE
`has_one ..., dependent: :destroy` behaves differently in 7.0.6 and 7.0.7

### ISSUE THREAD

**Issue by woto** [rails/rails#53670]
Hello, everyone, am I missed something or rails has a regression in `has_one ..., dependent :destroy` feature between 7.0.6 and 7.0.7?

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # NOTE: the test passes with 7.0.6, but does not pass with 7.0.7
  gem "rails", '7.0.7'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", '1.5'
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :status
  end
end

class Post < ActiveRecord::Base
  has_one :comment, -> { where(status: 'unique') }, dependent: :destroy
end

class Comment < ActiveRecord::Base
  belongs_to :post

  validates :post_id, uniqueness: true

  # validate do
  #   errors.add(:post, :error) if Comment.where(post_id:, ...).count.positive?
  # end
end

class BugTest < ActiveSupport::TestCase
  def test_dependent_removed
    Post.destroy_all
    Comment.destroy_all

    post = Post.create!
    post.create_comment!(status: 'unique')
    post.create_comment!(status: 'unique')

    assert_equal 1, Comment.count
  end
end
```

Here is the output, using Rails 7.0.6
![image](https://github.com/user-attachments/assets/98192666-ad4b-48e1-b7e5-40f67c6ea32c)

And here is output, using Rails 7.0.7
![image](https://github.com/user-attachments/assets/12111412-7284-4029-b481-6f1b076812cf)

I would appreciate any help in understanding :hugs:

**Comment by zzak** [comment]
Sorry this was changed in #48809, for reference.

I would recommend upgrading to the latest patch level, because this behavior was changed in 7.0.5, but we fixed it in 7.0.7. We try to only include bug fixes in the patch level, so they are intended to be safe.

**Comment by woto** [comment]
@zzak Hi, thank you for response. Ok, I understand, but we experienced this error in 7.2.2. I just wanted highlight the moment when it's happened.

**Comment by woto** [comment]
@zzak :) There is misunderstanding, I meant that the problem still exists.

It's fails.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: 'rails/rails'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :status
  end
end

class Post < ActiveRecord::Base
  has_one :comment, -> { where(status: 'unique') }, dependent: :destroy
end

class Comment < ActiveRecord::Base
  belongs_to :post

  validates :post_id, uniqueness: true

  # validate do
  #   errors.add(:post, :error) if Comment.where(post_id:, ...).count.positive?
  # end
end

class BugTest < ActiveSupport::TestCase
  def test_dependent_removed
    Post.destroy_all
    Comment.destroy_all

    post = Post.create!
    post.create_comment!(status: 'unique')
    post.create_comment!(status: 'unique')

    assert_equal 1, Comment.count
  end
end
```

**Comment by woto** [comment]
@zzak Ok,understand. Thank you :+1:
