### ISSUE TITLE
`ActiveRecord::UnmodifiableRelation` occurs when passing a string to `.group` and calling `.count` then `.reload`.

### ISSUE THREAD

**Issue by kehra** [rails/rails#53934]
After upgrading from version 7.1 to 7.2, `ActiveRecord::UnmodifiableRelation` error started occurring.

I pass a string as an argument to the `.group` method of ActiveRecord object and call the `.count` method. Then, after updating the associated records, I call the `.reload` method to refresh the state and attempt to call the `.count` method again, but it results in an `ActiveRecord::UnmodifiableRelation` error.

I'm not sure whether this behavior is intentional, but since the error does not occur depending on the method arguments passed to the `.group` method, I created this issue.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < ActiveSupport::TestCase
  def test_association_stuff
    post = Post.create!
    post.comments.create!

    posts = Post.joins(:comments).group('comments.id')

    assert_equal({1 => 1}, posts.count)

    post.comments.create!

    posts.reload # `ActiveRecord::UnmodifiableRelation` occurs here
    assert_equal({1 => 1, 2 => 1}, posts.count)
  end
end
```

### Expected behavior
We can call `.reload` successfully.

### Actual behavior
`ActiveRecord::UnmodifiableRelation` occurs when we call `.reload`.

### System configuration
**Rails version**:
7.2.2.1, 8.0(main)

**Ruby version**:
3.3

**Comment by Jay0921** [comment]
@kehra The issue is actually comes from `count`, not from `reload`. I’m not very familiar with the [UnmodifiableRelation](https://edgeapi.rubyonrails.org/classes/ActiveRecord/UnmodifiableRelation.html) error, but based on the documentation, you can’t modify a loaded relation. Calling `count` on a loaded relation will re-query the database, which triggers the error. To solve this in your case, you can use .size instead of .count.

**Comment by kehra** [comment]
@Jay0921 
Thanks for replying.

However, if the argument for `.group` is changed to `:id`, no error occurs, so I think it is not an issue with `.count`.
For example, making the following change does not cause an error.

```diff
--- test.rb     2024-12-13 23:18:47.301787586 +0900
+++ test2.rb    2024-12-13 23:18:31.166493789 +0900
@@ -47,13 +47,15 @@
     post = Post.create!
     post.comments.create!

-    posts = Post.joins(:comments).group('comments.id')
+    posts = Post.joins(:comments).group(:id)

     assert_equal({1 => 1}, posts.count)

     post.comments.create!

     posts.reload
-    assert_equal({1 => 1, 2 => 1}, posts.count)
+    assert_equal({1 => 2}, posts.count)
   end
 end
```

**Comment by kehra** [comment]
My explanation was slightly incorrect.
I don't think it's solely an issue with `.count`.
However, I'm not sure if this behavior is intentional or not.

**Comment by Jay0921** [comment]
**Below are my findings:**

When we call `count` on a loaded relation object, the existing relation object is reused for the operation. If the relation is already loaded, the instance variable `@loaded` is set to `true`. When `@loaded` is `true`, modifying the existing relation object raises an `ActiveRecord::UnmodifiableRelation` error.

https://github.com/rails/rails/blob/79c206ffa637f3d9cae8903b99666e69866008fb/activerecord/lib/active_record/relation/query_methods.rb#L1746-L1748

---

**First Example:**
```ruby
posts = Post.joins(:comments).group(:id)
posts.reload
posts.count
```
_Why it works:_
The `group(:id)` operation does not modify the existing relation object before creating a new one. As a result, the count method executes without issues.

---

**Second Example:**
```ruby
posts = Post.joins(:comments).group('comments.id')
posts.reload
posts.count # Raises ActiveRecord::UnmodifiableRelation
```
_Why it raises an error:_
The `group('comments.id')` operation tries to modify the existing relation object before creating a new one. Since the relation is already loaded (`@loaded `= `true`), this triggers the `ActiveRecord::UnmodifiableRelation` error.

The error is triggered in the following code:
https://github.com/rails/rails/blob/79c206ffa637f3d9cae8903b99666e69866008fb/activerecord/lib/active_record/relation/query_methods.rb#L1974

---
**Workaround:**
To avoid the `ActiveRecord::UnmodifiableRelation` error, we can use the `reset` method before calling count:
```ruby
posts = Post.joins(:comments).group('comments.id')
posts.reload
posts.reset
posts.count
```
_Why it works:_
The reset method clears the existing relation object and sets `@loaded` to `false`. This allows the relation object to be modified without triggering the `ActiveRecord::UnmodifiableRelation` error.

---

**Proposed solution:**
Since the `count` method is supposed to query the database to get the count, so it is safe for us to call the `reset` method inside calculation method and that would solve the issue. But, I'm not sure if this approach has any side effects.
```ruby
def execute_grouped_calculation
  reset
  ...existing code
end
```
https://github.com/rails/rails/blob/79c206ffa637f3d9cae8903b99666e69866008fb/activerecord/lib/active_record/relation/calculations.rb#L516-L517

**Comment by cgunther** [comment]
This looks similar to #53260, which was fixed by #53264, and also similar to #53983 (though that doesn't seem to fix this specific issue), both of which seem to stem from #53064.

**Comment by kamipo** [comment]
Fixed by #53983.

**Comment by cgunther** [comment]
I don't think #53983 actually fixed this as the original steps to reproduce still fail against main after the merge, though it definitely seems highly similar. I think the grouping here triggers a slightly different code path that likely needs it's own fix. I'll see if I can work up a PR to fix this.

**Comment by kamipo** [comment]
Thanks for the report, this issue on "group by" will be fixed by #53994.

**Comment by kehra** [comment]
Thanks all 😄

**Comment by benebrice** [comment]
> Thanks for the report, this issue on "group by" will be fixed by [#53994](https://github.com/rails/rails/pull/53994).

👆🏻Tank you for that @kamipo ! 

This was merged on December 18th and latest release of Rails 7.2.2.1 was wrapped up on 10th so this is bug is actually still on latest Rails 7 version. 

Can we imagine to add it as well on a version 7.2.2.2?

**Comment by kamipo** [comment]
That was backported at 789d6cf1a923a99ea0add3dd0814a22b7cc7860a to 7-2-stable branch, so it will be included in the 7.2.3 release.
