### ISSUE TITLE
Race condition in with_routing integration test helper

### ISSUE THREAD

**Issue by quixoten** [rails/rails#54595]
### Steps to reproduce

Hoping to get some guidance on making a consistent reproducible example. The error I'm observing (`No Failure App provided`) is occurring during `bin/rails test` and originates in the [warden gem](https://github.com/wardencommunity/warden/blob/67f5ba6baaa7564ec79afef02cf3a4d0f7d312e5/lib/warden/manager.rb#L145). This only occurs about 20% of the time, i.e., running `bin/rails test` will complete without errors 4/5 times. The error only occurs when using the `with_routing` helper, e.g., 

```ruby
class ErrorPagesConcernTest < ActionDispatch::IntegrationTest
  with_routing do |routes|
    routes.draw do
      %w[action_not_found invalid_authenticity_token name_error no_method_error record_not_found routing_error standard_error].each do |action|
        get "/default/#{action}", to: "error_pages_test##{action}"
        get "/rescued/#{action}", to: "rescued_error_pages_test##{action}"
      end
    end
  end
  
  ...
end
```

However, when I remove the `with_routing` helper and put the testing routes directly in `routes.rb`, the test suite runs without error 100% of the time.

### Expected behavior

The results of a test suit should be consistent when using the `with_routing` helper.

### Actual behavior

Using the `with_routing` helper causes inconsistent results in tests.

### System configuration

**Rails version**: 8.0.1

**Ruby version**: 3.2.6

**Comment by byroot** [comment]
> Here's the the complete test code if it helps.

Could you try turning it into an self contained executable test case?  https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

**Comment by Edouard-chin** [comment]
Are you using the `warden` directly or through another gem like `devise`?

I know that the `devise` gem has one issue after Rails introduced the LazyRouteSet feature which could break some tests depending on the order they'd run.
Can you reproduce the issue consistently when running the tests with the same seed?

**Comment by quixoten** [comment]
> Are you using the `warden` gem directly or through another gem like `devise`?
> 
> I know that the `devise` gem had one issue after Rails introduced the LazyRouteSet feature which could break some tests depending on the order they'd run. Can you reproduce the issue consistently when running the tests with the same seed?

I am using devise. Oddly, running with the same seed does not fail consistently.

**Comment by quixoten** [comment]
Actually, with `PARALLEL_WORKERS=1 bin/rails test` I can find seeds that always fail in the same way. It fails more often than not with `PARALLEL_WORKERS=1`, but I can also find seeds that always succeed.

**Comment by Edouard-chin** [comment]
Ah so that very sounds like the issue I mentioned. It was fixed in https://github.com/heartcombo/devise/pull/5728. Try to point your Gemfile on devise's main branch from github as the fix hasn't been made to a release yet and see if this fixes it.

**Comment by quixoten** [comment]
@Edouard-chin, thanks for the guidance! I found that my tests still failed consistently (`PARALLEL_WORKERS=1 bin/rails test --seed 29227`) using the `main` branch of devise, but it got me on the right track. After adding `Rails.application.try(:reload_routes_unless_loaded)` to my test:

```ruby
class ErrorPagesTest < ActionDispatch::IntegrationTest
  Rails.application.try(:reload_routes_unless_loaded)

  with_routing do |routes|
  ...
  end

  ...
end
```

my test suite passes consistently again. I found that I had to call `reload_routes_unless_loaded` before `with_routing` to get it to work. Putting it inside the `with_routing` block had no effect. I also verified that the following "patch" worked:

```ruby
module ActionDispatch::Assertions::RoutingAssertions::WithIntegrationRouting::ClassMethods
  def with_routing(&block)
    Rails.application.try(:reload_routes_unless_loaded)
    # .. existing code left unchanged
  end
end
```

Would it make sense to open a PR with this change? Would all the `with_routing` methods (I count 4) require this addition?

**Comment by quixoten** [comment]
Here's an executable reproduction:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
  gem "devise", github: "heartcombo/devise", ref: "fec67f98f26fcd9a79072e4581b1bd40d0c7fa1d"
  gem "sqlite3"
end

require "action_controller/railtie"
require "active_record/railtie"
require "devise/orm/active_record"
require "minitest/autorun"
require "rack/test"

ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.root = __dir__
  config.eager_load = false
  config.hosts.clear
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  config.active_record.encryption.primary_key = "primary_key"
  config.active_record.encryption.deterministic_key = "deterministic_key"
  config.active_record.encryption.key_derivation_salt = "key_derivation_salt"
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end
end

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

USERS = {
  one: User.create!(email: "one@example.com", password: "secret")
}

Rails.application.routes.draw do
  devise_for :users

  # NOTE: if you uncomment this route and remove the with_routing block below,
  # the error (No Failure App provided) goes away

  # get "/no-failure-app", to: "no_failure_app#index"
end

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

class NoFailureAppController < ApplicationController
  def index
    render json: { msg: "no failure app" }
  end
end

class NoFailureAppControllerTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers

  # NOTE: If you remove this with_routing block and uncomment the route above,
  # the error (No Failure App provided) goes away

  with_routing do |routes|
    routes.draw do
      get "/no-failure-app", to: "no_failure_app#index"
    end
  end

  def test_no_failure_app
    get "/no-failure-app"
    assert_response :found
  end
end
```

**Comment by yedhink** [comment]
I tested the executable test code. For some reason the `warden_config.failure_app` is getting reset to `nil` in the `with_routing` block, which in turn leads to a `500 internal server error`: https://github.com/heartcombo/devise/blob/main/lib/devise.rb#L489

I even tried setting the Devise mapping, which in turn adds a [default_failure_app](https://github.com/heartcombo/devise/blob/fec67f98f26fcd9a79072e4581b1bd40d0c7fa1d/lib/devise/mapping.rb#L123-L129), but that was also in vain because the `warden_config` is getting reset:
```diff
with_routing do |routes|
    routes.draw do
+      devise_for :users
      get "/no-failure-app", to: "no_failure_app#index"
    end
  end
```

Before the `with_routing` block:
```
(byebug) Devise.warden_config
{default_scope: nil, scope_defaults: {}, default_strategies: {}, intercept_401: false, failure_app: #<Devise::Delegator:0x0000000129accf18>}
```

After the `with_routing` block:
```
(byebug) Devise.warden_config
{default_scope: :default, scope_defaults: {}, default_strategies: {}, intercept_401: true}
```


On another note, I think we are supposed to pass assertions associated with custom routes within the `with_routing` block - refer: https://api.rubyonrails.org/v8.0/classes/ActionDispatch/Assertions/RoutingAssertions.html#method-i-with_routing:
```rb
  def test_no_failure_app
    with_routing do |routes|
      routes.draw do
        devise_for :users
        get '/no-failure-app', to: 'no_failure_app#index'
      end

      get '/no-failure-app'
      assert_response :found
    end
  end
```

I still havent' figured out what's resetting the `warden_config` when `with_routing` block gets executed.

**Comment by Edouard-chin** [comment]
Thanks for the reproduction script! It's indeed a problem in devise that started since Rails 7.2

I submitted a PR to fix this upstream: https://github.com/heartcombo/devise/pull/5769 Hopefully it will get accepted.

I'll close this issue since there is not much to do in Rails.

**Comment by Edouard-chin** [comment]
I'm going to reopen because after digging, I think I found a legitimate issue with the `with_routing` implementation. I originally closed as I saw that devise was using some sort of monkeypatch on the RouteSet object and I figured this would need to be fixed there.

But even without monkeypatching and configuring a middleware the "Rails' way", I couldn't figure out how to workaround the issue so I believe this would need to be fixed in Rails.

**Comment by byroot** [comment]
> But even without monkeypatching and configuring a middleware the "Rails' way",

You have a pure Rails repro?

**Comment by Edouard-chin** [comment]
I have opened #54705, with a concrete example. If you'd like a pure Rails repo, I can work on creating a new app and showcase the issue
